### ISSUE TITLE
The getter 'definingUnit' was called on null

### ISSUE THREAD

**Issue by neckaros** [simolus3/moor#1085]
Hello,

As soon as i create a test class like in the doc i get the following error:
```
NoSuchMethodError: The getter 'definingUnit' was called on null.
Receiver: null
Tried calling: definingUnit
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      LinkedElementFactory.isLibraryUri (package:analyzer/src/summary2/linked_element_factory.dart:133:28)
```

My test code: 
```
import 'package:moor/ffi.dart';
import 'package:flutter_test/flutter_test.dart';
// the file defined above, you can test any moor database of course
import '../lib/models/dbs/tables.dart';

void main() {
  //MyDatabase database;

  setUp(() {
    //database = MyDatabase(VmDatabase.memory());
  });
  tearDown(() async {
    //await database.close();
  });
}
```

if i remove 
`import '../lib/models/dbs/tables.dart';`
i don't get the error anymore any tables are correctly generated
This file is just a standard moor file like in the getting started doc.

I found an issue (#905 ) where it is says to downgrade analyser but i can't as older version use non null safe package and is incompatible with many packages now.

I don't get this issue with built_value

i have:
```
moor: ^4.1.0 
moor_generator: ^4.1.0
build_runner: ^1.11.0
```

**Comment by neckaros** [comment]
For information i fixed this issue with modifying my import from relative to package:

`import '../lib/models/dbs/tables.dart';`
`import 'package:packagename/models/dbs/tables.dart';`
