### ISSUE TITLE
Unknown Error only in Release Builds

### ISSUE THREAD

**Issue by alphamanorg** [simolus3/moor#1108]
Hy guys, I'm facing an unknown error. I really don't know how to fix this. It is only happening in the release build, debug builds are fine.

Here are the logs captured with the logger:

I/flutter (29760): ┌─────────────────────────────────────────────────
I/flutter (29760): │ #0   AuthBloc.onError (package:app/application/auth/auth/auth_bloc.dart:60)
I/flutter (29760): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (29760): │ ⛔ Error occurred in Auth Bloc = #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
I/flutter (29760): │ ⛔ <asynchronous suspension>
I/flutter (29760): │ ⛔ #1      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7)
I/flutter (29760): │ ⛔ <asynchronous suspension>
I/flutter (29760): │ ⛔ #2      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:153)
I/flutter (29760): │ ⛔ <asynchronous suspension>
I/flutter (29760): │ ⛔ #3      _SqfliteDelegate.open (package:moor_flutter/moor_flutter.dart:52)
I/flutter (29760): │ ⛔ <asynchronous suspension>
I/flutter (29760): │ ⛔ #4      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:253)
I/flutter (29760): │ ⛔ <asynchronous suspension>
I/flutter (29760): │ ⛔ #5      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18)
I/flutter (29760): │ ⛔ <asynchronous suspension>
I/flutter (29760): │ ⛔ #6      DatabaseConnectionUser.doWhenOpened.<anonymous closure> (package:moor/src/runtime/api/connection_user.dart:125)
I/flutter (29760): │ ⛔ <asynchronous suspension>
I/flutter (29760): │ ⛔ 
I/flutter (29760): └─────────────────────────────────────────────────

I'm using:
moor_flutter: ^4.0.0-nullsafety
moor_generator:
    git:
      url: https://github.com/simolus3/moor.git
      ref: d279f1cdffeb48235db6be41f6adf756af96f6f0
      path: moor_generator

** Flutter Doctor **

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
    • Flutter version 2.0.1 at C:\tools\flutter
    • Framework revision c5a4b4029c (2 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Aman\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\Aman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • RMX1801 (mobile) • 649cc2e9 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!

**Comment by simolus3** [comment]
It's pretty weird that this would happen in `SqfliteDatabaseFactoryMixin.getDatabasesPath` - this might be an sqflite problem unrelated to moor. Also, your logs only mention the stack trace but no actual error, can you post the error description?

**Comment by alphamanorg** [comment]
Where to log at please tell?

**Comment by simolus3** [comment]
How to log errors depends on what you use for logging. It looks like you're only printing the stack trace.
