### ISSUE TITLE
 Null check operator used on a null value when running build_runner

### ISSUE THREAD

**Issue by 0x-cell** [simolus3/moor#1166]
I've decided to update Moor to latest version and now I'm getting following crash when trying to run `flutter packages pub run build_runner build --delete-conflicting-outputs -v`

Any help appreciated as I have no idea what's wrong.

```
...
[SEVERE] moor_generator:moor_generator on lib/about.dart:

Null check operator used on a null value
#0      LinkedElementFactory.isLibraryUri (package:analyzer/src/summary2/linked_element_factory.dart:418:48)
#1      LibraryContext.isLibraryUri (package:analyzer/src/dart/analysis/library_context.dart:95:27)
#2      LibraryAnalyzer._isLibrarySource (package:analyzer/src/dart/analysis/library_analyzer.dart:511:25)
#3      LibraryAnalyzer._resolveDirectives (package:analyzer/src/dart/analysis/library_analyzer.dart:552:36)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:128:5)
#5      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:105:12)
#6      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1590:63)
#7      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#8      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1565:20)
#9      AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1644:26)
#10     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1266:20)
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2296:24)
<asynchronous suspension>

package:analyzer/src/dart/analysis/driver.dart 1619:9             AnalysisDriver._computeAnalysisResult.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 32:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1565:20            AnalysisDriver._computeAnalysisResult
package:analyzer/src/dart/analysis/driver.dart 1644:26            AnalysisDriver._computeErrors
package:analyzer/src/dart/analysis/driver.dart 1266:20            AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 2296:24            AnalysisDriverScheduler._run

[INFO] Heartbeat:18.7s elapsed, 31/47 actions completed.
[INFO] Heartbeat:19.7s elapsed, 31/47 actions completed.
[INFO] Heartbeat:20.7s elapsed, 31/47 actions completed.
[INFO] Heartbeat:21.8s elapsed, 31/47 actions completed.
[INFO] Heartbeat:22.9s elapsed, 31/47 actions completed.
[INFO] Heartbeat:23.9s elapsed, 31/47 actions completed.
[INFO] Heartbeat:25.0s elapsed, 31/47 actions completed.
[INFO] Heartbeat:26.0s elapsed, 31/47 actions completed.
[INFO] Heartbeat:27.1s elapsed, 31/47 actions completed.
[INFO] Heartbeat:28.1s elapsed, 31/47 actions completed.
[INFO] Heartbeat:29.1s elapsed, 31/47 actions completed.
```

flutter doctor 
```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (2 available)
```

pubsec.yaml
```
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0
  http: ^0.13.0
  shimmer: ^1.1.1
  moor_flutter: ^4.0.0
  moor: ^4.2.1
  provider: ^4.2.0
  cached_network_image: ^3.0.0
  flutter_inapp_purchase: ^4.0.2
  rate_my_app: ^0.6.1+6
  simple_auth: ^2.0.7
  simple_auth_flutter: ^2.0.7
  dio: ^4.0.0
  sprintf: "^4.0.0"
  url_launcher: ^6.0.3
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^9.1.1
  package_info: ^0.4.3
  modal_bottom_sheet: ^2.0.0
  another_flushbar: ^1.10.17
  flutter_svg: ^0.22.0
  webview_flutter: ^1.0.7
  delayed_display: ^1.1.0
  lottie: ^1.0.1
  launch_review: ^3.0.0
  smooth_page_indicator: ^0.2.0
  auto_size_text: ^2.1.0
  flutter_markdown: ^0.6.1
  google_nav_bar: ^5.0.3
  preload_page_view: ^0.1.6
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.2.2
  build_runner: ^2.0.1
```

**Comment by simolus3** [comment]
This looks like a bug in the Dart analyzer. Just to check whether it's fixed in the latest version, can you add this to your pubspec?

```yaml
dependency_overrides:
  analyzer: ^1.5.0
```

Then, try running `flutter pub run build_runner clean` followed by another build. If the exception is still happening, can you open an issue at [dart-lang/sdk](https://github.com/dart-lang/sdk/issues/new)?

**Comment by 0x-cell** [comment]
I'm guessing that this might be the solution: https://github.com/dart-lang/sdk/pull/45823

**Comment by simolus3** [comment]
True, that does look similar. I'll close this issue since it looks like it's not moor's fault :D
