### ISSUE TITLE
reset database without using some truncate

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#122]
is any simple way to reset all of data in database (not selecting tables)? or this feature:

```dart
Future truncateUser(UserTableCompanion user) => truncate(user);
```

**Comment by simolus3** [comment]
You mean deleting all data in a table? This
```dart
await delete(users.go();
```
should do it. We don't expose the `TRUNCATE TABLE` statement in moor (but it wouldn't be much work to add so let me know if you need it).

To delete all data in all tables, you could add this method to your database
```dart
Future resetDb() async {
  for (var table in allTables) {
    await delete(table).go();
  }
}
```

**Comment by MahdiPishguy** [comment]
@simolus3 It's not clear to me, could you help me how can i use that in this database structure?

```dart
class UserTable extends Table{
  IntColumn get id =>integer().autoIncrement()();

  TextColumn get name =>text().nullable()();
  TextColumn get mobileNumber =>text()();
  TextColumn get email =>text().nullable()();
}

@UseMoor(
    tables:[
      UserTable
    ],
    daos: [
      UserTableDao
    ],
    queries: {
    })
class AppDb extends _$AppDb{
  AppDb() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite',logStatements: true));
  @override
  int get schemaVersion => 1;
}

@UseDao(tables:[UserTable])
class UserTableDao extends DatabaseAccessor<AppDb> with _$UserTableDaoMixin{
  final AppDb db;
  UserTableDao(this.db):super(db);

  Future<UserTableData> getSingleUser() {
    return (
        select(userTable)
          ..orderBy([(t) => OrderingTerm(expression: t.id, mode: OrderingMode.desc)])
          ..limit(1)
        ).getSingle();
  }
  Future<int> insertUser(UserTableCompanion user) => into(userTable).insert(user);
  Future updateUser(UserTableCompanion  user) => update(userTable).replace(user);
  Future deleteUser(UserTableCompanion user) => delete(userTable).delete(user);
}
```

**Comment by simolus3** [comment]
If you want to reset all data, you could change your `AppDb` class as follows:
```dart
@UseMoor(...)
class AppDb extends _$AppDb {
  // constructor and schemaVersion getter still need to be here

  Future<void> deleteAllData() {
    return transaction((_) async {
      for (var table in allTables) {
        await delete(table).go();
      }
    });
  }
}
```
Then, calling `deleteAllData` will delete all rows in every table. Is that what you need?

**Comment by MahdiPishguy** [comment]
@simolus3 i get this error:

```dart
Unhandled Exception: DatabaseException(no such table: category_table (Sqlite code 1): , while compiling: DELETE FROM category_table;, (OS error - 2:No such file or directory)) sql 'DELETE FROM category_table;' args []}
`

my database structure:

```dart
import 'package:moor_flutter/moor_flutter.dart';

part 'moor_database.g.dart';

//@formatter:off

class UserTable extends Table{
  IntColumn get id =>integer().autoIncrement()();

  TextColumn get name =>text().nullable()();
  TextColumn get mobileNumber =>text()();
  TextColumn get email =>text().nullable()();
  TextColumn get experience =>text().nullable()();
  TextColumn get insurance =>text().nullable()();
  TextColumn get job =>text().nullable()();
  TextColumn get avatar =>text().nullable()();
  TextColumn get apiToken =>text()();

  IntColumn get userActive =>integer()();
  IntColumn get teammate =>integer().nullable()();
  IntColumn get age =>integer().nullable()();
  IntColumn get gender =>integer().nullable()();
  IntColumn get height =>integer().nullable()();
  IntColumn get weight =>integer().nullable()();
  IntColumn get bmi =>integer().nullable()();

  TextColumn get createdAt =>text()();
  TextColumn get updatedAt =>text()();
}

class TicketsTable extends Table{
  IntColumn  get id=>integer().autoIncrement()();
  TextColumn get subject=>text()();
  TextColumn get description=>text()();

  IntColumn  get ticketNumber =>integer()();
  IntColumn  get section  =>integer()();
  IntColumn  get solved  =>integer()();

  TextColumn get createdAt=>text()();
  TextColumn get updatedAt=>text()();
}

class TicketRepliesTable extends Table{
  IntColumn  get id=>integer().autoIncrement()();
  IntColumn  get ticketId=>integer()();

  TextColumn get reply=>text()();
  TextColumn get createdAt=>text()();
  TextColumn get updatedAt=>text()();
}

class PostsTable extends Table{
  IntColumn get id=>integer().autoIncrement()();
  IntColumn  get postId =>integer()();
  TextColumn get title =>text()();
  TextColumn get description =>text()();
  TextColumn get categoryName =>text()();
  TextColumn get featuredImages =>text()();
  TextColumn get createdAt =>text()();
  TextColumn get updatedAt =>text()();
}

class CategoryTable extends Table{
  IntColumn get id=>integer().autoIncrement()();
  TextColumn get title=>text()();
  IntColumn get parent=>integer().autoIncrement()();
  TextColumn get image=>text()();
}

class MedicineTable extends Table{
    IntColumn get id=>integer().autoIncrement()();
    TextColumn get name=>text()();
    TextColumn get timeSection=>text()();
    DateTimeColumn get unixTime=>dateTime()();
}

@UseMoor(
    tables:[
      UserTable, TicketsTable, TicketRepliesTable, PostsTable, CategoryTable,MedicineTable
    ],
    daos: [
      UserTableDao,
      PostsTableDao
    ],
    queries: {
    })
class AppDb extends _$AppDb{
  AppDb() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite',logStatements: true));

  Future<void> deleteAllData() {
    return transaction((_) async {
      for (var table in allTables) {
        await delete(table).go();
      }
    });
  }

  @override
  int get schemaVersion => 1;
}

@UseDao(tables:[UserTable])
class UserTableDao extends DatabaseAccessor<AppDb> with _$UserTableDaoMixin{
  final AppDb db;
  UserTableDao(this.db):super(db);

  Future<UserTableData> getSingleUser() {
    return (
        select(userTable)
          ..orderBy([(t) => OrderingTerm(expression: t.id, mode: OrderingMode.desc)])
          ..limit(1)
        ).getSingle();
  }
  Future<int> insertUser(UserTableCompanion user) => into(userTable).insert(user);
  Future updateUser(UserTableCompanion  user) => update(userTable).replace(user);
  Future deleteUser(UserTableCompanion user) => delete(userTable).delete(user);
}

@UseDao(tables:[PostsTable])
class PostsTableDao extends DatabaseAccessor<AppDb> with _$PostsTableDaoMixin{
  final AppDb db;
  PostsTableDao(this.db):super(db);

  Future<List<PostsTableData>> get getAllPosts => select(postsTable).get();
  Future<int> insertUser(PostsTableCompanion post) => into(postsTable).insert(post);
  Future updateUser(PostsTableCompanion  post) => update(postsTable).replace(post);
  Future deleteUser(PostsTableCompanion post) => delete(postsTable).delete(post);
}


//@formatter:off
```

**Comment by simolus3** [comment]
Did you already open the database at some point before writing the `CategoryTable` class? Moor creates all tables when the database is created, but if you already had the database open before you need to write that table manually. 

You can do that by writing a schema migration:
```dart
class AppDb extends _$AppDb {
  // inside the AppDb class
  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onUpgrade: (m, from, to) async {
        // create missing tables that were missing in version 1
        if (from <= 1) {
          await m.createTable(categoryTable);
          // you also need this line for every other table not created in the first version
        }
      },
    );
  }
  // rest of the class
}
```

If you're the only one with your app installed, you could also try deleting the app's data on the phone once. If you then re-run the app, moor should create all tables, so you don't need the schema migration.

**Comment by MahdiPishguy** [comment]
@simolus3 

> Did you already open the database at some point before writing the CategoryTable class?

I've had this table before, not created in this time and don't have any data into that, because i don't use that in still

> all tables when the database is created, but if you already had the database open before you need to write that table manually.

i don't create this table now and i had that already with other tables 

you can see in this log:

```
Launching lib\main.dart on WAS LX1A in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/flutter ( 4176): Moor: Sent CREATE TABLE IF NOT EXISTS user_table (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR NULL, mobile_number VARCHAR NOT NULL, email VARCHAR NULL, experience VARCHAR NULL, insurance VARCHAR NULL, job VARCHAR NULL, avatar VARCHAR NULL, api_token VARCHAR NOT NULL, user_active INTEGER NOT NULL, teammate INTEGER NULL, age INTEGER NULL, gender INTEGER NULL, height INTEGER NULL, weight INTEGER NULL, bmi INTEGER NULL, created_at VARCHAR NOT NULL, updated_at VARCHAR NOT NULL); with args []
I/flutter ( 4176): Moor: Sent CREATE TABLE IF NOT EXISTS tickets_table (id INTEGER PRIMARY KEY AUTOINCREMENT, subject VARCHAR NOT NULL, description VARCHAR NOT NULL, ticket_number INTEGER NOT NULL, section INTEGER NOT NULL, solved INTEGER NOT NULL, created_at VARCHAR NOT NULL, updated_at VARCHAR NOT NULL); with args []
I/flutter ( 4176): Moor: Sent CREATE TABLE IF NOT EXISTS ticket_replies_table (id INTEGER PRIMARY KEY AUTOINCREMENT, ticket_id INTEGER NOT NULL, reply VARCHAR NOT NULL, created_at VARCHAR NOT NULL, updated_at VARCHAR NOT NULL); with args []
I/flutter ( 4176): Moor: Sent CREATE TABLE IF NOT EXISTS posts_table (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER NOT NULL, title VARCHAR NOT NULL, description VARCHAR NOT NULL, category_name VARCHAR NOT NULL, featured_images VARCHAR NOT NULL, created_at VARCHAR NOT NULL, updated_at VARCHAR NOT NULL); with args []
I/flutter ( 4176): Moor: Sent CREATE TABLE IF NOT EXISTS category_table (id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR NOT NULL, parent INTEGER PRIMARY KEY AUTOINCREMENT, image VARCHAR NOT NULL); with args []
I/flutter ( 4176): Moor: Sent CREATE TABLE IF NOT EXISTS medicine_table (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR NOT NULL, time_section VARCHAR NOT NULL, unix_time INTEGER NOT NULL); with args []
E/SQLiteLog( 4176): (1) 
E/flutter ( 4176): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DatabaseException(table "category_table" has more than one primary key (Sqlite code 1): , while compiling: CREATE TABLE IF NOT EXISTS category_table (id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR NOT NULL, parent INTEGER PRIMARY KEY AUTOINCREMENT, image VARCHAR NOT NULL);, (OS error - 2:No such file or directory))
E/flutter ( 4176): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 4176): <asynchronous suspension>
E/flutter ( 4176): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
E/flutter ( 4176): #2      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:183:15)
E/flutter ( 4176): #3      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.invokeExecute (package:sqflite/src/database_mixin.dart:328:12)
E/flutter ( 4176): #4      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnExecute.<anonymous closure> (package:sqflite/src/database_mixin.dart:323:14)
E/flutter ( 4176): #5      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite/src/database_mixin.dart:290:22)
E/flutter ( 4176): #6      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
E/flutter ( 4176): <asynchronous suspension>
E/flutter ( 4176): #7      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart:286:43)
E/flutter ( 4176): <asynchronous suspension>
E/flutter ( 4176): #8      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite/src/database_mixin.dart:307:7)
E/flutter ( 4176): #9      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnExecute (package:sqflite/src/database_mixin.dart:313:12)
E/flutter ( 4176): #10     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin&SqfliteDatabaseExecutorMixin.execute (package:sqflite/src/database_mixin.dart:35:15)
E/flutter ( 4176): #11     __SqfliteDelegate&DatabaseDelegate&_SqfliteExecutor.runCustom (package:moor_flutter/moor_flutter.dart:130:15)
E/flutter ( 4176): #12     _DelegatedDatabase&QueryExecutor&_ExecutorWithQueryDelegate.runCustom.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:71:19)
E/flutter ( 4176): #13     _DelegatedDatabase&QueryExecutor&_ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22:26)
E/flutter ( 4176): <asynchronous suspension>
E/flutter ( 4176): #14     _DelegatedDatabase&QueryExecutor&_ExecutorWithQueryDelegate.runCustom (package:moor/src/runtime/executor/helpers/engines.dart:68:12)
E/flutter ( 4176): #15     Migrator.issueCustomQuery (package:moor/src/runtime/migration.dart:156:12)
E/flutter ( 4176): <asynchronous suspension>
E/flutter ( 4176): #16     Migrator.createTable (package:moor/src/runtime/migration.dart:134:12)
E/flutter ( 4176): <asynchronous suspension>
E/flutter ( 4176): #17     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
E/flutter ( 4176): #18     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter ( 4176): #19     Future.wait (dart:async/future.dart:393:26)
E/flutter ( 4176): #20     Migrator.createAllTables (package:moor/src/runtime/migration.dart:70:19)
E/flutter ( 4176): #21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
E/flutter ( 4176): #22     Migrator.createAllTables (package:moor/src/runtime/migration.dart:69:31)
E/flutter ( 4176): #23     _defaultOnCreate (package:moor/src/runtime/migration.dart:22:48)
E/flutter ( 4176): #24     GeneratedDatabase.handleDatabaseCreation (package:moor/src/runtime/database.dart:308:31)
E/flutter ( 4176): #25     DelegatedDatabase._runMigrations (package:moor/src/runtime/executor/helpers/engines.dart:298:26)
E/flutter ( 4176): #26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter ( 4176): #27     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 4176): #28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 4176): #29     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 4176): #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 4176): #31     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 4176): #32     Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter ( 4176): #33     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter ( 4176): #34     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 4176): #35     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 4176): #36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 4176): #37     _CustomZone.bindC
Syncing files to device WAS LX1A...

```

**Comment by MahdiPishguy** [comment]
@simolus3 i think i found whats problem. let me to check

**Comment by MahdiPishguy** [comment]
@simolus3 problem was on my code and database structure, thanks,
solved :)

**Comment by MahdiPishguy** [comment]
@simolus3 

how about single table?

```dart
Future<void> deleteUserData() {
    return transaction((_) async {
      delete(allTables[0]).go();
    });
  }
```

**Comment by simolus3** [comment]
You can just use the table name directly in that case, you don't even need a transaction:
```dart
Future<void> deleteUserData() {
  return delete(userTable).go();
}
```

**Comment by MahdiPishguy** [comment]
@simolus3 my English is not very good. but i like to add this features into documentation

**Comment by simolus3** [comment]
It's a change introduced in the upgrade to moor 2.0. Just remove the `_`, so line two from your snippet would be `return transaction(() async {`. See the "Breaking changes" section from the [changelog](https://pub.dev/packages/moor#-changelog-tab-) for details.
