### ISSUE TITLE
near "ON": syntax error insertAllOnConflictUpdate method

### ISSUE THREAD

**Issue by vaibhiarora03** [simolus3/moor#1319]
I want use `insertAllOnConflictUpdate` method. But upon using this method I am getting error 
```
E/SQLiteLog(32688): (1) near "ON": syntax error
E/flutter (32688): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1 SQLITE_ERROR): , while compiling: INSERT INTO command_groups_table (group_id, make_id, car_company, `group`) VALUES (?, ?, ?, ?) ON CONFLICT(make_id) DO UPDATE SET group_id = ?, make_id = ?, car_company = ?, `group` = ?) sql 'INSERT INTO command_groups_table (group_id, make_id, car_company, `group`) VALUES (?, ?, ?, ?) ON CONFLICT(make_id) DO UPDATE SET group_id = ?, make_id = ?, car_company = ?, `group` = ?' args [6, 6, {"id":6,"name":"BMW"}, {"id":6,"name":"BMW"}, 6, 6, {"id":6,"name":"BMW"}, {"id":6,"name":"BMW"}]}
E/flutter ( 6416): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 6416): <asynchronous suspension>
E/flutter ( 6416): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter ( 6416): #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite_common/src/database_mixin.dart:211:15)
E/flutter ( 6416): #3      SqfliteDatabaseMixin.txnApplyBatch.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:438:17)
E/flutter ( 6416): #4      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:321:26)
E/flutter ( 6416): #5      SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite_common/src/database_mixin.dart:354:7)
E/flutter ( 6416): #6      SqfliteDatabaseMixin.txnApplyBatch (package:sqflite_common/src/database_mixin.dart:428:12)
E/flutter ( 6416): #7      SqfliteTransactionBatch.commit (package:sqflite_common/src/batch.dart:149:33)
E/flutter ( 6416): #8      _SqfliteExecutor.runBatched (package:moor_flutter/moor_flutter.dart:130:17)
E/flutter ( 6416): #9      _ExecutorWithQueryDelegate.runBatched.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:90:19)
E/flutter ( 6416): #10     _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:25:26)
E/flutter ( 6416): #11     _ExecutorWithQueryDelegate.runBatched (package:moor/src/runtime/executor/helpers/engines.dart:86:12)
E/flutter ( 6416): #12     Batch._runWith (package:moor/src/runtime/api/batch.dart:196:10)
E/flutter ( 6416): #13     Batch._commit (package:moor/src/runtime/api/batch.dart:180:15)
E/flutter ( 6416): <asynchronous suspension>
E/flutter ( 6416): #14     QueryEngine.batch (package:moor/src/runtime/api/query_engine.dart:395:20)
E/flutter ( 6416): #15     AppDatabase.insertCommandGroups (package:garage_pro_flutter/Database/moor_database.dart:343:11)
E/flutter ( 6416): #16     _FullScanPickModuleScreenState.fetchCommandGroup (package:garage_pro_flutter/Screens/FullScanPickModule.dart:120:14)
E/flutter ( 6416): <asynchronous suspension>
E/flutter ( 6416): #17     _FullScanPickModuleScreenState.fetchCommandInInit (package:garage_pro_flutter/Screens/FullScanPickModule.dart:62:11)
E/flutter ( 6416): #18     _FullScanPickModuleScreenState.initState (package:garage_pro_flutter/Screens/FullScanPickModule.dart:49:5)
E/flutter ( 6416): #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter ( 6416): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 6416): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6416): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6416): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 6416): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6416): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6416): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6416): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6416): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 6416): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 6416): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6416): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6416): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 6416): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6416): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6416): #35     SingleChildRenderObjectEleme
```

My usage of `insertAllOnConflictUpdate` method is like
```
Future insertCommandGroups(List<CommandGroupTable> commandGroups) async {
    await batch((batch) {
      batch.insertAllOnConflictUpdate(commandGroupsTable, commandGroups);
    });
  }
```

Packages I'm using are 
```
sqlite3_flutter_libs : "0.3.0"
moor_flutter : "3.1.0"
sqflite: "1.3.2+4"
```

Flutter doctor-v details are mentioned below
```
Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 
    • Framework revision 9b2d32b605 (6 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK 
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
```

**Comment by kuhnroyal** [comment]
You need sqlite `3.35.0`+ I believe, you should update `sqlite3_flutter_libs` to at least `0.4.3`.
Not sure how that works together with your old moor version.

**Comment by vaibhiarora03** [comment]
For upgrading `sqlite3_flutter_libs` to `0.4.3` it requires to update dart SDK to `2.12` and currently I am using `2.10.5`.
I also tried upgrading  `sqlite3_flutter_libs` to `0.4.0+1` but still the same issue. 

Also, at the time I started integrating `moor` in my project, official documentation recommended using `moor_flutter` and  when I recently went through the documentation it recommends using `moor/ffi`. 
Is it advisable to migrate to `moor/ffi` or this can be resolved by keeping with `moor_flutter`? I have my `iOS` app in production and `Android` is yet to release.

**Comment by simolus3** [comment]
@vaibhiarora03 `moor_flutter` is based on `sqflite`, which always uses the sqlite3 version that comes with the operating system. Most devices have an older sqlite3 version that does not yet support upserts.

An advantage of `moor/ffi` is that you control the sqlite3 version used, so you can use the latest features on all devices. The documentation describes how to migrate [here](https://moor.simonbinder.eu/docs/other-engines/vm/#migrating-from-moor_flutter-to-moor-ffi). I think it's worth migrating if you want to use recent sqlite features. The only downside of `moor/ffi` that I'm aware of is that it's synchronous. So expensive queries might cause UI lag. If this turns out to be a problem for you, you can make moor [run on a background isolate](https://moor.simonbinder.eu/docs/advanced-features/isolates/).

I don't think there's a prebuilt way to use `sqflite` (and thus, `moor_flutter`) with the sqlite3 version from `sqlite3_flutter_libs`. It should be possible in theory by changing the Java/ObjC code accessing sqlite3 in the plugin implementation. But I'm not aware of anyone actually doing that.
