### ISSUE TITLE
[develop] "Bad state: No element" in moor_generator:moor_generator

### ISSUE THREAD

**Issue by North101** [simolus3/moor#1346]
`flutter pub run build_runner build --delete-conflicting-outputs --verbose`
```
[ +112 ms] executing: sysctl hw.optional.arm64
[  +26 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[  +13 ms] executing: [/usr/local/Caskroom/flutter/2.2.2/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d79295af24c3ed621c33713ecda14ad196fd9c31
[   +2 ms] executing: [/usr/local/Caskroom/flutter/2.2.2/flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[  +29 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] 2.2.2
[  +14 ms] executing: [/usr/local/Caskroom/flutter/2.2.2/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/Caskroom/flutter/2.2.2/flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +156 ms] executing: [/usr/local/Caskroom/flutter/2.2.2/flutter/] git rev-parse --abbrev-ref HEAD
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +12 ms] executing: sw_vers -productName
[  +35 ms] Exit code 0 from: sw_vers -productName
[   +2 ms] macOS
[        ] executing: sw_vers -productVersion
[  +27 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.4
[   +1 ms] executing: sw_vers -buildVersion
[  +26 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20F71
[ +102 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +51 ms] Using /usr/local/Caskroom/flutter/2.2.2/flutter/.pub-cache for the pub cache.
[   +3 ms] executing: /usr/local/Caskroom/flutter/2.2.2/flutter/bin/cache/dart-sdk/bin/pub run build_runner build --delete-conflicting-outputs
--verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 757ms

[INFO] BuildDefinition:Initializing inputs
[INFO] flutter_gen_runner:flutter_gen_runner:FlutterGen Loading ... pubspec.yaml
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] flutter_gen_runner:flutter_gen_runner:Generated: /Users/alexander/git/netdeck/lib/util/assets.gen.dart
[INFO] flutter_gen_runner:flutter_gen_runner:FlutterGen finished.
[INFO] BuildDefinition:Reading cached asset graph completed, took 483ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 1.8s

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 40ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 140ms

[SEVERE] moor_generator:moor_generator on lib/db/database.dart (cached):

Bad state: No element
dart:collection                                                                 ListMixin.firstWhere
package:moor_generator/src/analyzer/moor/create_table_reader.dart 265:57        CreateTableReader._readTypeConverter
package:moor_generator/src/analyzer/moor/create_table_reader.dart 120:23        CreateTableReader.extractTable
package:moor_generator/src/analyzer/moor/parser.dart 71:25                      MoorParser.parseAndAnalyze
package:moor_generator/src/analyzer/runner/task.dart 85:20                      Task._parse
package:moor_generator/src/analyzer/runner/task.dart 42:20                      Task.runTask
package:moor_generator/src/backends/build/moor_builder.dart 37:7                MoorBuilder.analyzeDartFile
package:moor_generator/src/backends/build/generators/moor_generator.dart 28:20  MoorGenerator.generate
package:source_gen/src/builder.dart 328:23                                      _generate

[SEVERE] Build:
Failed after 236ms
[+6719 ms] "flutter run" took 6,934ms.
[  +10 ms] pub finished with exit code 1
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:368:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +130 ms] ensureAnalyticsSent: 113ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by North101** [comment]
Doesn't happen on stable

**Comment by simolus3** [comment]
It looks like this might happen when a class is used as a type converter without extending from `TypeConverter`. It's definitely weird that this doesn't happen with the stable version.

**Comment by North101** [comment]
I just went to debug it and... the error stopped happening? No idea why
