### ISSUE TITLE
Drift 1.1.0 - Isolate Serialization

### ISSUE THREAD

**Issue by laurensfischer** [simolus3/moor#1593]
Hey, 
thanks for your awesome library!

We just migrated from moor to drift, but our isolate setup doesn't work with the newest version.
It runs fine from the main thread, but when we try to access the database from our android workmanager thread, we get the following exception.

<details>
  <summary>Exception</summary>
  
```
E/flutter (30424): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
E/flutter (30424): #0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:249:43)
E/flutter (30424): #1      _SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:230:5)
E/flutter (30424): #2      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (30424): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (30424): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (30424): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (30424): #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (30424): #7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (30424): #8      _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (30424): #9      _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (30424): #10     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (30424): #11     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (30424): #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (30424): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (30424): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (30424): #15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (30424): #16     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (30424): #17     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (30424): #18     _StreamSinkWrapper.add (dart:async/stream_controller.dart:826:13)
E/flutter (30424): #19     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
E/flutter (30424): #20     DriftCommunication._send (package:drift/src/remote/communication.dart:117:19)
E/flutter (30424): #21     DriftCommunication.request (package:drift/src/remote/communication.dart:103:5)
E/flutter (30424): #22     _RemoteQueryExecutor.ensureOpen (package:drift/src/remote/client_impl.dart:133:10)
E/flutter (30424): #23     DatabaseConnectionUser.doWhenOpened (package:drift/src/runtime/api/connection_user.dart:154:21)
E/flutter (30424): #24     DatabaseConnectionUser.customStatement (package:drift/src/runtime/api/connection_user.dart:381:19)
E/flutter (30424): #25     setTmpDirForAndroid (package:x_code_manager/gears/services/database_provider.dart:83:12)
E/flutter (30424): <asynchronous suspension>
```
</details>

This doesn't happen when using v1.0.1, do we maybe have to adjust our database setup?

<details>
  <summary>Database setup</summary>
  
```
  Future<AppDatabase> database(String customerId) async {
    final receivePort = ReceivePort();

    final existingIsolate = IsolateNameServer.lookupPortByName(customerId);
    DriftIsolate? isolate;
    if (existingIsolate == null) {
      await Isolate.spawn(
        _startBackground,
        _IsolateStartRequest(
          receivePort.sendPort,
          _dirs.dataDir.file("$customerId.sqlite").path,
        ),
      );
      isolate = await receivePort.first as DriftIsolate?;
      if (isolate != null) {
        IsolateNameServer.registerPortWithName(isolate.connectPort, customerId);
      }
    } else {
      isolate = DriftIsolate.fromConnectPort(existingIsolate);
    }

    final connection = await isolate!.connect();

    final db = AppDatabase.connect(connection);

    setTmpDirForAndroid(db);
    return db;
  }
}

void _startBackground(_IsolateStartRequest request) {
  final executor = NativeDatabase(
    File(request.targetPath),
    setup: (database) {
      //some custom functions ...
    },
  );
  final moorIsolate = DriftIsolate.inCurrent(
    () => DatabaseConnection.fromExecutor(executor),
  );
  request.sendMoorIsolate.send(moorIsolate);
}
```

</details>

Thank you for any advice!

**Comment by frankvollebregt** [comment]
I am having roughly the same issue, though your setup seems a bit clearer. I created a discussion thread on it earlier today, so you might want to keep an eye on that one as well, depending on where the questions are answered
[link to the discussion](https://github.com/simolus3/moor/discussions/1590)

**Comment by kuhnroyal** [comment]
```dart
  final moorIsolate = DriftIsolate.inCurrent(
    () => DatabaseConnection.fromExecutor(executor),
  );
  request.sendMoorIsolate.send(moorIsolate);
```

This seems wrong, you are not supposed to send the whole `DriftIsolate`, only the `moorIsolate.connectPort`. And the construct it with `DriftIsolate.fromConnectPort`.

**Comment by simolus3** [comment]
Peter is right about only sending the connect port instead of the full `DriftIsolate` object, but there is a regression introduced in Drift 1.1.0. After reading about isolate groups being enabled by default, I assumed that we could now send almost every Dart object without custom serialization. As this serialization has a cost, I've raised the SDK constraint to 2.15.0 and then turned it off in Drift 1.1.0. As it now turns out, this was a poor choice since isolates managed by the `workmanager` package are in different groups and can therefore only send simple objects.

In af1a8b5f8107cd5ad331cb62e95405efb8ba93f9, I've added a parameter controlling whether this explicit serialization should happen or not. It defaults to the pre-1.1.0 behavior for backwards compatibility, but can be turned off when all isolates are managed by the same Flutter engine for a performance gain. I'm aiming to release this and other fixes tomorrow.

**Comment by simolus3** [comment]
Reading up on the discussion in #1590, it looks like some messages go through and others don't. If this turns out to be the case all the time, I should probably look into why some messages are failing and continue to keep the serialization off by default.

@laurensfischer Could you enable `debugLog: true` in the call to `DriftIsolate.connect` and see if there are some messages being logged before the crash?

@frankvollebregt Did you use "regular" isolates (spawned with `Isolate.spawn` instead of a Flutter plugin potentially setting up new engines) when you ran into your issue? If so, I'll try to reproduce this with a somewhat vanilla + isolate approach and see where it goes wrong.

**Comment by frankvollebregt** [comment]
Thanks for looking into this so quickly. I use the `flutter_isolate` plugin to spawn isolates, from which I try to connect to the `DriftIsolate`, so I'm not sure about separate engines. I'll verify this for you (whether it's the same in all cases for me) tomorrow (hopefully in the morning)

**Comment by frankvollebregt** [comment]
Hi! I just managed to recreate a small example project showcasing my use case, which indeed reproduces the error. You might be able to use it as a starting point to debug the issue.

https://github.com/frankvollebregt/drift_isolate_test

**Comment by laurensfischer** [comment]
Hey @simolus3 , didn't expect such a fast answer, thanks! 
This is the only message I get from the background flutter engine (ignoring all successful logs from the main thread) before the exception occurs:
`I/flutter ( 9228): [OUT]: Request (id = 0): EnsureOpen(3, null)`

And thanks for your suggestion @kuhnroyal , changed it to the connectPort. What exactly is the difference between sending the isolate and only sending the connectPort? Only slightly less data?

**Comment by kuhnroyal** [comment]
> And thanks for your suggestion @kuhnroyal , changed it to the connectPort. What exactly is the difference between sending the isolate and only sending the connectPort? Only slightly less data?

It is not about the data, it is about what can be serialized and passed as a message to another isolate. Read the `SendPort.send` docs for more info.

**Comment by kuhnroyal** [comment]
@simolus3 Could we have a `DriftIsolate` that can handle both serialized and direct messages at the same time?
It does depend on the client isolate what form of communication is required so theoretically a client could connect and tell the `DriftIsolate` how it wants to communicate.
I have a couple isolates started from the same engine group which could benefit from direct messages while I also have some background isolates which (currently) are not in the same engine group.

**Comment by kuhnroyal** [comment]
@simolus3 I created a PR that allows clients with different serialization configuration to connect to the same server.
I think that if the min SDK stays at 2.15 then we can safely default to `serialize = true` for `spawn` and `inCurrent` as those are always in the same engine group.
Only `fromConnectPort` needs to defaults to `false`.

**Comment by simolus3** [comment]
Neat! I think this should address the problems (I tested it on @frankvollebregt's helpful repro where it fixes the problem while also avoiding unnecessary serialization between the main isolates).
