### ISSUE TITLE
leftouterjoin issue

### ISSUE THREAD

**Issue by aidooyaw1992** [simolus3/moor#160]
hi please, i keep getting this error and i dont know why.
im doing left join on three tables. it works the first time but i keep getting this error later
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'writeInto' was called on null.
E/flutter ( 4284): Receiver: null
E/flutter ( 4284): Tried calling: writeInto(Instance of 'GenerationContext')
E/flutter ( 4284): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 4284): #1      InfixOperator.writeInto (package:moor/src/runtime/expressions/expression.dart:48:11)
E/flutter ( 4284): #2      Join.writeInto (package:moor/src/runtime/components/join.dart:29:10)
E/flutter ( 4284): #3      JoinedSelectStatement.writeStartPart (package:moor/src/runtime/statements/select.dart:68:19)
E/flutter ( 4284): #4      Query.constructQuery (package:moor/src/runtime/statements/query.dart:38:5)
E/flutter ( 4284): #5      JoinedSelectStatement.get (package:moor/src/runtime/statements/select.dart:115:17)     
E/flutter ( 4284): <asynchronous suspension>
E/flutter ( 4284): #6      CustomerAccountsDao.getAccountsWithMetersAndMeterReadings (package:ereader/db/database.dart:97:8)
E/flutter ( 4284): <asynchronous suspension>
E/flutter ( 4284): #7      AppLogic.loadAccounts (package:ereader/app_logic/app_logic.dart:290:48)
E/flutter ( 4284): <asynchronous suspension>
E/flutter ( 4284): #8      _CustomersPageState.initState (package:ereader/pages/customers/customers_page.dart:22:15)
E/flutter ( 4284): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)       
E/flutter ( 4284): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 4284): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4284): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4284): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4284): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4284): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4284): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)   
E/flutter ( 4284): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 4284): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 4284): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 4284): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4284): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4284): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4284): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4284): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4284): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4284): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4284): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4284): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4284): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4284): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4284): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 4284): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4284): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4284): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 4284): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 4284): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 4284): #37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter ( 4284): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 4284): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 4284): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 4284): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 4284): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 4284): #43     ComponentElement._firstBuild (package:flutter/src/widgets/f
```

 moor_flutter: ^1.7.0
flutter channel beta

**Comment by simolus3** [comment]
This looks like a bug in moor, thanks for the report. Can you give me the code you use for the query (the `select(...).join(...)` part)? I can then take a look to see where it's going wrong.

**Comment by aidooyaw1992** [comment]
It was a left join on between 3 tables

**Comment by simolus3** [comment]
Sorry, I think I need the full Dart query code. It seems like some part in that query is null while it shouldn't be. If I have your code, I can take a detailed look at how that could happen and how moor can prevent it. So if you could send the code of `CustomerAccountsDao.getAccountsWithMetersAndMeterReadings`, it would very much help me. If you're uncomfortable sharing that code publicly, you can email it to me via oss@simonbinder.eu.

**Comment by aidooyaw1992** [comment]
Future<List<AccountWithMeterAndMeterReading>>getAccountsWithMetersAndMeterReadings() async{
    final rows = await select(customerAccounts).join([
      leftOuterJoin(
        meterReadings,
        meterReadings.customerAccountId.equalsExp(customerAccounts._customerAccountId)
      ),
      leftOuterJoin(
        meters,
        meters.id.equalsExp(customerAccounts.meterId)
      )
    ]).get();

    return rows.map((resultRow){
      return AccountWithMeterAndMeterReading(
        account: resultRow.readTable(customerAccounts),
        meter: resultRow.readTable(meters),
        meterReading: resultRow.readTable(meterReadings)
      );
    }).toList();
  }

**Comment by simolus3** [comment]
I couldn't see anything wrong with your code, thanks for providing the details. It looks like, for some reason, either `customerAccounts._customerAccountId` or `customerAccounts.meterId` is null.

Just to be sure: Did you declare `IntColumn get _customerAccountId => ...` in your table (notice the leading underscore)? If not, please try using `meterReadings.customerAccountId.equalsExp(customerAccounts.customerAccountId)` (I removed the underscore) for the join.

**Comment by aidooyaw1992** [comment]
oh wow, thank you very much, there was an underscore there. Ive removed and its working perfectly. thanks

**Comment by simolus3** [comment]
Great!

**Comment by aidooyaw1992** [comment]
> 
> 
> Thanks for providing the details. It looks like, for some reason, either `customerAccounts._customerAccountId` or `customerAccounts.meterId` is null.
> 
> Just to be sure: Did you declare `IntColumn get _customerAccountId => ...` in your table (notice the leading underscore)? If not, please try using `meterReadings.customerAccountId.equalsExp(customerAccounts.customerAccountId)` (I removed the underscore) for the join.

hi, please `customerAccounts.meterId` is null but its not all that is null so i  dont understand why is not working

**Comment by simolus3** [comment]
That's weird, generated columns should never be null. But I think I need more information to take a look at what's going wrong. If `customAccounts.meterId` returns null, can you post the generated source code for `meterId`?

**Comment by aidooyaw1992** [comment]
Sorry everything is working  now. I made a mistake
