### ISSUE TITLE
Stack trace lost in single_transformer.dart

### ISSUE THREAD

**Issue by yehorh** [simolus3/moor#1607]
> % dart --version                          
> Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"

https://github.com/simolus3/moor/blob/70e83b5a747cb6bf9bf360d6de78e8398d3b6873/drift/lib/src/utils/single_transformer.dart#L26-L29

current implementation
```dart
import 'dart:async';

Future<void> main() async {
  var stream = countStream(10).transform(StreamTransformer.fromHandlers(
    handleData: (data, sink) {
      try {
        if (data == 9) throw '123';
        sink.add(data);
      } catch (e) {
        sink.addError(StateError('custom error'));
      }
    },
  ));
  stream.forEach((element) {
    print(element);
  });
}

Stream<int> countStream(int to) async* {
  for (int i = 1; i <= to; i++) {
    yield i;
  }
}

class StateError extends Error {
  final String message;

  StateError(this.message);
}
```
output
```
1
2
3
4
5
6
7
8
Unhandled exception:
Instance of 'StateError'

Process finished with exit code 255
```

implementation with `handleError`
```dart
import 'dart:async';

Future<void> main() async {
  var stream = countStream(10).transform(StreamTransformer.fromHandlers(
    handleData: (data, sink) {
      if (data == 9) throw '123';
      sink.add(data);
    },
    handleError: (error, stackTrace, sink) {
      sink.addError(error);
    },
  ));
  stream.forEach((element) {
    print(element);
  });
}

Stream<int> countStream(int to) async* {
  for (int i = 1; i <= to; i++) {
    yield i;
  }
}

class StateError extends Error {
  final String message;

  StateError(this.message);
}
```

output
```
1
2
3
4
5
6
7
8
Unhandled exception:
123
#0      main.<anonymous closure> (file:///path_to_src/bin/async_errors.dart:6:22)
#1      _HandlerEventSink.add (dart:async/stream_transformers.dart:209:17)
#2      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)

Process finished with exit code 255
```

**Comment by simolus3** [comment]
I'm not sure if the stack trace is particularly helpful here (it's an async stream, you're always going to get a mostly unhelpful trace starting at `_microtaskLoop`), but I've changed the implementation to throw an error with a trace in bce13f150fcddc64288f24d16c301415c6129baf.
