### ISSUE TITLE
Provide createdAt/updatedAt fields

### ISSUE THREAD

**Issue by ddxl123** [simolus3/moor#1652]
Provide createdAt/updatedAt fields.
Automatically write createdAt when a row is created, 
and update updatedAt when a row is updated.

**Comment by simolus3** [comment]
This would have to be stored in the database, and I don't believe that drift should add those columns by default.

You can easily add those fields to your table with a mixin:

```dart
mixin WithModificationTimestamps on Table {
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
}
```

Then, you just have to use `extends Table with WithModificationTimestamps` on your table definitions to get the fields. `createdAt` should already be working with that, for `updatedAt` you'll also need to define triggers:

```dart
  MigrationStrategy get migration {
    return MigrationStrategy(onCreate: (m) async {
      await m.createAll();

      for (final table in allTables) {
        if (table is WithModifiedTimestamps) {
          final name = table.entityName;

          await customStatement('''
            CREATE TRIGGER updated_at_$name AFTER UPDATE ON $name
            BEGIN
              UPDATE $name SET updated_at = CURRENT_TIMESTAMP;
            END;
          ''');
        }
      }
    });
  }
```

**Comment by ddxl123** [comment]
@simolus3 

As written, this error occurred.

```
I/flutter ( 5841): [2022-04-16 06:07:35.865708 | Catcher | INFO] ---------- ERROR ----------
I/flutter ( 5841): [2022-04-16 06:07:35.866445 | Catcher | INFO] type 'String' is not a subtype of type 'int' in type cast
I/flutter ( 5841): [2022-04-16 06:07:35.866673 | Catcher | INFO] 
I/flutter ( 5841): [2022-04-16 06:07:35.869378 | Catcher | INFO] ------- STACK TRACE -------
I/flutter ( 5841): [2022-04-16 06:07:35.870450 | Catcher | INFO] #0      DateTimeType.mapFromDatabaseResponse (package:drift/src/runtime/types/sql_types.dart:138:34)
I/flutter ( 5841): [2022-04-16 06:07:35.871108 | Catcher | INFO] #1      DriftDbViewerDatabase.remapData.<anonymous closure>.<anonymous closure> (package:drift_db_viewer/src/model/db/drift_db_viewer_database.dart:49:41)
I/flutter ( 5841): [2022-04-16 06:07:35.871356 | Catcher | INFO] #2      Iterable.forEach (dart:core/iterable.dart:325:35)
I/flutter ( 5841): [2022-04-16 06:07:35.871584 | Catcher | INFO] #3      DriftDbViewerDatabase.remapData.<anonymous closure> (package:drift_db_viewer/src/model/db/drift_db_viewer_database.dart:43:17)
I/flutter ( 5841): [2022-04-16 06:07:35.871876 | Catcher | INFO] #4      List.forEach (dart:core-patch/growable_array.dart:433:8)
I/flutter ( 5841): [2022-04-16 06:07:35.872029 | Catcher | INFO] #5      DriftDbViewerDatabase.remapData (package:drift_db_viewer/src/model/db/drift_db_viewer_database.dart:41:10)
I/flutter ( 5841): [2022-04-16 06:07:35.872156 | Catcher | INFO] #6      TableContentListViewerViewModel._getData.<anonymous closure> (package:db_viewer/src/viewmodel/table_content_list_viewer_viewmodel.dart:64:33)
I/flutter ( 5841): [2022-04-16 06:07:35.872302 | Catcher | INFO] #7      _rootRunUnary (dart:async/zone.dart:1434:47)
I/flutter ( 5841): [2022-04-16 06:07:35.872449 | Catcher | INFO] #8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter ( 5841): [2022-04-16 06:07:35.872577 | Catcher | INFO] #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
I/flutter ( 5841): [2022-04-16 06:07:35.873067 | Catcher | INFO] #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
I/flutter ( 5841): [2022-04-16 06:07:35.873423 | Catcher | INFO] #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
I/flutter ( 5841): [2022-04-16 06:07:35.874379 | Catcher | INFO] #12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
I/flutter ( 5841): [2022-04-16 06:07:35.874604 | Catcher | INFO] #13     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
I/flutter ( 5841): [2022-04-16 06:07:35.874842 | Catcher | INFO] #14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
I/flutter ( 5841): [2022-04-16 06:07:35.875494 | Catcher | INFO] #15     _rootRunUnary (dart:async/zone.dart:1434:47)
I/flutter ( 5841): [2022-04-16 06:07:35.875677 | Catcher | INFO] #16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter ( 5841): [2022-04-16 06:07:35.876044 | Catcher | INFO] #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
I/flutter ( 5841): [2022-04-16 06:07:35.876364 | Catcher | INFO] #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
I/flutter ( 5841): [2022-04-16 06:07:35.876500 | Catcher | INFO] #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
I/flutter ( 5841): [2022-04-16 06:07:35.876620 | Catcher | INFO] #20     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
I/flutter ( 5841): [2022-04-16 06:07:35.877014 | Catcher | INFO] #21     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
I/flutter ( 5841): [2022-04-16 06:07:35.877250 | Catcher | INFO] #22     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
I/flutter ( 5841): [2022-04-16 06:07:35.877499 | Catcher | INFO] #23     _rootRunUnary (dart:async/zone.dart:1434:47)
I/flutter ( 5841): [2022-04-16 06:07:35.878332 | Catcher | INFO] #24     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter ( 5841): [2022-04-16 06:07:35.878485 | Catcher | INFO] #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
I/flutter ( 5841): [2022-04-16 06:07:35.878622 | Catcher | INFO] #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
I/flutter ( 5841): [2022-04-16 06:07:35.878841 | Catcher | INFO] #27     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
I/flutter ( 5841): [2022-04-16 06:07:35.879883 | Catcher | INFO] #28     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
I/flutter ( 5841): [2022-04-16 06:07:35.880260 | Catcher | INFO] #29     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
I/flutter ( 5841): [2022-04-16 06:07:35.880634 | Catcher | INFO] #30     _rootRun (dart:async/zone.dart:1418:47)
I/flutter ( 5841): [2022-04-16 06:07:35.880828 | Catcher | INFO] #31     _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter ( 5841): [2022-04-16 06:07:35.881175 | Catcher | INFO] #32     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
I/flutter ( 5841): [2022-04-16 06:07:35.881311 | Catcher | INFO] #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
I/flutter ( 5841): [2022-04-16 06:07:35.881537 | Catcher | INFO] #34     _rootRun (dart:async/zone.dart:1426:13)
I/flutter ( 5841): [2022-04-16 06:07:35.881949 | Catcher | INFO] #35     _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter ( 5841): [2022-04-16 06:07:35.882338 | Catcher | INFO] #36     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
I/flutter ( 5841): [2022-04-16 06:07:35.882613 | Catcher | INFO] #37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
I/flutter ( 5841): [2022-04-16 06:07:35.883374 | Catcher | INFO] #38     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
I/flutter ( 5841): [2022-04-16 06:07:35.883946 | Catcher | INFO] #39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
I/flutter ( 5841): [2022-04-16 06:07:35.884793 | Catcher | INFO] 
I/flutter ( 5841): [2022-04-16 06:07:35.885957 | Catcher | INFO] ------- CUSTOM INFO -------
I/flutter ( 5841): [2022-04-16 06:07:35.887529 | Catcher | INFO] 回滚嵌套标签: []
I/flutter ( 5841): [2022-04-16 06:07:35.887761 | Catcher | INFO] ======================================================================
I/flutter ( 5841): [2022-04-16 06:07:35.890874 | Catcher | INFO] Report result: true

```

**Comment by simolus3** [comment]
Following up on this: Especially when using `validateDatabaseSchema()`, it is better to include the trigger in `allSchemaEntities` instead of creating it manually:

```dart
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities {
    final result = super.allSchemaEntities;

    for (final table in result.whereType<TableInfo>().toList()) {
      if (table is WithModifiedTimestamps) {
        final name = table.entityName;
        final triggerName = 'updated_at_$name';

        result.add(
          Trigger(
            '''
            CREATE TRIGGER $triggerName AFTER UPDATE ON $name BEGIN
              UPDATE $name SET updated_at = CURRENT_TIMESTAMP;
            END;
          ''',
            triggerName,
          ),
        );
      }
    }

    return result;
  }
``` 

With this override, the custom `onCreate` strategy can be removed.

**Comment by darkomenx** [comment]
Why this very good explain is not in your documentation ? 

Thank you for your advice. I confirm that It works like a charm in my part.
