### ISSUE TITLE
Migration Deleting Column and Index

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#1709]
I use an old version, `moor: 4.4.0` with `encrypted_moor`. I can't upgrade it easily since I forked it to add a functionality

I encounter a problem removing a Column with an Index.

The INDEX was in a `.moor` file:
`CREATE INDEX survey_questions_survey_id ON survey_questions(survey_id);`
and I deleted it.

Then, I removed the column in the table declaration and bumped the `schemaVersion`.
`await m.alterTable(TableMigration(surveyQuestions));`

Then Clean and Build everything again.

Error:
```
Moor: Sent PRAGMA foreign_keys with args []
I/flutter (14585): Moor: Sent BEGIN TRANSACTION with args []
I/flutter (14585): Moor: Sent SELECT type, name, sql FROM sqlite_master WHERE tbl_name = ?; with args [survey_questions]
I/flutter (14585): Moor: Sent CREATE TABLE IF NOT EXISTS tmp_for_copy_survey_questions (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, package_uid TEXT NULL DEFAULT NULL, survey_uid TEXT NOT NULL, question_uid TEXT NOT NULL, rank INTEGER NOT NULL DEFAULT 0); with args []
I/flutter (14585): Moor: Sent INSERT INTO tmp_for_copy_survey_questions (id, package_uid, survey_uid, question_uid, rank) SELECT id, package_uid, survey_uid, question_uid, rank FROM survey_questions; with args []
I/flutter (14585): Moor: Sent DROP TABLE survey_questions with args []
I/flutter (14585): Moor: Sent ALTER TABLE tmp_for_copy_survey_questions RENAME TO survey_questions with args []
I/flutter (14585): Moor: Sent CREATE INDEX survey_questions_survey_id ON survey_questions(survey_id) with args []
I/flutter (14585): Moor: Sent ROLLBACK TRANSACTION with args []
E/flutter (14585): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SqliteException(1): no such column: survey_id
E/flutter (14585):   Causing statement: CREATE INDEX survey_questions_survey_id ON survey_questions(survey_id)
E/flutter (14585): #0      DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:129:9)
E/flutter (14585): #1      _VmDelegate._runWithArgs (package:moor/src/ffi/vm_database.dart:199:11)
E/flutter (14585): #2      _VmDelegate.runCustom (package:moor/src/ffi/vm_database.dart:209:11)
E/flutter (14585): #3      _ExecutorWithQueryDelegate.runCustom.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:85:19)
E/flutter (14585): #4      _ExecutorWithQueryDelegate._synchronized.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:27:22)
E/flutter (14585): #5      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:27)
E/flutter (14585): #6      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:16:35)
E/flutter (14585): #7      Lock.synchronized.<anonymous closure> (package:moor/src/utils/synchronized.dart:25:35)
E/flutter (14585): #8      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (14585): #9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #10     Migrator.alterTable.<anonymous closure> (package:moor/src/runtime/query_builder/migration.dart:221:9)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #11     DatabaseConnectionUser.transaction.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/api/connection_user.dart:397:26)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #12     DatabaseConnectionUser.transaction (package:moor/src/runtime/api/connection_user.dart:390:12)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #13     Migrator.alterTable (package:moor/src/runtime/query_builder/migration.dart:136:5)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #14     MyDatabase.migration.<anonymous closure> (package:myapp/db/db_classes.dart:3168:10)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #15     GeneratedDatabase.beforeOpen.<anonymous closure> (package:moor/src/runtime/api/db_base.dart:117:9)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #16     DelegatedDatabase._runMigrations (package:moor/src/runtime/executor/helpers/engines.dart:300:5)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #17     DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:267:7)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #18     Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:16)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #19     RunningController.checkFinishedRunning.<anonymous closure> (package:myapp/module/RunningController.dart:272:28)
E/flutter (14585): <asynchronous suspension>
E/flutter (14585): #20     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart)
E/flutter (14585): <asynchronous suspension>
```

I know the version is old, is it a bug, or am I missing something?

**Comment by apoleo88** [comment]
I solved adding in the migration

`await m.drop(Index('survey_questions_survey_id', ''));`

it is the correct way?

**Comment by simolus3** [comment]
Yes, you should `drop` elements that you no longer use in your schema to avoid this class of problems. The snippet you posted looks like a good way to do just that.
