### ISSUE TITLE
Cannot perform this operation because there is no current transaction

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#182]
after some opening and closing application i had get this error:

```
I/flutter (19275): error DatabaseException(Cannot perform this operation because there is no current transaction.) sql 'COMMIT' args []} during open, closing...
I/SQLiteConnectionPool(19275): The connection pool for /data/user/0/ir.instacheeta.instacheeta/databases/cheetah.sqlite has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.

I/flutter (19275): error DatabaseException(database_closed 1) during open, closing...
I/flutter (19275): error DatabaseException(database_closed 1) closing database 1
E/SQLiteLog(19275): (5) 
E/SQLiteDatabase(19275): Failed to open database '/data/user/0/ir.instacheeta.instacheeta/databases/cheetah.sqlite'.

E/SQLiteDatabase(19275): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5): , while compiling: PRAGMA journal_mode, (OS error - 2:No such file or directory)

E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:925)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:670)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:356)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:330)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:229)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:511)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:194)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:864)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:767)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:742)
E/SQLiteDatabase(19275): 	at com.tekartik.sqflite.Database.open(Database.java:26)
E/SQLiteDatabase(19275): 	at com.tekartik.sqflite.SqflitePlugin$6.run(SqflitePlugin.java:772)
E/SQLiteDatabase(19275): 	at android.os.Handler.handleCallback(Handler.java:808)
E/SQLiteDatabase(19275): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/SQLiteDatabase(19275): 	at android.os.Looper.loop(Looper.java:166)
E/SQLiteDatabase(19275): 	at android.os.HandlerThread.run(HandlerThread.java:65)


I/OMXClient(19275): Treble IOmx obtained
I/ACodec  (19275): In onAllocateComponent create compenent, codec name: OMX.IMG.MSVDX.Decoder.AVC
D/SurfaceUtils(19275): connecting to surface 0x7e109e8010, reason connectToSurface
I/MediaCodec(19275): [OMX.IMG.MSVDX.Decoder.AVC] setting surface generation to 19737610
D/SurfaceUtils(19275): disconnecting from surface 0x7e109e8010, reason connectToSurface(reconnect)


D/SurfaceUtils(19275): connecting to surface 0x7e109e8010, reason connectToSurface(reconnect)
W/HwExtendedUtils(19275): hw configLocalPlayBack err = -1010
E/ACodec  (19275): [OMX.IMG.MSVDX.Decoder.AVC] setPortMode on output to DynamicANWBuffer failed w/ err -1010
W/ACodec  (19275): [OMX.IMG.MSVDX.Decoder.AVC] prepareForAdaptivePlayback failed w/ err -1010


I/HwExtendedCodec(19275): mime is [video/avc] at setVideoFormat
I/ACodec  (19275): codec does not support config priority (err -1010)
I/ACodec  (19275): onStart
I/HwExtendedUtils(19275): error setConfig queuesToNativeWindow (err -1010)
D/SurfaceUtils(19275): disconnecting from surface 0x7e109e8010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(19275): connecting to surface 0x7e109e8010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(19275): set up nativeWindow 0x7e109e8010 for 640x640, color 0x300, rotation 0, usage 0x20002900
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000


I/OMXClient(19275): Treble IOmx obtained
I/ACodec  (19275): In onAllocateComponent create compenent, codec name: OMX.google.aac.decoder
W/HwExtendedUtils(19275): hw configLocalPlayBack err = -2147483648
I/HwExtendedUtils(19275): error setConfig queuesToNativeWindow (err -1010)
I/ACodec  (19275): codec does not support config priority (err -2147483648)
D/SurfaceUtils(19275): disconnecting from surface 0x7e109e8010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(19275): connecting to surface 0x7e109e8010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(19275): set up nativeWindow 0x7e109e8010 for 640x640, color 0x300, rotation 0, usage 0x20002900


I/ACodec  (19275): onStart
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(19275): buffer descriptor with invalid usage bits 0x2000
D/AudioTrack(19275): OFFLOAD 0,mNotificationFrames 0,mStreamType 

=-1,mOriginalSampleRate 44100,mAfSampleRate 48000,mTransfer 3
D/AudioTrack(19275): Client defaulted notificationFrames to 3675 for frameCount 11025
I/AudioTrack(19275): audioTrack continuously zero data counter >= 20, send pause/stop state to pg, counter: 20


E/SQLiteLog(19275): (5) 
E/SQLiteDatabase(19275): Failed to open database '/data/user/0/ir.instacheeta.instacheeta/databases/cheetah.sqlite'.
E/SQLiteDatabase(19275): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5): , while compiling: PRAGMA journal_mode, (OS error - 2:No such file or directory)


E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:925)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:670)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:356)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:330)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:229)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:511)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:194)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:864)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:767)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:742)
E/SQLiteDatabase(19275): 	at com.tekartik.sqflite.Database.open(Database.java:26)
E/SQLiteDatabase(19275): 	at com.tekartik.sqflite.SqflitePlugin$6.run(SqflitePlugin.java:772)
E/SQLiteDatabase(19275): 	at android.os.Handler.handleCallback(Handler.java:808)
E/SQLiteDatabase(19275): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/SQLiteDatabase(19275): 	at android.os.Looper.loop(Looper.java:166)
E/SQLiteDatabase(19275): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/SQLiteLog(19275): (5) 
E/SQLiteDatabase(19275): Failed to open database '/data/user/0/ir.instacheeta.instacheeta/databases/cheetah.sqlite'.
E/SQLiteDatabase(19275): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5): , while compiling: PRAGMA journal_mode, (OS error - 2:No such file or directory)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:925)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:670)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:356)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:330)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:229)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:511)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:194)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:864)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:767)
E/SQLiteDatabase(19275): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:742)
E/SQLiteDatabase(19275): 	at com.tekartik.sqflite.Database.open(Database.java:26)
E/SQLiteDatabase(19275): 	at com.tekartik.sqflite.SqflitePlugin$6.run(SqflitePlugin.java:772)
E/SQLiteDatabase(19275): 	at android.os.Handler.handleCallback(Handler.java:808)
E/SQLiteDatabase(19275): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/SQLiteDatabase(19275): 	at android.os.Looper.loop(Looper.java:166)
E/SQLiteDatabase(19275): 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by simolus3** [comment]
Yeah, I think the problem is that after the app was put to background the database wasn't closed properly, so it's locked when re-opening. I think sqflite has some builtin protection against that, so I would assume that this is pretty rare.

If you kill your app's process and then restart the app entirely, does the error go away?

**Comment by MahdiPishguy** [comment]
@simolus3 
> 
> . I think sqflite has some builtin protection against that, so I would assume that this is pretty rare.
> 
:upside_down_face: 

i had't check, each opening app cause of i get this error. after delete database and tables this problem solved

**Comment by simolus3** [comment]
> i had't check, each opening app cause of i get this error. after delete database and tables this problem solved

Ouch, that sounds bad and definitely shouldn't happen. It's hard to work on this without knowing how to reproduce the bug though. Can you try to call [`GeneratedDatabase.close`](https://pub.dev/documentation/moor/latest/moor_web/GeneratedDatabase/close.html) when the app is closed (use a `WidgetsBindingObserver`). You would have to re-open the database manually after the app is back in foreground (just create another instance of your database class).

**Comment by MahdiPishguy** [comment]
@simolus3 ok thanks, i should be try
