### ISSUE TITLE
Unhandled Exception when using "drift_dev schema generate --data-classes --companions"

### ISSUE THREAD

**Issue by radaced** [simolus3/moor#1988]
Hello @simolus3 

While following your docs on how to write tests for migrations I encountered following error while trying to generate test code with `--data-classes` and `--companions` for my database schema in a flutter project:

```
Unhandled exception:
Could not format because the source could not be parsed:

line 189, column 30 of .: Expected an identifier.
    ╷
189 │ working_type_definition_fts({});factory working_type_definition_fts.fromData(Map<String, dynamic> data, {String? prefix}) { 
    │                              ^
    ╵
line 204, column 42 of .: Expected an identifier.
    ╷
204 │ };}working_type_definition_fts copyWith({}) => working_type_definition_fts();@override
    │                                          ^
    ╵
line 210, column 45 of .: Expected an identifier.
    ╷
210 │ const working_type_definition_ftsCompanion({});
    │                                             ^
    ╵
line 211, column 46 of .: Expected an identifier.
    ╷
211 │ working_type_definition_ftsCompanion.insert({});
    │                                              ^
    ╵
line 212, column 56 of .: Expected an identifier.
    ╷
212 │ static Insertable<working_type_definition_fts> custom({}) {
    │                                                        ^
    ╵
line 214, column 49 of .: Expected an identifier.
    ╷
214 │ }working_type_definition_ftsCompanion copyWith({}) {
    │                                                 ^
    ╵
#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:144:7)
#1      DartFormatter.format (package:dart_style/src/dart_formatter.dart:72:12)
#2      GenerateUtilsCommand._writeSchemaFile (package:drift_dev/src/cli/commands/schema/generate_utils.dart:183:40)
#3      GenerateUtilsCommand.run (package:drift_dev/src/cli/commands/schema/generate_utils.dart:77:13)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#5      MoorCli.run (package:drift_dev/src/cli/cli.dart:65:5)
<asynchronous suspension>
#6      run (package:drift_dev/src/cli/cli.dart:19:12)
<asynchronous suspension>
pub finished with exit code `255`
```

I have a table `WorkingTypeDefinitionTable` that includes a drift-file that creates a virtual table for full-text-search.

**app_database.dart**
```
@DriftDatabase(tables: [
  WorkingTypeDefinitionTable,
  ...
], daos: [
  WorkingTypeTableDao,
  ...
], queries: {
  ...
}, include: {
  'drift_files/working_type_definition_fts.drift',
  ...
})
...
```

**working_type_table_dao.dart**
```
part 'working_type_table_dao.g.dart';

@DriftAccessor(
  tables: [WorkingTypeDefinitionTable],
  include: {'../drift_files/working_type_definition_fts.drift'},
  queries: {
    'workingTypeSearch':
        "SELECT * FROM working_type_definition_table WHERE rowid IN (SELECT rowid FROM working_type_definition_fts WHERE working_type_definition_fts MATCH :searchTerm ORDER BY rank); "
  },
)
class WorkingTypeTableDao extends DatabaseAccessor<AppDatabase> with _$WorkingTypeTableDaoMixin {...}
```

**working_type_definition_fts.drift**
```
import 'package:isa/core/repositories/db/tables/working_type_definition_table.dart';

CREATE VIRTUAL TABLE working_type_definition_fts USING fts5(
    name,
    description,
    search_terms,
    content='working_type_definition_table',
    tokenize = "unicode61 tokenchars '.'"
);

CREATE TRIGGER working_type_definition_ai AFTER INSERT ON working_type_definition_table
    BEGIN
        INSERT INTO working_type_definition_fts (rowid, name, description, search_terms)
        VALUES (new.rowid, new.name, new.description, new.search_terms);
    END;

CREATE TRIGGER working_type_definition_ad AFTER DELETE ON working_type_definition_table
    BEGIN
        INSERT INTO working_type_definition_fts (working_type_definition_fts, rowid, name, description, search_terms)
        VALUES ('delete', old.rowid, old.name, old.description, old.search_terms);
    END;

CREATE TRIGGER working_type_definition_au AFTER UPDATE ON working_type_definition_table
    BEGIN
        INSERT INTO working_type_definition_fts (working_type_definition_fts, rowid, name, description, search_terms)
        VALUES ('delete', old.rowid, old.name, old.description, old.search_terms);
        INSERT INTO working_type_definition_fts (rowid, name, description, search_terms)
        VALUES (new.rowid, new.name, new.description, new.search_terms);
    END;
```

and last but not least my **build.yaml**
```
targets:
    $default:
      builders:
        drift_dev:
          options:
            generate_connect_constructor: true
            apply_converters_on_variables: true
            generate_values_in_copy_with: true
            new_sql_code_generation: true
            scoped_dart_components: true
            sqlite_modules:
              - fts5
```

When I remove the includes of the drift file (resp. no virtual table schema is created etc.) the generation of test code with `--data-classes` and `--companions` works. I assume there is an issue when drift_dev generates the schema/json for the virtual table that then gets reused for generating the testing code.

If you need further info/code to possibly reproduce the issue let me know.

Thank you very much in advance for your help.

**Comment by simolus3** [comment]
Thanks for the detailed report! I've just fixed this on `develop` and will put this into the next release (hopefully out very soon, :crossed_fingers:)
