### ISSUE TITLE
Some expressions crash when being used as default constraint

### ISSUE THREAD

**Issue by MohiuddinM** [simolus3/moor#24]
```
I/flutter ( 8123): error NoSuchMethodError: The getter 'typeSystem' was called on null.
I/flutter ( 8123): Receiver: null
I/flutter ( 8123): Tried calling: typeSystem during open, closing...
I/flutter ( 8123): error NoSuchMethodError: The getter 'typeSystem' was called on null.
I/flutter ( 8123): Receiver: null
I/flutter ( 8123): Tried calling: typeSystem during open, closing...
E/flutter ( 8123): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'typeSystem' was called on null.
E/flutter ( 8123): Receiver: null
E/flutter ( 8123): Tried calling: typeSystem
E/flutter ( 8123): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 8123): #1      Constant.writeInto (package:moor/src/runtime/expressions/variables.dart:72:35)
E/flutter ( 8123): #2      GeneratedColumn.writeColumnDefinition (package:moor/src/runtime/structure/columns.dart:49:22)
E/flutter ( 8123): #3      Migrator.createTable (package:moor/src/runtime/migration.dart:67:14)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
E/flutter ( 8123): #5      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter ( 8123): #6      Future.wait (dart:async/future.dart:393:26)
E/flutter ( 8123): #7      Migrator.createAllTables (package:moor/src/runtime/migration.dart:51:19)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #8      _defaultOnCreate (package:moor/src/runtime/migration.dart:14:48)
E/flutter ( 8123): #9      GeneratedDatabase.handleDatabaseCreation (package:moor/src/runtime/database.dart:222:22)
E/flutter ( 8123): #10     FlutterQueryExecutor.ensureOpen.<anonymous closure> (package:moor_flutter/moor_flutter.dart:110:27)
E/flutter ( 8123): #11     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.doOpen.<anonymous closure> (package:sqflite/src/database_mixin.dart:661:29)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #12     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin._runTransaction (package:sqflite/src/database_mixin.dart:433:28)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #13     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.transaction.<anonymous closure> (package:sqflite/src/database_mixin.dart:450:14)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #14     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart:275:26)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #15     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite/src/database_mixin.dart:307:7)
E/flutter ( 8123): #16     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.transaction (package:sqflite/src/database_mixin.dart:449:12)
E/flutter ( 8123): #17     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.doOpen (package:sqflite/src/database_mixin.dart:651:15)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #18     SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:32:22)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #19     _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite/src/factory_mixin.dart:100:43)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #20     ReentrantLock.synchronized.<anonymous closure>.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:33:24)
E/flutter ( 8123): #21     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 8123): #22     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 8123): #23     _runZoned (dart:async/zone.dart:1516:10)
E/flutter ( 8123): #24     runZoned (dart:async/zone.dart:1463:12)
E/flutter ( 8123): #25     ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:32:24)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #26     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #27     ReentrantLock.synchronized (package:synchronized/src/reentrant_lock.dart:28:17)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #28     _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.openDatabase (package:sqflite/src/factory_mixin.dart:66:17)
E/flutter ( 8123): #29     openDatabase (package:sqflite/sqflite.dart:146:26)
E/flutter ( 8123): #30     FlutterQueryExecutor.ensureOpen (package:moor_flutter/moor_flutter.dart:107:16)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #31     QueryExecutor.doWhenOpened (package:moor/src/runtime/executor/executor.dart:15:12)
E/flutter ( 8123): #32     SimpleSelectStatement._getWithQuery (package:moor/src/runtime/statements/select.dart:165:49)
E/flutter ( 8123): <asynchronous suspension>
E/flutter ( 8123): #33     SimpleSelectStatement.get (package:moor/src/runtime/statements/select.dart:161:12)
E/flutter ( 8123): <asynchronous suspension>
```

**Comment by simolus3** [comment]
Thanks for the report!
Just published moor 1.3.2, which fixes this problem. Running `flutter packages upgrade` should resolve this for you.
