### ISSUE TITLE
Database locked with prepared statements cache

### ISSUE THREAD

**Issue by YeungKC** [simolus3/moor#2464]
When I upgraded to 2.8.1, I got an error about database locked, that wasn't there before, The detailed error is :

```

SqliteException(5): while executing, cannot commit transaction - SQL statements in progress, database is locked (code 5)
  Causing statement: COMMIT TRANSACTION, parameters: 
```

PS: Always happened with COMMIT TRANSACTION.

I found that it was caused by the #2434, the change inside is actually very simple, just caching commonly used statements, but when not using cache, there is a slight difference in logic compared to the previous code, specifically that `CommonPreparedStatement.dispose()` is not called.

https://github.com/simolus3/drift/commit/45353a7693c928f06d81b357428585514729c417#diff-acd603f6276d61fb2f09c053ff4d50f15ffcc3271ec14940c4d377554cc01e2dL121

When I directly changed this code add manually called `CommonPreparedStatement.dispose()` when cache was disabled, I did not get the database locked anymore.

Finally, I curious, is `CommonPreparedStatement.dispose()` not supposed to be called? if using cache, is it unnecessary?

**Comment by simolus3** [comment]
The reason we're not disposing the statement directly is that the statement is potentially being cached to be re-used later, so we want to keep it around.

Can you enable `logStatements: true` and post the statements that happen inside the transaction?

@davidmartos96 Have you seen this error before or do you have some clues on how this might happen? I guess we might not be fully executing some other statements before.

I've messed up by forgetting to add this feature to the changelog, given that is has caused some problems I'm leaning towards a patch release that disables statement caching by default until the next minor drift release.

**Comment by davidmartos96** [comment]
@simolus3 I did not see such error unfortunately. But I think the problem is that the individual stmt.dispose() was not added when the cache statements flag is false. That was a slip up on my part.

It would be great to add an extra test that fails with a non caching database.

Yes, maybe it can get delayed until the next update.

**Comment by YeungKC** [comment]
> The reason we're not disposing the statement directly is that the statement is potentially being cached to be re-used later, so we want to keep it around.↳
> 
> Can you enable `logStatements: true` and post the statements that happen inside the transaction?↳
> 
> @davidmartos96 Have you seen this error before or do you have some clues on how this might happen? I guess we might not be fully executing some other statements before.↳
> 
> I've messed up by forgetting to add this feature to the changelog, given that is has caused some problems I'm leaning towards a patch release that disables statement caching by default until the next minor drift release.↳

I have downgrade to 2.8.0, When I switch to 2.8.1, I got a new Error:

```
Bad state: Tried to operate on a released prepared statement
#0      StatementImplementation._ensureNotFinalized (package:sqlite3/src/implementation/statement.dart:70:7)
#1      StatementImplementation.select (package:sqlite3/src/implementation/statement.dart:272:5)
#2      Sqlite3Delegate.runSelect (package:drift/src/sqlite3/database.dart:152:25)
#3      _BaseExecutor.runSelect.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:77:19)
#4      _BaseExecutor._synchronized (package:drift/src/runtime/executor/helpers/engines.dart:61:20)
#5      _BaseExecutor.runSelect (package:drift/src/runtime/executor/helpers/engines.dart:74:26)
#6      CustomVmDatabaseWrapper.runSelect.<anonymous closure> (package:flutter_app/db/custom_vm_database_wrapper.dart:57:29)
#7      CustomVmDatabaseWrapper.logWrapper (package:flutter_app/db/custom_vm_database_wrapper.dart:83:25)
#8      CustomVmDatabaseWrapper.runSelect (package:flutter_app/db/custom_vm_database_wrapper.dart:56:7)
#9      DatabaseConnection.runSelect (package:drift/src/runtime/api/connection.dart:108:16)
#10     ServerImplementation._runQuery (package:drift/src/remote/server_impl.dart:157:44)
<asynchronous suspension>
#11     DriftCommunication.setRequestHandler.<anonymous closure> (package:drift/src/remote/communication.dart:165:20)
<asynchronous suspension>
```


I tried writing a test case to reproduce the issue, but I failed.

In our app, the situation be much more complex, so I'm not sure what's causing the problem.

**Comment by simolus3** [comment]
Could you add this to your pubspec? It will disable statement caching by default, it would be good to know whether there's still a regression from 2.8.0 that's not fixed in that version. If there isn't, I'll publish that version to pub.

```yaml
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift
```

**Comment by YeungKC** [comment]
> 

It's working now~

**Comment by simolus3** [comment]
Thanks for the confirmation. The fix has been released in `drift: 2.8.2` so you can remove the dependency override, but I'd still like to figure out the root cause of the original problem.

> SQL statements in progress, database is locked

This SQL statements in progress sounds like we might have started stepping through a select statement, but didn't finish it. So the statement would still be active later since we didn't actively reset/dispose it. @YeungKC, if you have more information about the statements being run in the transaction or a way to reproduce it, that would be much appreciated!

**Comment by simolus3** [comment]
From [here](https://www.sqlite.org/lang_transaction.html):

> A statement finishes when its last cursor closes, which is guaranteed to happen when the prepared statement is [reset](https://www.sqlite.org/c3ref/reset.html) or [finalized](https://www.sqlite.org/c3ref/finalize.html). Some statements might "finish" for the purpose of transaction control prior to being reset or finalized, but there is no guarantee of this.

So it sounds like we should probably call `sqlite3_reset()` when returning a statement into the cache. I was able to reproduce the issue [with direct sqlite3 APIs](https://github.com/simolus3/sqlite3.dart/blob/6f4ed364f79141efd060f39c750e141fa433d86e/sqlite3/test/common/prepared_statement.dart#L264-L281), but I don't see how that could happen in drift since we're always fully stepping through a statement when executing it.

**Comment by rkistner** [comment]
I ran into this issue with the web database - there doesn't seem to be any way to disable the prepared statement cache when using `WasmDatabase.open()`.

Here's an example reproducing the issue (using `NativeDatabase` with `cachePreparedStatements` for simplicity, but the same happens when using `WasmDatabase`):

https://gist.github.com/rkistner/3e4f0c4e5866ec5800a1ebfec1dba1d9

Output:

```
[{id: 2, parent: 0, notused: 0, detail: SEARCH test USING COVERING INDEX i1 (description=?)}]
Unhandled exception:
SqliteException(6): while executing, database table is locked, database table is locked (code 6)
  Causing statement: drop index i1, parameters: 
```

Basically, keeping a `EXPLAIN QUERY PLAN` statement open locks the table schema, which then causes the index delete to fail.

Calling `stmt.reset()` [here](https://github.com/simolus3/drift/blob/2d00149cb90da1187a36f1fe96e2e27e3ae30827/drift/lib/src/sqlite3/database.dart#L190) fixes the "database table is locked" issue. However, it causes a different problem in this example: Running the EXPLAIN QUERY PLAN returns the old query plan using the deleted index. Ideally it would be possible to disable statement caching for WasmDatabase, or always avoid caching "EXPLAIN" queries specifically (can use [sqlite3_stmt_isexplain](https://www.sqlite.org/c3ref/stmt_isexplain.html) for this).

I'm not sure if there are any examples not using the combination of explain + schema modifications that would cause this issue. It's probably not common when using drift normally - more common when using manual SQL statements.

**Comment by simolus3** [comment]
Thanks for the pointers, this super helpful! I've exposed `sqlite3_stmt_isexplain` in version 2.4.0 of the `sqlite3` package and I'll use that information to not cache these statements.

We should have an option to disable statement caching on the web, but it requires changes to the protocol as well since that flag has to be transported to the worker hosting the database.
