### ISSUE TITLE
How to switch links from different sqlite files

### ISSUE THREAD

**Issue by JasonYHZ** [simolus3/moor#2514]
In app, I need to dynamically create corresponding sqlite files according to the user's id. When one of my users logs out, and then another user logs in, how do I switch the corresponding sqlite files of other users?

Now I have recreated an object after using the close () method

However, the following error prompt appears on the recreated object

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Tried to send Request (id = 18): StatementMethod.deleteOrUpdate: UPDATE chatRecord SET isRead = ?1 WHERE channelId = ?2 AND senderId = ?3 with [1, 16ecf86d7133400116ea8f118832c002, 1651968312272437249] over isolate channel, but the connection was closed!
#0      DriftCommunication._send (package:drift/src/remote/communication.dart:128:7)
#1      DriftCommunication.request (package:drift/src/remote/communication.dart:115:5)
#2      _BaseExecutor._runRequest (package:drift/src/remote/client_impl.dart:97:28)
#3      _BaseExecutor.runUpdate (package:drift/src/remote/client_impl.dart:119:12)
#4      LazyDatabase.runUpdate (package:drift/src/utils/lazy_database.dart:88:17)
#5      DatabaseConnection.runUpdate (package:drift/src/runtime/api/connection.dart:112:16)
#6      LazyDatabase.runUpdate (package:drift/src/utils/lazy_database.dart:88:17)
#7      DatabaseConnectionUser.customUpdate.<anonymous closure> (package:drift/src/runtime/api<…>
```
My logic for creating the database is like this.

```

class ChatDatabaseService extends GetxService {
  static ChatDatabaseService get to => Get.find();

  late ChatDatabase chatDatabase;

  void connect(String uid) {
    chatDatabase = ChatDatabase(uid);
  }
  void close() {
    chatDatabase.close();
  }
}

```

**Comment by simolus3** [comment]
Closing the old database and then opening the new one under a different path sounds reasonable.

This sounds similar to #2515: There appears to be a place where you're running an update asynchronously (someplace where you set `isRead: true`) after you've closed the database. The only solution at the moment is to not do that, but since it has come up multiple times, perhaps we should improve the APIs here. Do you have a way to not use the old database after closing it (this may be hard to implement when some tasks are accessing the database asynchronously, or are not properly notified that there is a new database instance).

**Comment by zhanchen18** [comment]
Is there any good solution to this problem? After closing the database, I created a new database when I logged in again, but there was a problem that insert could be executed successfully, but insertAll failed.

`
E/flutter ( 7288): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Tried to send Request (id = 78): RunTransactionAction(NestedExecutorControl.rollback, null) over isolate channel, but the connection was closed!
E/flutter ( 7288): #0      DriftCommunication._send (package:drift/src/remote/communication.dart:128:7)
E/flutter ( 7288): #1      DriftCommunication.request (package:drift/src/remote/communication.dart:115:5)
E/flutter ( 7288): #2      _RemoteTransactionExecutor._sendAction (package:drift/src/remote/client_impl.dart:239:10)
E/flutter ( 7288): #3      _RemoteTransactionExecutor.rollback (package:drift/src/remote/client_impl.dart:247:11)
E/flutter ( 7288): #4      Batch._commit (package:drift/src/runtime/api/batch.dart:203:28)
E/flutter ( 7288): <asynchronous suspension>
`
