### ISSUE TITLE
Error while do upsert

### ISSUE THREAD

**Issue by Maged12** [simolus3/moor#2573]
```dart
db.into(db.products).insert(
            productsList[i],
            onConflict: DoUpdate(
              target: [
                db.products.sku,
                db.products.productName,
              ],
              (old) => ProductsCompanion.custom(
                quantity: const Constant(50),
              ),
            ),
          );
```

in this lines of code i try to make upsert but i get this error and i don't know what is the problem with my code 

```
Unhandled Exception: SqliteException(1): while preparing statement, ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint, SQL logic error (code 1)
  Causing statement: INSERT INTO "products" ("inventory_id", "product_name", "product_description", "product_sku", "product_quantity", "product_unite_warning_quantity", "product_unite_price", "product_unite_sale_price", "product_unite_cost_Price", "product_box_warning_quantity", "product_box_price", "product_box_sale_price", "product_box_cost_Price", "product_box_amount", "is_kilogram", "created_by", "updated_by", "has_box") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT("product_sku", "product_name") DO UPDATE SET "product_quantity" = 50.0

#0      DriftCommunication.request (package:drift/src/remote/communication.dart:113:66)
#1      _BaseExecutor._runRequest (package:drift/src/remote/client_impl.dart:97:28)
#2      _BaseExecutor.runInsert (package:drift/src/remote/client_impl.dart:124:12)
#3      LazyDatabase.runInsert (package:drift/src/utils/lazy_database.dart:78:17)
#4      DatabaseConnection.runInsert (package:drift/src/runtime/api/connection.dart:103:16)
#5      LazyDatabase.runInsert (package:drift/src/utils/lazy_database.dart:78:17)
#6      InsertStatement.insert.<anonymous closure> (package:drift/src/runtime/query_builder/statements/insert.dart:74:26)
#7      DatabaseConnectionUser.doWhenOpened.<anonymous closure> (package:drift/src/runtime/api/connection_user.dart:162:64)
<asynchronous suspension>
#8      InsertStatement.insert (package:drift/src/runtime/query_builder/statements/insert.dart:73:12)
<asynchronous suspension>
#9      _AddInvoiceWidgetState.addProductsToProductsTable (package:crm_app/presentaion/suppliers/widgets/add_invoice_widget.dart:41:22)
<asynchronous suspension>
#10     _AddInvoiceWidgetState.build.<anonymous closure> (package:crm_app/presentaion/suppliers/widgets/add_invoice_widget.dart:458:31)
<asynchronous suspension>
```

**Comment by simolus3** [comment]
Well, what is the primary key of `products`? Did you [add a unique constraint](https://drift.simonbinder.eu/api/drift/table/uniquekeys) for the two columns? As the error message explains, the combination for which you want to detect duplicates needs to be unique. You can also remove the `target` field to make drift use the primary key as a default.

**Comment by Maged12** [comment]
```dart
class Products extends Table {
  IntColumn get productId => integer().named("id").autoIncrement()();

  IntColumn get inventoryId =>
      integer().named("inventory_id").references(Inventories, #id)();

  TextColumn get productName => text().named("product_name").unique()();

  TextColumn get productDescription =>
      text().named("product_description").nullable()();

  TextColumn get sku => text().named("product_sku").unique()();

  RealColumn get quantity => real().named("product_quantity")();

  RealColumn get uniteWarningQuantity =>
      real().named("product_unite_warning_quantity")();

  RealColumn get unitePrice => real().named("product_unite_price")();

  RealColumn get uniteSalePrice =>
      real().named("product_unite_sale_price").nullable()();

  RealColumn get uniteCostPrice => real().named("product_unite_cost_Price")();

  IntColumn get boxWarningQuantity =>
      integer().named("product_box_warning_quantity").nullable()();

  RealColumn get boxPrice => real().named("product_box_price").nullable()();

  RealColumn get boxSalePrice =>
      real().named("product_box_sale_price").nullable()();

  RealColumn get boxCostPrice => real().named("product_box_cost_Price").nullable()();

  IntColumn get boxAmount => integer().named("product_box_amount").nullable()();

  BoolColumn get isKilogram => boolean().withDefault(const Constant(true))();

  IntColumn get createdBy =>
      integer().named("created_by").references(Users, #id)();

  IntColumn get updatedBy =>
      integer().named("updated_by").references(Users, #id)();

  DateTimeColumn get createdAt =>
      dateTime().named("created_at").withDefault(currentDateAndTime)();

  DateTimeColumn get updatedAt =>
      dateTime().named("updated_at").withDefault(currentDateAndTime)();

  BoolColumn get isDeleted => boolean().withDefault(const Constant(false))();
  BoolColumn get hasBox => boolean().withDefault(const Constant(false))();
}
```

this is my table and i wanna update the product if the sku or productName already exists

**Comment by simolus3** [comment]
>i wanna update the product if the sku or productName already exists

As far as I know, this is not possible with an upsert. Using `sku` and `productName` as a combination would trigger when the _pair_ of `(sku, productName)` already exists, not when either one is in conflict.

I think the best alternative is to:

1. Start a transaction.
2. Run a select statement finding the ids of products with the same sku or product name.
3. If those exists, update them (note that there could be more than one since they columns are only unique in isolation, not in their combination. There could be a product with the same SKU and another one with the same name).
4. Otherwise, run an insert statement.

But if that matches what you want to express in your schema, you could also define your table to not make `sku` and `productName` `unique()`. Instead, you'd do this:

```dart
class Products extends Table {
  IntColumn get productId => integer().named("id").autoIncrement()();
  // other columns...
  BoolColumn get hasBox => boolean().withDefault(const Constant(false))();

  @override
   Set<Column> get uniqueKeys => [{sku, productName}];
}
```

This will always make the pair of SKU and product name unique in the table, instead of enforcing uniqueness of the individual columns on their own. That will also make your original query work.
