### ISSUE TITLE
When a file is named `enum.dart` `drift_dev` crashes

### ISSUE THREAD

**Issue by ValentinVignal** [simolus3/moor#2628]
**Describe the bug**

<details>
<summary>Code sample</summary>

You can also check out https://github.com/ValentinVignal/flutter_app_stable/tree/drift/crash-with-enum.dart

```dart
// lib/database.dart

import 'package:drift/drift.dart';

import 'todo.table.dart';
import 'enum.dart';

part 'database.g.dart';

@DriftDatabase(tables: [
  Todos,
])
class Database extends _$Database {
  Database(QueryExecutor e) : super(e);

  @override
  int get schemaVersion => 1;
}
```

```dart
// lib/todo.table.dart

import 'package:drift/drift.dart';

import 'enum.dart';

class Todos extends Table {
  IntColumn get id => integer()();
  TextColumn get title => text()();

  IntColumn get badEnum => intEnum<MyEnum>()();
}
```

```dart
// lib/enum.dart

enum MyEnum {
  entry0,
  entry1,
}
```

</details>

When I run 

```shell
flutter pub run build_runner build --delete-conflicting-outputs -v
```

it crashes.

<details>

<summary>Logs</summary>

```
[   +8 ms] executing: sw_vers -productName
[  +26 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.3.1
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22E772610a
[        ] executing: uname -m
[   +6 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +81 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +59 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +109 ms] executing: [/Users/valentin/Perso/Projects/flutter_app_stable/] /Users/valentin/flutter/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run build_runner build
--delete-conflicting-outputs -v
FINE: Pub 3.1.2
MSG : Deprecated. Use `dart run` instead.
FINE: Package Config up to date.
FINE: Package Config up to date.
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 379ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 110ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 965ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 15ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 68ms

[SEVERE] drift_dev on lib/database.dart (cached):

type 'Null' is not a subtype of type 'ClassElement' in type cast
package:drift_dev/src/analysis/resolver/dart/helper.dart 52:55  new KnownDriftTypes._fromLibrary
package:drift_dev/src/analysis/resolver/dart/helper.dart 94:28  KnownDriftTypes.resolve
package:drift_dev/src/analysis/driver/driver.dart 93:28         DriftAnalysisDriver.loadKnownTypes
package:drift_dev/src/analysis/resolver/discover.dart 76:46     DiscoverStep.discover
package:drift_dev/src/analysis/driver/driver.dart 129:7         DriftAnalysisDriver.discoverIfNecessary
package:drift_dev/src/analysis/driver/driver.dart 166:7         DriftAnalysisDriver.findLocalElements
package:drift_dev/src/backends/build/analyzer.dart 36:22        DriftDiscover.build

[SEVERE] drift_dev on lib/database.dart (cached):

type 'Null' is not a subtype of type 'ClassElement' in type cast
package:drift_dev/src/analysis/resolver/dart/helper.dart 52:55  new KnownDriftTypes._fromLibrary
package:drift_dev/src/analysis/resolver/dart/helper.dart 94:28  KnownDriftTypes.resolve
package:drift_dev/src/analysis/driver/driver.dart 93:28         DriftAnalysisDriver.loadKnownTypes
package:drift_dev/src/analysis/resolver/discover.dart 76:46     DiscoverStep.discover
package:drift_dev/src/analysis/driver/driver.dart 129:7         DriftAnalysisDriver.discoverIfNecessary
package:drift_dev/src/backends/build/analyzer.dart 97:5         DriftAnalyzer.build

[SEVERE] drift_dev on lib/todo.table.dart (cached):

type 'Null' is not a subtype of type 'ClassElement' in type cast
package:drift_dev/src/analysis/resolver/dart/helper.dart 52:55  new KnownDriftTypes._fromLibrary
package:drift_dev/src/analysis/resolver/dart/helper.dart 94:28  KnownDriftTypes.resolve
package:drift_dev/src/analysis/driver/driver.dart 93:28         DriftAnalysisDriver.loadKnownTypes
package:drift_dev/src/analysis/resolver/discover.dart 76:46     DiscoverStep.discover
package:drift_dev/src/analysis/driver/driver.dart 129:7         DriftAnalysisDriver.discoverIfNecessary
package:drift_dev/src/analysis/driver/driver.dart 166:7         DriftAnalysisDriver.findLocalElements
package:drift_dev/src/backends/build/analyzer.dart 36:22        DriftDiscover.build

[SEVERE] drift_dev on lib/enum.dart (cached):

type 'Null' is not a subtype of type 'ClassElement' in type cast
package:drift_dev/src/analysis/resolver/dart/helper.dart 52:55  new KnownDriftTypes._fromLibrary
package:drift_dev/src/analysis/resolver/dart/helper.dart 94:28  KnownDriftTypes.resolve
package:drift_dev/src/analysis/driver/driver.dart 93:28         DriftAnalysisDriver.loadKnownTypes
package:drift_dev/src/analysis/resolver/discover.dart 76:46     DiscoverStep.discover
package:drift_dev/src/analysis/driver/driver.dart 129:7         DriftAnalysisDriver.discoverIfNecessary
package:drift_dev/src/backends/build/analyzer.dart 97:5         DriftAnalyzer.build

[SEVERE] drift_dev on lib/todo.table.dart (cached):

type 'Null' is not a subtype of type 'ClassElement' in type cast
package:drift_dev/src/analysis/resolver/dart/helper.dart 52:55  new KnownDriftTypes._fromLibrary
package:drift_dev/src/analysis/resolver/dart/helper.dart 94:28  KnownDriftTypes.resolve
package:drift_dev/src/analysis/driver/driver.dart 93:28         DriftAnalysisDriver.loadKnownTypes
package:drift_dev/src/analysis/resolver/discover.dart 76:46     DiscoverStep.discover
package:drift_dev/src/analysis/driver/driver.dart 129:7         DriftAnalysisDriver.discoverIfNecessary
package:drift_dev/src/backends/build/analyzer.dart 97:5         DriftAnalyzer.build

[SEVERE] drift_dev on lib/enum.dart (cached):

type 'Null' is not a subtype of type 'ClassElement' in type cast
package:drift_dev/src/analysis/resolver/dart/helper.dart 52:55  new KnownDriftTypes._fromLibrary
package:drift_dev/src/analysis/resolver/dart/helper.dart 94:28  KnownDriftTypes.resolve
package:drift_dev/src/analysis/driver/driver.dart 93:28         DriftAnalysisDriver.loadKnownTypes
package:drift_dev/src/analysis/resolver/discover.dart 76:46     DiscoverStep.discover
package:drift_dev/src/analysis/driver/driver.dart 129:7         DriftAnalysisDriver.discoverIfNecessary
package:drift_dev/src/analysis/driver/driver.dart 166:7         DriftAnalysisDriver.findLocalElements
package:drift_dev/src/backends/build/analyzer.dart 36:22        DriftDiscover.build

[SEVERE] Build:
Failed after 130ms
IO  : Writing 9851 characters to text file /Users/valentin/.pub-cache/log/pub_log.txt.
MSG : Logs written to /Users/valentin/.pub-cache/log/pub_log.txt.
[+3517 ms] pub failed
                    command: "/Users/valentin/flutter/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run build_runner build --delete-conflicting-outputs -v"
                    pub env: {
                      "FLUTTER_ROOT": "/Users/valentin/flutter/flutter",
                      "PUB_ENVIRONMENT": "flutter_cli:forward",
                    }
                    exit code: 1

[  +13 ms] "flutter run" took 3,713ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
           <asynchronous suspension>
           #2      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:530:5)
           <asynchronous suspension>
           #3      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:133:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +197 ms] ensureAnalyticsSent: 189ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

I works fine if I rename `enum.dart` into `my_enum.dart`

**Comment by simolus3** [comment]
Could it be that you're applying a dependency override to `drift_dev` without applying one to `drift` as well?

I can't reproduce this issue with the latest drift/drift_dev versions from pub or the ones currently used on `develop` in this repository.

**Comment by ValentinVignal** [comment]
Hum weird I cannot reproduce the issue anymore as well 🤔 

> Could it be that you're applying a dependency override to drift_dev without applying one to drift as well?

I definitely could have done that at some point but when I was creating this issue I didn't have any override anymore (As you can see in the repo I linked). Maybe there was still an issue in the flutter cache that was not cleared?

I can close this since it seems to work.
