### ISSUE TITLE
Exception when closing database if --enable-asserts is omitted

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#275]
After upgrading to Dart 2.7/Flutter 1.12.8, running this file:
```dart
// repro.dart:
import 'package:moor/moor.dart';
import 'package:moor_ffi/moor_ffi.dart';

void main() async {
  await EmptyDb(VmDatabase.memory()).close();
}

class EmptyDb extends GeneratedDatabase {

  EmptyDb(QueryExecutor driver) : super(SqlTypeSystem.defaultInstance, driver);

  @override
  final List<TableInfo> allTables = const [];

  @override
  int schemaVersion = 1;
}
```
with `flutter/bin/cache/dart-sdk/bin/dart.exe repro.dart` throws the following exception:
```
Unhandled exception:
NoSuchMethodError: The method '-' was called on null.
Receiver: null
Tried calling: -(1)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      GeneratedDatabase.close (package:moor/src/runtime/api/db_base.dart:127:32)
```

while right-click -> `Run 'repro.dart'` in IntelliJ works fine - it looks like the `--enable-asserts` that IntelliJ adds is making it work. Running `flutter/bin/cache/dart-sdk/bin/dart.exe --enable-asserts repro.dart` fixes the error.

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows)
    • Flutter version 1.12.13+hotfix.5 at F:\flutter
    • Framework revision 27321ebbad (23 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


moor:file:///F:/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.1.0/lib/
moor_ffi:file:///F:/flutter/.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.2.0/lib/
moor_flutter:file:///F:/flutter/.pub-cache/hosted/pub.dartlang.org/moor_flutter-2.0.0/lib/
moor_generator:file:///F:/flutter/.pub-cache/hosted/pub.dartlang.org/moor_generator-2.1.1/lib/
```

**Comment by simolus3** [comment]
Thanks for the report. This has already been fixed on `develop`, I don't know why I didn't release a hotfix right away. I've cherry-picked that and another small fix to master and released `moor 2.1.1`, which should fix the problem.
