### ISSUE TITLE
Unknown issue on Safari, with Potential route of Discovery

### ISSUE THREAD

**Issue by Dall127** [simolus3/moor#2812]
## Environment
- Browser: Safari
- Context: WebAssembly storage implementation

## Issue Description
Experiencing a peculiar inconsistency with Safari in handling storage using WebAssembly. This issue is not observed in other browsers, regardless of whether they are in private or normal modes. I wasn't experiencing this issue till transitioning to WASM.

#### Normal Mode
In normal mode, Safari selects `WasmStorageImplementation.sharedIndexedDb` due to missing:
- `MissingBrowserFeature.dedicatedWorkersInSharedWorkers`
- `MissingBrowserFeature.sharedArrayBuffers`

However, storage doesn't function as anticipated.

#### Private Mode
In private mode, additional missing features are noted:
- `MissingBrowserFeature.fileSystemAccess`

Surprisingly, it operates correctly in this mode, which contrasts with the normal mode.

### Other Browsers
In other browsers, both in private and normal modes, it works seamlessly using the same WebAssembly setup.

## Seeking Solutions
I am seeking insights or solutions to address this issue in Safari's regular browsing mode. Currently, I lack detailed debug information beyond what's provided, as it's error output is gibberish. This problem only arises on my live site (not in visiting the page during development on safari, while debugging on chrome), adding to the complexity of diagnosing it. The 'features used' might offer clues to someone well-versed in this area. If there's a better way to get debug information, I might be able to with direction on how to go about that.

**Comment by simolus3** [comment]
Thanks for the report, I'll try to reproduce this with an example from this repository.

> However, storage doesn't function as anticipated.

Is it just completely broken without giving any error message or is there more that might be relevant?

> In private mode, additional missing features are noted:

Does it also pick `sharedIndexedDb` there?

**Comment by Dall127** [comment]
it does pick ```sharedIndexedDb```

I believe that it successfully creates the Database (i.e. in my debug panel I can see the expected db got created)

though afterwards, nothing is getting stored. Normally I'd get a dropdown showing at least a little of what got stored, 
(as shown on pre-migration) 
![Screenshot 2023-12-29 at 4 17 28 PM](https://github.com/simolus3/drift/assets/31700756/952522ec-6496-4228-ac5b-590f230528bf)

After migration
![Screenshot 2023-12-29 at 4 19 17 PM](https://github.com/simolus3/drift/assets/31700756/af43ed57-ae52-44ba-86ee-51b8bedf04d2)

So I'm making the assumption that nothing is getting stored. My initial (blindly attempting) pull request's goal was to see if perhaps there was an issue with utf-8, as for why we discussed I don't think that's the case. 


output from private mode: ```Using WasmStorageImplementation.sharedIndexedDb due to missing browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.fileSystemAccess, MissingBrowserFeature.sharedArrayBuffers}```


Alls to say, my bet would be that there's something fishy with the ```fileSystemAccess``` on Safari if the lack thereof makes the implementation work

**Comment by Dall127** [comment]
Update: I think the initial trail might have been a little misleading; there's two new things that might give you clue to what's up. 
I've found potential solution for the Safari normal mode issue. This might have been a migration-to-wasm issue, though I was sure to rename the db after migrating. Not completely sure.

However, there's a new twist in Safari's private mode: storage works correctly on the first load, but fails on subsequent reloads. This is a different layer to the problem, suggesting an issue with Safari's handling of data storage and retrieval across different browsing sessions. It doesn't occur on private mode in other browsers. 

@simolus3 , If you have a discord, I can PM you a link to the site with the issue. It'll be a black box, but at least you'll be able see what states get you into what

**Comment by simolus3** [comment]
Sure, my Discord username is `simonbinder`

**Comment by SleepySquash** [comment]
I might add some strange things discovered in Safari 17.4.1. It seems like deploying web application with `Cross-Origin-Embedder-Policy` header set to `require-corp` breaks the `WasmDatabase` entirely (Safari only, other browsers have no issues). The application initializes and works perfectly fine with the first run, however on each following page refresh the `drift` throws the error in the console, unable to initialize:

<img width="1422" alt="Screenshot 2024-05-21 at 11 10 52" src="https://github.com/simolus3/drift/assets/21217248/3849a383-cb38-46e5-899a-8eb036227a70">


Note: I'm building the `examples/app` application (`cd examples/app && dart run build_runner build && flutter build web`) and then deploying it with the following command:
```
dhttpd '--headers=Cross-Origin-Embedder-Policy=require-corp;Cross-Origin-Opener-Policy=same-origin' --path build/web/
```

The `drift` picks IndexedDB for storage:
```
Using WasmStorageImplementation.sharedIndexedDb due to unsupported browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers}
```

And the culprit seems to be the IndexedDB's database not being populated, as like `WasmDatabase` doesn't have the write access (it should contain `blocks`, etc):

<img width="621" alt="Screenshot 2024-05-21 at 11 21 10" src="https://github.com/simolus3/drift/assets/21217248/e7b02ec3-d5a1-470d-be5a-1a26e6333cbe">

What's even more strange is the fact that deploying application without the COEP/COOP headers works fine and even deploying the COEP with `credentialless` works fine! However, when COEP is set to `credentialless`, the `drift` seems to consider `SharedArrayBuffer`s as being unavailable:

```
Using WasmStorageImplementation.sharedIndexedDb due to unsupported browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.sharedArrayBuffers}
```

Yet I can confirm the headers are set:

<img width="1422" alt="Screenshot 2024-05-21 at 11 11 54" src="https://github.com/simolus3/drift/assets/21217248/b7271852-5728-420c-94d2-d34e5775571e">

Perhaps Safari with COEP set to `require-corp` needs some additional deployment configuration? I'll try to investigate this a bit and leave a comment, if something is up.

UPD. The bug mentioned at https://drift.simonbinder.eu/web/#additional-headers might be related, however I'm not sure: https://bugs.webkit.org/show_bug.cgi?id=254065. Also it seems to have `RESOLVED FIXED` status.

**Comment by simolus3** [comment]
Thanks for the report! Did you already have a database from a previous run in the first screenshot? Drift should pick `opfsLocks` here, unless it detects that the IndexedDB database already exists (so that no data is lost).

> However, when COEP is set to `credentialless`, the `drift` seems to consider `SharedArrayBuffer`s as being unavailable:

When I tried that, `crossOriginIsolated` also reported `false` in the console - so shared buffers really are unavailable.

The problem, I think, comes from here: https://github.com/simolus3/drift/blob/2d870a6cf54e190dab6459dfd5060c42ce97ba2f/drift/lib/src/web/wasm_setup/shared.dart#L116-L139

We're checking whether an IndexedDB database exists because, if it does, we don't want to use OPFS even it is available. The problem is that (despite aborting the transaction) we seem to create the database inadvertently with that check. That's a big problem, because it now means that as soon as we reach a state where OPFS doesn't exist/is unavailable, we'll try to use that broken database.

Most browsers support `indexedDb.databases` though, I'll migrate the check to that if it's supported to avoid creating the database here.

**Comment by simolus3** [comment]
So I've fixed that in 996176d8a5daf535371e9512cbe8dea5b2f8b284, but that only prevents new versions from accidentally creating a bogus database. Depending on how widespread this problem is we may have to bump the schema version for IndexedDB and create the stores if they don't exist.

**Comment by ciprig** [comment]
Hi, we experience the same/similar issue on the Safari private window. The first time the app load create the db, however when refreshing/reloading the app cannot access the db "NotFoundError: The object can not be found here"
Version: 2.19.1 and latest 2.21.0

**Comment by ciprig** [comment]
It can be reproduced with the sample app from the repo: load the app in Safari incognito and after reload
```
[Log] Using WasmStorageImplementation.sharedIndexedDb due to missing browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.fileSystemAccess, MissingBrowserFeature.sharedArrayBuffers} (dart_sdk.js, line 38043)
[Log] NotFoundError: The object can not be found here. (dart_sdk.js, line 38043)
[Log] #2      request (http://localhost:49216/packages/drift/src/remote/communication.dart:113:66) (dart_sdk.js, line 38043)
[Log] #3      ensureOpen (http://localhost:49216/packages/drift/src/remote/client_impl.dart:175:10) (dart_sdk.js, line 38043)
[Log] #4      runBody (http://localhost:49216/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart:84:54) (dart_sdk.js, line 38043)
[Log] #5      _async (http://localhost:49216/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart:127:12) (dart_sdk.js, line 38043)
[Log] #6      handleValueCallback (http://localhost:49216/dart-sdk/lib/async/future_impl.dart:861:44) (dart_sdk.js, line 38043)
[Log] #7      _propagateToListeners (http://localhost:49216/dart-sdk/lib/async/future_impl.dart:890:32) (dart_sdk.js, line 38043)
[Log] #8      <anonymous closure> (http://localhost:49216/dart-sdk/lib/async/future_impl.dart:666:5) (dart_sdk.js, line 38043)
[Log] #9      <anonymous closure> (http://localhost:49216/dart-sdk/lib/async/future_impl.dart:736:7) (dart_sdk.js, line 38043)
[Log] #10     _microtaskLoop (http://localhost:49216/dart-sdk/lib/async/schedule_microtask.dart:40:11) (dart_sdk.js, line 38043)
[Log] #11     _startMicrotaskLoop (http://localhost:49216/dart-sdk/lib/async/schedule_microtask.dart:49:5) (dart_sdk.js, line 38043)
[Log] #12     <anonymous closure> (http://localhost:49216/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart:181:15) (dart_sdk.js, line 38043)```

**Comment by simolus3** [comment]
Good catch! I can reproduce the issue, but I couldn't figure out why it's happening (the error originates in the shared drift worker, which can't be debugged on Safari. There's also no stack trace). So it will likely be a bit of a challenge to track this down, but having something that reproduces this is definitely helpful.

**Comment by simolus3** [comment]
Ok, Safari doesn't support storing `Blob`s in IndexedDb in private browsing windows (or so it seems). There's a fairly easy workaround (https://github.com/simolus3/sqlite3.dart/pull/266), I'll have to do some more testing before releasing it.

**Comment by ciprig** [comment]
@simolus3 any update on this, or if I can help with something? I see the https://github.com/simolus3/sqlite3.dart/pull/266 has been closed, however, this is still open

**Comment by simolus3** [comment]
Thanks for the ping, the changes there were merged and released but this still appears to be broken. I'm not sure if a Safari update broke this in different ways in the meantime or if the fix never worked, but given that the feature-detection doesn't work and other implementations are storing `ArrayBuffer`s directly, I'll just do the same instead of worrying about blobs.

**Comment by simolus3** [comment]
Should be fixed with the worker from the [2.25.0 release](https://github.com/simolus3/drift/releases/tag/drift-2.25.0).
