### ISSUE TITLE
When using PgTypes cannot generate a dialect for Sqllite.

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2828]
Hi I am trying to get sqlite and postgres to sync up. When generating the code using the postgrestypes it does not generate code for a sqlDialect. Refering to the example I am using the code as follows:

```
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:drift_postgres/drift_postgres.dart';
import 'package:postgres/postgres.dart' as pg;
import 'package:uuid/uuid.dart';

part 'main.g.dart';

class TestingTable extends Table {
  @override
  String get tableName => 'TestingTable';

  Column<PgDate> get date => customType(PgTypes.date).nullable()();
  TextColumn get name => text()();
  BoolColumn get isAwesome => boolean().withDefault(const Constant(true))();
  // Column<double> get balance => customType(PgTypes.numeric).nullable()();
}

@DriftDatabase(tables: [TestingTable])
class DriftPostgresDatabase extends _$DriftPostgresDatabase {
  DriftPostgresDatabase(super.e);
  factory DriftPostgresDatabase.localSqlite() {
    driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
    return _instance;
  }

  factory DriftPostgresDatabase.postgreSQL() {
    driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
    return _remote;
  }
  static final DriftPostgresDatabase _instance =
      DriftPostgresDatabase(LazyDatabase(() async {
    return NativeDatabase(File('D:\\sdcard\\rohan.sqlite'),
        logStatements: true);
  }));
  static final DriftPostgresDatabase _remote = DriftPostgresDatabase(PgDatabase(
    endpoint: pg.Endpoint(
      host: 'localhost',
      database: 'postgres',
      username: 'postgres',
      password: 'postgres',
    ),
    settings: pg.ConnectionSettings(
      // If you expect to talk to a Postgres database over a public connection,
      // please use SslMode.verifyFull instead.
      sslMode: pg.SslMode.disable,
    ),
    logStatements: true,
  ));
  @override
  int get schemaVersion => 1;

  @override
  // TODO: implement migration
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
        },
        onUpgrade: (m, from, to) async {
          return;
        },
      );
}

void main() async {
  final sqlite = DriftPostgresDatabase.localSqlite();
  final postgres = DriftPostgresDatabase.postgreSQL();

  final user2 =
      await sqlite.testingTable.insertReturning(TestingTableCompanion.insert(
    name: 'Simon',
    date: Value(PgDate(year: 1996, month: 7, day: 8)),
  ));
  print(user2);
  final user = await postgres.testingTable.insertReturning(
      TestingTableCompanion.insert(
          name: 'Simon', date: Value(PgDate(year: 1996, month: 7, day: 8))));

  print(user);
  await sqlite.close();
  await postgres.close();
}

```
The error I get when inserting into the date column is:

```
Drift: Sent CREATE TABLE IF NOT EXISTS "TestingTable" ("date" date NULL, "name" TEXT NOT NULL, "is_awesome" INTEGER NOT NULL DEFAULT 1 CHECK ("is_awesome" IN (0, 1))); with args []
Unhandled exception:
Invalid argument (params[1]): Allowed parameters must either be null or bool, int, num, String or List<int>.: Instance of 'TypedValue<Object>'
#0      StatementImplementation._bindParam (package:sqlite3/src/implementation/statement.dart:243:14)
#1      StatementImplementation._bindIndexedParams (package:sqlite3/src/implementation/statement.dart:192:7)
#2      StatementImplementation._bindParams (package:sqlite3/src/implementation/statement.dart:254:9)
#3      StatementImplementation.selectWith (package:sqlite3/src/implementation/statement.dart:282:5)
#4      CommonPreparedStatement.select (package:sqlite3/src/statement.dart:75:12)
#5      Sqlite3Delegate.runSelect (package:drift/src/sqlite3/database.dart:154:27)
#6      _BaseExecutor.runSelect.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:77:19)
#7      _BaseExecutor._synchronized (package:drift/src/runtime/executor/helpers/engines.dart:61:20)
#8      _BaseExecutor.runSelect (package:drift/src/runtime/executor/helpers/engines.dart:74:26)
#9      LazyDatabase.runSelect (package:drift/src/utils/lazy_database.dart:83:22)
#10     InsertStatement.insertReturningOrNull.<anonymous closure> (package:drift/src/runtime/query_builder/statements/insert.dart:174:30)
#11     DatabaseConnectionUser.doWhenOpened.<anonymous closure> (package:drift/src/runtime/api/connection_user.dart:162:64)
<asynchronous suspension>
#12     InsertStatement.insertReturning (package:drift/src/runtime/query_builder/statements/insert.dart:152:9)
<asynchronous suspension>
#13     main (file:///D:/Github/drift/extras/drift_postgres/example/main.dart:72:7)
<asynchronous suspension>
Drift: Sent INSERT INTO "TestingTable" ("date", "name") VALUES (?, ?) RETURNING * with args [TypedValue(Type(oid:1082), 1996-07-08 00:00:00.000), Simon]

Process finished with exit code 255

```
Looking at the generated code, i see no seperate code is generated for the sql dialect. Is there a way for me to differentiate between the two? Could I maybe using a type converter to convert it down?

**Comment by simolus3** [comment]
> Is there a way for me to differentiate between the two?

At the moment, no there isn't. The postgres types are supposed to work on postgres only.

As a (horrible) workaround, you can have the type remember whether it's running against postgres or not:

```dart
class MultiDialectDate implements CustomSqlType<PgDate> {
  bool isPostgres = false;

  @override
  String mapToSqlLiteral(PgDate dartValue) {
    if (isPostgres) {
      return PgTypes.date.mapToSqlLiteral(dartValue);
    } else {
      return "'${dartValue.toDateTime().toIso8601String()}'";
    }
  }

  @override
  Object mapToSqlParameter(PgDate dartValue) {
    if (isPostgres) {
      return PgTypes.date.mapToSqlParameter(dartValue);
    } else {
      return dartValue.toDateTime().toIso8601String();
    }
  }

  @override
  PgDate read(Object fromSql) {
    if (isPostgres) {
      return PgTypes.date.read(fromSql);
    } else {
      return PgDate.fromDateTime(DateTime.parse(fromSql as String));
    }
  }

  @override
  String sqlTypeName(GenerationContext context) {
    if (isPostgres) {
      return 'date';
    } else {
      return 'text';
    }
  }
}
```

Then you can configure this after creating the database instance like this

```dart
  static final DriftPostgresDatabase _instance =
      DriftPostgresDatabase(LazyDatabase(() async {
    return NativeDatabase(File('rohan.sqlite'), logStatements: true);
  }))
        .._markIsPostgres(false);
  static final DriftPostgresDatabase _remote = DriftPostgresDatabase(PgDatabase(
    endpoint: pg.Endpoint(
      host: 'localhost',
      database: 'postgres',
      username: 'postgres',
      password: 'postgres',
    ),
    settings: pg.ConnectionSettings(
      // If you expect to talk to a Postgres database over a public connection,
      // please use SslMode.verifyFull instead.
      sslMode: pg.SslMode.disable,
    ),
    logStatements: true,
  ))
    .._markIsPostgres(true);

  void _markIsPostgres(bool postgres) {
    for (final table in allTables) {
      for (final column in table.$columns) {
        final type = column.type;
        if (type is MultiDialectDate) {
          type.isPostgres = postgres;
        }
      }
    }
  }
```

This fixes the problem, but it's horrible - I'll come up with a better API to have dialect-specific types.

**Comment by simolus3** [comment]
It will be possible to properly define dialect-specific custom types in drift 2.15 (with f25eaf10f22ed0f5fcb7b6fc8c3676c0c8903f6c).
