### ISSUE TITLE
Error while inserting into database (with a real type)

### ISSUE THREAD

**Issue by MohiuddinM** [simolus3/moor#30]
```
E/flutter (13486): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Too many elements
E/flutter (13486): #0      _ListBase&Object&ListMixin.singleWhere (dart:collection/list.dart:167:11)
E/flutter (13486): #1      SqlTypeSystem.forDartType (package:moor/src/types/type_system.dart:23:18)
E/flutter (13486): #2      Variable.mapToSimpleValue (package:moor/src/runtime/expressions/variables.dart:48:37)
E/flutter (13486): #3      Variable.writeInto (package:moor/src/runtime/expressions/variables.dart:56:33)
E/flutter (13486): #4      InsertStatement._createContext (package:moor/src/runtime/statements/insert.dart:107:16)
E/flutter (13486): #5      InsertStatement.insert (package:moor/src/runtime/statements/insert.dart:31:17)
```

**Comment by simolus3** [comment]
Thanks for the report! I'm pretty sure I know why this is happening, I'll fix it this weekend.

**Comment by MohiuddinM** [comment]
I have made a quick fix by changing:

```
/// Returns the appropriate sql type for the dart type provided as the
  /// generic parameter.
  SqlType<T> forDartType<T>() {
    return types.singleWhere((t) => t is SqlType<T>) as SqlType<T>;
  }
```
to:

```
/// Returns the appropriate sql type for the dart type provided as the
  /// generic parameter.
  SqlType<T> forDartType<T>() {
    return types.where((t) => t is SqlType<T>).last as SqlType<T>;
  }
```

**Comment by simolus3** [comment]
I think I'll make the `RealColumn` a `Column<double>` instead of a `Column<num>` to fix this, as `num` is the supertype of `int` and `double` and we already have a dedicated `IntColumn`. But thanks for the idea!

**Comment by simolus3** [comment]
Should be fixed on the development. You probably need to re-run the build runner.

**Comment by cmedamine** [comment]
**I have the same issue while trying to insert a record**

```
E/flutter (21585): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: LateInitializationError: Field '_db@1324164674' has not been initialized.
E/flutter (21585): #0      Sqlite3Delegate._db (package:drift/src/sqlite3/database.dart)
package:drift/…/sqlite3/database.dart:1
E/flutter (21585): #1      Sqlite3Delegate._runWithArgs
package:drift/…/sqlite3/database.dart:110
E/flutter (21585): #2      Sqlite3Delegate.runInsert
package:drift/…/sqlite3/database.dart:127
E/flutter (21585): #3      _BaseExecutor.runInsert.<anonymous closure>
package:drift/…/helpers/engines.dart:99
E/flutter (21585): #4      _BaseExecutor._synchronized.<anonymous closure>
package:drift/…/helpers/engines.dart:51
E/flutter (21585): #5      new Future.sync (dart:async/future.dart:301:31)
E/flutter (21585): #6      Lock.synchronized.callBlockAndComplete
package:drift/…/utils/synchronized.dart:17
E/flutter (21585): #7      Lock.synchronized.<anonymous closure>
package:drift/…/utils/synchronized.dart:21
E/flutter (21585): #8      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (21585): #9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (21585): <asynchronous suspension>
E/flutter (21585): #10     InsertStatement.insert.<anonymous closure>
package:drift/…/statements/insert.dart:74
E/flutter (21585): <asynchronous suspension>
E/flutter (21585): #11     InsertStatement.insert
package:drift/…/statements/insert.dart:73
E/flutter (21585): <asynchronous suspension>
E/flutter (21585): #12     DealCardState._buildDealCardAddFavoriteButton.<anonymous closure>.<anonymous closure>
package:deal_hunter/…/widgets/deal_card.dart:530
E/flutter (21585): <asynchronous suspension>
E/flutter (21585):
```
