### ISSUE TITLE
Can't use converter

### ISSUE THREAD

**Issue by CripyIce** [simolus3/moor#515]
Hi there,
I've posted a while ago an issue where I wanted to save a json string instead of parsing it.
Now, I would like to save a parsed json so I've tried to do so with a `TypeConverter` but failed to succeed.

`client_status.dart`:
```dart
import 'dart:convert';

List<ClientStatus> clientStatusFromJson(String str) => List<ClientStatus>.from(
    json.decode(str).map((x) => ClientStatus.fromMap(x)));

String clientStatusToJson(List<ClientStatus> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toMap())));

class ClientStatus {
  final int id;
  final String name;
  final String color;
  final int ownerId;

  ClientStatus({
    this.id,
    this.name,
    this.color,
    this.ownerId,
  });

  factory ClientStatus.fromMap(Map<String, dynamic> json) => ClientStatus(
        id: json["id"] == null ? null : json["id"],
        name: json["name"] == null ? null : json["name"],
        color: json["color"] == null ? null : json["color"],
        ownerId: json["owner_id"] == null ? null : json["owner_id"],
      );

  Map<String, dynamic> toMap() => {
        "id": id == null ? null : id,
        "name": name == null ? null : name,
        "color": color == null ? null : color,
        "owner_id": ownerId == null ? null : ownerId,
      };
}
```

`client_status_converter.dart`:
```dart
import 'model/client_status.dart';
import 'package:moor/moor.dart';

class ClientStatusConverter extends TypeConverter<List<ClientStatus>, String> {
  const ClientStatusConverter();

  @override
  List<ClientStatus> mapToDart(String fromDb) {
    if (fromDb == null) {
      return null;
    }
    return clientStatusFromJson(fromDb);
  }

  @override
  String mapToSql(List<ClientStatus> value) {
    if (value == null) {
      return null;
    }

    return clientStatusToJson(value);
  }
}
```

In `database.dart` I've added this column into my table: ```TextColumn get status =>
      text().nullable().map(const ClientStatusConverter())();```
After running `flutter packages pub run build_runner build`, I'm getting an error inside `database.g.dart`:
![image](https://user-images.githubusercontent.com/26387823/79986958-7d0a5e80-84b5-11ea-8266-233ee420343b.png)

Appreciate the help.

**Comment by simolus3** [comment]
Yeah, you'd need to import `client_status.dart` into the file where you use `@UseMoor`. Generated files can't contain import statements unfortunately, so there's not much moor can do about that.

Moor should emit a warning for this, see https://github.com/simolus3/moor/issues/368. I haven't added that yet though.

**Comment by CripyIce** [comment]
@simolus3 Thanks for the fast reply!
It now compiles without any errors, but now I'm getting runtime error:
`Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<ClientStatus>' in type cast`.
Is there something wrong with how I've written my code?

**Comment by simolus3** [comment]
I couldn't find anything obvious that would cause the error. Can you post the stack trace of that type error? Does it originate in generated code?

**Comment by CripyIce** [comment]
@simolus3 This is the stack trace:
```
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<ClientStatus>' in type cast
#0      _DefaultValueSerializer.fromJson (package:moor/src/runtime/data_class.dart:125:17)
#1      new Clients.fromJson (package:testapp/db/database.g.dart:4122:26)
#2      ApiProvider.getClients.<anonymous closure> (package:testapp/remote/api_provider.dart:345:63)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#5      new List.from (dart:core-patch/array_patch.dart:54:19)
#6      ApiProvider.getClients (package:testapp/remote/api_provider.dart:345:11)
<asynchronous suspension>
#7      _CustomersListState._refreshCustomers (package:testapp/ui/customers/customers_list.dart:176:60)
#8      _CustomersListState.initState.<anonymous closure> (package:testapp/ui/customers/customers_list.dart:47:7)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/b<…>
```

This is `package:testapp/db/database.g.dart:4122:26`:
```dart
  factory Clients.fromJson(Map<String, dynamic> json,
      {ValueSerializer serializer}) {
    serializer ??= moorRuntimeOptions.defaultSerializer;
    return Clients(
      id: serializer.fromJson<int>(json['id']),
      cardId: serializer.fromJson<int>(json['card_id']),
      firstName: serializer.fromJson<String>(json['first_name']),
      lastName: serializer.fromJson<String>(json['last_name']),
      phoneNumber: serializer.fromJson<String>(json['phone_number']),
      telephone2: serializer.fromJson<String>(json['telephone_2']),
      message: serializer.fromJson<String>(json['message']),
      email: serializer.fromJson<String>(json['email']),
      company: serializer.fromJson<String>(json['company']),
      ownerId: serializer.fromJson<int>(json['owner_id']),
      commentHistory: serializer.fromJson<String>(json['comment_history']),
      professionalTitle:
          serializer.fromJson<String>(json['professional_title']),
      zipCode: serializer.fromJson<String>(json['zip_code']),
      address: serializer.fromJson<String>(json['address']),
      city: serializer.fromJson<String>(json['city']),
      birthday: serializer.fromJson<String>(json['birthday']),
      createdAt: serializer.fromJson<String>(json['created_at']),
      status: serializer.fromJson<List<ClientStatus>>(json['status']),
    );
  }
```

And this is my code from `api_provider.dart`:
```dart
  Future<ClientsResponse> getClients() async {
    try {
      Response response = await _dio.get("${BUSINESS_CARD_API_URL}leads");

      if (response.toString().contains("error")) {
        return ClientsResponse.failure(error: response.toString());
      }

      final clients =
          List<Clients>.from(response.data.map((x) => Clients.fromJson(x)));

      _database.clientsDao.insertClients(clients);

      return ClientsResponse.success(clients);
    } on DioError catch (e) {
      print("dio error: ${e.response.statusCode}");

      return ClientsResponse.failure(error: e.response.data["name"]);
    }
  }
```

**Comment by simolus3** [comment]
I see what's happening now: The problem is this line
https://github.com/simolus3/moor/blob/7fc1671bf8cd1b732da55b0495c2ee9100e0f8bb/moor/lib/src/runtime/data_class.dart#L125

Moor's default serializer doesn't support type converters since it can't know how those would affect json serialization (in general type converters are only used to map to database values). You can provide your own `ValueSerializer` with support for `List<ClientStatus>` and apply it to your entire app with `moorRuntimeOptions.defaultSerializer`.

The docs should probably warn about this.

**Comment by CripyIce** [comment]
1. Am I implementing my code in a wrong way? or this is the only way to go?
2. I have many other classes using moor database, will `moorRuntimeOptions.defaultSerializer` affect them? Let's say I would like to have more `TypeConverter` for different classes, could I do multiple `ValueSerializer`?

**Comment by simolus3** [comment]
Unfortunately this the only way to go, as type converters only affect the mapping from and to sql. If we also applied type converters to json, you would get a json string in your json: `{"status": "[{...}]"}` as that's what the converter outputs.

Using `moorRuntimeOptions` affects your entire app, yes. If you only want to use a serializer for one class only, you'd have to pass it explicitly: `Clients.fromJson(json, serializer: const MySerializer())`. In general I'd recommend to write a custom serializer for your whole app if you need to:

```dart
class MyValueSerializer extends ValueSerializer {
  const MyValueSerializer();

  @override
  T fromJson<T>(dynamic json) {
    if (T == DateTime) {
      if (json == null) {
        return null;
      } else {
        return DateTime.fromMillisecondsSinceEpoch(json as int) as T;
      }
    }

    if (T == double && json is int) {
      return json.toDouble() as T;
    }

    if (T == List<ClientStatus>) {
      return (json as list).map((element) => ClientStatus.fromMap(element)).toList();
    }

    // other cases needed for your app ...

    return json as T;
  }

  @override
  dynamic toJson<T>(T value) {
    if (value is DateTime) {
      return value.millisecondsSinceEpoch;
    }

    if (value is List<ClientStatus>) {
      return value.map((element) => element.toMap()).toList();
    }

    // other cases needed for your app

    return value;
  }
}
```
