### ISSUE TITLE
Analyzer Plugin: 'resultColumn' called on null

### ISSUE THREAD

**Issue by ResoDev** [simolus3/moor#578]
Hello, thank you for the great library!

Trying to do anything inside a moor file results in the following error being reported in VS Code. The analyzer plugin is successfully running - I checked it in analyzer diagnostics.

Errors are also not highlighted in the moor file, I see them only in the moor_generator output in the terminal.

### Versions

- Visual Studio Code v1.45.1
- Dart Code v3.10.2
- Flutter SDK v1.17.1

### Analyzer Info

The analyzer was launched using the arguments:

- C:\Flutter\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
- --client-id=VS-Code
- --client-version=3.10.2

### Exception
```
PLEASE DO NOT REPORT THIS ON dart-lang/sdk! This should be reported via https://github.com/simolus3/moor/issues/new instead. Message was Error while working on file:///D:/Reso%20Coder/SHORTENED/git_repo.moor, error NoSuchMethodError: The getter 'resultColumns' was called on null.
Receiver: null
Tried calling: resultColumns

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      CreateTableReader.extractTable (package:moor_generator/src/analyzer/moor/create_table_reader.dart:35:32)
#2      MoorParser.parseAndAnalyze (package:moor_generator/src/analyzer/moor/parser.dart:65:40)
#3      ParseMoorStep.parseFile (package:moor_generator/src/analyzer/runner/steps/parse_moor.dart:11:19)
#4      Task._parse (package:moor_generator/src/analyzer/runner/task.dart:84:31)
<asynchronous suspension>
#5      Task.runTask (package:moor_generator/src/analyzer/runner/task.dart:41:26)
#6      MoorDriver.performWork (package:moor_generator/src/backends/common/driver.dart:107:18)
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1975:24)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1898:5)
#9      new ServerPlugin (package:analyzer_plugin_fork/plugin/plugin.dart:100:29)
#10     new BaseMoorPlugin (package:moor_generator/src/backends/common/base_plugin.dart:16:47)
#11     new _MoorPlugin&BaseMoorPlugin&OutlineMixin (package:moor_generator/src/backends/plugin/plugin.dart)
#12     new _MoorPlugin&BaseMoorPlugin&OutlineMixin&FoldingMixin (package:moor_generator/src/backends/plugin/plugin.dart)
#13     new _MoorPlugin&BaseMoorPlugin&OutlineMixin&FoldingMixin&CompletionMixin (package:moor_generator/src/backends/plugin/plugin.dart)
#14     new _MoorPlugin&BaseMoorPlugin&OutlineMixin&FoldingMixin&CompletionMixin&NavigationMixin (package:moor_generator/src/backends/plugin/plugin.dart)
#15     new MoorPlugin (package:moor_generator/src/backends/plugin/plugin.dart:28:43)
#16     new MoorPlugin.forProduction (package:moor_generator/src/backends/plugin/plugin.dart:34:12)
#17     start (package:moor_generator/integrations/plugin.dart:7:34)
#18     main (file:///C:/Users/mreso/AppData/Local/.dartServer/.plugin_manager/bc0d343db770f933c8def53d1a73e1cb/analyzer_plugin/bin/plugin.dart:13:5)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

The moor file is rather simple:
```sql
CREATE TABLE git_repos (
  id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
  user INT REFERENCES users (id),
  /*WRITING HERE TRIGGERS THE EXCEPTION*/
);

CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTOINCREMENT
);
```

**Comment by Mike278** [comment]
Haven't tried it, but does the error go away if you define `users` before `git_repos`? I think the generator sorts tables by foreign key references, but maybe there's a bug there.

**Comment by simolus3** [comment]
There were two issues here: The first one was a NPE in the `sqlparser` package when extracting the schema from a column definition without a typename (e.g. `CREATE TABLE foo (bar);`). We'll now interpret `bar` as a blob columns which matches [sqlite's documentation](https://www.sqlite.org/datatype3.html#affinity_name_examples).
Then there's another NPE in `moor_generator` when the schema reader throws an exception, which I've now fixed as well.

Both problems are fixed on `develop` now - I'll try to release a new version soon.
