### ISSUE TITLE
New enum only writes 4294967296 on database

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#591]
In development mode, columns with the new enum works fine (so if the enum value is 1, 1 is recorded on the table's row).

In release mode, all enums, no matter which value, writes the int 4294967296 in the database.

**Comment by JCKodel** [comment]
```
I/flutter (19684): Moor: Sent SELECT *
I/flutter (19684):      FROM Users
I/flutter (19684):      WHERE "id" = :id with args [4HsEUe64kBVzE56xNLG17an0pov2]
E/flutter (19684): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: RangeError (length): Invalid value: Not in range 0..2, inclusive: 4294967296
E/flutter (19684): #0      _$UsersDaoMixin._rowToUser (package:meucronogramacapilar/data/daos/users_dao.g.dart:0)
E/flutter (19684): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417)
E/flutter (19684): #2      ListIterable.toList (dart:_internal/iterable.dart:221)
E/flutter (19684): #3      _MappedSelectable._mapResults (package:moor/src/runtime/query_builder/statements/query.dart:151)
E/flutter (19684): #4      _MapStream._handleData (dart:async/stream_pipe.dart:229)
E/flutter (19684): #5      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166)
E/flutter (19684): #6      _StartWithValueStream.listen.wrappedCallback (package:moor/src/utils/start_with_value_transformer.dart:37)
E/flutter (19684): #7      _rootRunUnary (dart:async/zone.dart:1192)
E/flutter (19684): #8      _CustomZone.runUnary (dart:async/zone.dart:1085)
E/flutter (19684): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987)
E/flutter (19684): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
E/flutter (19684): #11     _DelayedData.perform (dart:async/stream_impl.dart:594)
E/flutter (19684): #12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710)
E/flutter (19684): #13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670)
E/flutter (19684): #14     _rootRun (dart:async/zone.dart:1180)
E/flutter (19684): #15     _CustomZone.run (dart:async/zone.dart:1077)
E/flutter (19684): #16     _CustomZone.runGuarded (dart:async/zone.dart:979)
E/flutter (19684): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019)
E/flutter (19684): #18     _rootRun (dart:async/zone.dart:1184)
E/flutter (19684): #19     _CustomZone.run (dart:async/zone.dart:1077)
E/flutter (19684): #20     _CustomZone.runGuarded (dart:async/zone.dart:979)
E/flutter (19684): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019)
E/flutter (19684): #22     _microtaskLoop (dart:async/schedule_microtask.dart:43)
E/flutter (19684): #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52)
```

**Comment by JCKodel** [comment]
Odly, using this code, everything works (so I imagine is something internal):

```dart
enum HairCurvature {
  none,
  straight,
  wavy,
  curly,
  afro,
}

const c = EnumIndexConverter<HairCurvature>(HairCurvature.values);

print("${c.mapToSql(HairCurvature.afro)} ${c.mapToDart(4)} ${HairCurvature.values} ${HairCurvature.values.indexOf(HairCurvature.afro)}");
```

Thats prints `4 HairCurvature.afro [HairCurvature.none, HairCurvature.straight, HairCurvatur e.wavy, HairCurvature.curly, HairCurvature.afro] 4` in both debug and release mode, so I guess it is not an error on `EnumIndexConverter<T>`.

**Comment by simolus3** [comment]
Does this happen on all devices? This might be an ffi problem, can you try to run https://github.com/simolus3/moor/issues/446#issuecomment-614087976?

**Comment by JCKodel** [comment]
Yep, all devices.

Moto G 1st edition: Repro works fine, no error messages
Samsung Galaxy J4+: Also fine
Asus ZenFone: Also fine

But, due to https://github.com/simolus3/moor/issues/592, I can't use Moor anymore. Too risk.

**Comment by simolus3** [comment]
> But, due to #592, I can't use Moor anymore. Too risk.

Sorry to hear that, but it's a compiler bug I can't do too much about. You can try downgrading to `moor_ffi` version 0.5.0 and see if that works.

**Comment by simolus3** [comment]
Closing this as it sounds like a duplicate.
