### ISSUE TITLE
[moor_ffi] Error occurs while using REGEXP in select/where statement (expected two strings as parameters to regexp)

### ISSUE THREAD

**Issue by loomp** [simolus3/moor#610]
Hello,

I want to report an issue I have observed when trying to use REGEXP in the where/select statement.

Error message: `SqliteException(1): Expected two strings as parameters to regexp, SQL logic error (code 1)`

moor: "3.1.0"
moor_ffi: "0.6.0"
moor_generator: "3.1.0"

Exception is thrown while using Android simulator (x86, Android 10.0)

Code generation built successfully, with no errors.
The problem is with the only query listed below.

my code snippet (provides/rewards/objectives fields contains json with identifiers):

```
Future<List<QuestModel>> getByObjects(List<String> objects) async {
    final regex = '"' + objects.join('"|"') + '"';

    final query = select(questTable)
      ..where((table) => table.provides.regexp(regex)
          | table.rewards.regexp(regex)
          | table.objectives.regexp(regex));

    return (await query.get())
        .map((entry) => QuestModel.fromMap(entry.toJson()))
        .toList()
      ..sort((a, b) {
        var sort = (a.level ?? 0).compareTo(b.level ?? 0);

        if (sort == 0) {
          sort = a.title.toString().compareTo(b.title.toString());
        }

        return sort;
      });
  }
```

build.yaml:

```
targets:
  $default:
    builders:
      moor_generator:
        options:
          sqlite_modules:
            - moor_ffi
```

pubsec.yaml:

```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  english_words:
  url_launcher:
  sembast:
  path_provider:
  flutter_bloc:
  equatable:
  shared_preferences:
  sprintf:
  sticky_headers:
  in_app_purchase:
  flutter_focus_watcher:
  flutter_markdown:
  flutter_speed_dial:
  intl:
  moor:
  moor_ffi:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:
  pedantic:
  build_runner:
  moor_generator:
  json_serializable:
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.45.1)
[√] Connected device (1 available)

• No issues found!
```

stack trace
```
E/flutter ( 8821): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unhandled error SqliteException(1): Expected two strings as parameters to regexp, SQL logic error (code 1) occurred in bloc Instance of 'SourceBloc'.
E/flutter ( 8821): #0      PreparedStatement.select (package:moor_ffi/src/impl/prepared_statement.dart:54:7)
E/flutter ( 8821): #1      _VmDelegate.runSelect (package:moor_ffi/src/vm_database.dart:97:25)
E/flutter ( 8821): #2      _ExecutorWithQueryDelegate.runSelect.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:41:19)
E/flutter ( 8821): #3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter ( 8821): #4      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22:26)
E/flutter ( 8821): #5      _ExecutorWithQueryDelegate.runSelect (package:moor/src/runtime/executor/helpers/engines.dart:39:26)
E/flutter ( 8821): #6      LazyDatabase.runSelect (package:moor/src/utils/lazy_database.dart:64:17)
E/flutter ( 8821): #7      SimpleSelectStatement._getWithQuery.<anonymous closure> (package:moor/src/runtime/query_builder/statements/select/select.dart:40:22)
E/flutter ( 8821): #8      QueryEngine.doWhenOpened.<anonymous closure> (package:moor/src/runtime/api/query_engine.dart:98:64)
E/flutter ( 8821): #9      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 8821): #10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 8821): #11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 8821): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 8821): #13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 8821): #14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 8821): #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter ( 8821): #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter ( 8821): #17     BasicLock.synchronized (package:synchronized/src/basic_lock.dart)
E/flutter ( 8821): <asynchronous suspension>
E/flutter ( 8821): #18     DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:238:25)
E/flutter ( 8821): #19     LazyDatabase.ensureOpen.<anonymous closure> (package:moor/src/utils/lazy_database.dart:43:49)
E/flutter ( 8821): #20     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 8821): #21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 8821): #22     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 8821): #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 8821): #24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 8821): #25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 8821): #26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter ( 8821): #27     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 8821): #28     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 8821): #29     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 8821): #30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 8821): #31     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 8821): #32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 8821): 
E/flutter ( 8821): #0      Bloc.onError.<anonymous closure> (package:bloc/src/bloc.dart:146:7)
E/flutter ( 8821): #1      Bloc.onError (package:bloc/src/bloc.dart:147:6)
E/flutter ( 8821): #2      _rootRunBinary (dart:async/zone.dart:1204:38)
E/flutter ( 8821): #3      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
E/flutter ( 8821): #4      _CustomZone.runBinaryGuarded (dart:async/zone.dart:995:7)
E/flutter ( 8821): #5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
E/flutter ( 8821): #6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
E/flutter ( 8821): #7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:275:7)
E/flutter ( 8821): #8      _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:393:20)
E/flutter ( 8821): #9      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:327:15)
E/flutter ( 8821): #10     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:392:5)
E/flutter ( 8821): #11     _BroadcastStreamController._addError (dart:async/broadcast_stream_controller.dart:294:5)
E/flutter ( 8821): #12     _rootRunBinary (dart:async/zone.dart:1204:38)
E/flutter ( 8821): #13     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
E/flutter ( 8821): #14     _CustomZon
```

**Comment by loomp** [comment]
Statement looks OK: `SELECT * FROM quest_table WHERE provides REGEXP ? OR rewards REGEXP ? OR objectives REGEXP ?;`

![image](https://user-images.githubusercontent.com/59165289/83355190-23bc0780-a35e-11ea-9e91-28ddb75506a2.png)

**Comment by simolus3** [comment]
The function is implemented in Dart: https://github.com/simolus3/moor/blob/b5cc9b974d34d6227d50a0b1b21c88e91c628736/moor_ffi/lib/src/impl/moor_functions.dart#L80-L83

My guess is that any of the arguments is null (probably the column). I've changed the implementation to just return null in that case.

**Comment by loomp** [comment]
I believe that was it - some of mentioned columns are nullable indeed.
Thank you very much for your awesome work!
