### ISSUE TITLE
Reading 10000+ records results in a crash on android. 

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/moor#621]
We are reading 10000+ records with a Stream. and we are receiving this error.

No problem on iOS

The error:
https://sqlite.org/rescode.html#ioerr_gettemppath

```
E/flutter ( 6721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: "SqliteException(6410): disk I/O error, disk I/O error (code 6410)"
E/flutter ( 6721): #0      PreparedStatement.select (package:moor_ffi/src/impl/prepared_statement.dart:54:7)
E/flutter ( 6721): #1      _VmDelegate.runSelect (package:moor_ffi/src/vm_database.dart:97:25)
E/flutter ( 6721): #2      _ExecutorWithQueryDelegate.runSelect.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:43:19)
E/flutter ( 6721): #3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter ( 6721): #4      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22:26)
E/flutter ( 6721): #5      _ExecutorWithQueryDelegate.runSelect (package:moor/src/runtime/executor/helpers/engines.dart:41:26)
E/flutter ( 6721): #6      _MoorServer._runQuery (package:moor/src/runtime/isolate/server.dart:89:25)
E/flutter ( 6721): <asynchronous suspension>
E/flutter ( 6721): #7      _MoorServer._handleRequest (package:moor/src/runtime/isolate/server.dart:57:14)
E/flutter ( 6721): #8      IsolateCommunication.setRequestHandler.<anonymous closure> (package:moor/src/runtime/isolate/communication.dart:163:31)
E/flutter ( 6721): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
E/flutter ( 6721): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 6721): #11     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
E/flutter ( 6721): #12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
E/flutter ( 6721): #13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
E/flutter ( 6721): #14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 6721): #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 6721): #16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
E/flutter ( 6721): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

How can I fix this?

I found this. but how do I set this value?
https://stackoverflow.com/questions/44766917/sql-logic-error-only-when-querying-on-android

**Comment by vanlooverenkoen** [comment]
This is how I fixed my 6410 error on android. Now all my queries work
```  
Future<void> setTmpDirForAndroid() async {
    if (Platform.isAndroid) {
      try {
        final dbFolder = await getTemporaryDirectory();
        await customStatement('PRAGMA temp_store_directory="${dbFolder.path}"');
      } catch (e) {
        SibosLogger.logError(message: 'Failed to set temp dir ', error: e);
      }
    }
  }
```

**Comment by htsv** [comment]
I was able to test this as I had a table with 200k products and wrote a single query that returned about 14k products in the result. This was not possible before without temp file on Android before. 
Thanks for sharing the solution!

**Comment by Mike278** [comment]
Might be worth noting that `PRAGMA temp_store_directory` [is deprecated](https://www.sqlite.org/pragma.html#pragma_temp_store_directory). 

Maybe using memory for temp storage with [`PRAGMA temp_store=2`](https://www.sqlite.org/pragma.html#pragma_temp_store) would help.
