### ISSUE TITLE
Handle unhandled exceptions from isolate.

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#652]
Hi @simolus3, how can we handle the exceptions from isolate. I tried `into(myTable).insert(data).catchError((e) {});` but it doesn't catches the error. Also, after one unhandled exception from isolate, moor stops working.

**Comment by simolus3** [comment]
Thanks for the report. I added a test to ensure errors are reported when they happen on another isolate (b4aeacdba3e5fafcd6af09c6c5d1db33cc2e61dc). However, that works without any code changes, so I need more information to reproduce this.

**Comment by SahajRana** [comment]
Sure, I received this error
```
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\runtime\dart_isolate.cc(875)] Unhandled exception:
SqliteException: UNIQUE constraint failed: comp_prop_table.prop_type_id, comp_prop_table.comp_id, constraint failed
#0      PreparedStatement.execute (package:moor_ffi/src/impl/prepared_statement.dart:85:7)
#1      _VmDelegate._runWithArgs (package:moor_ffi/src/vm_database.dart:64:12)
#2      _VmDelegate.runInsert (package:moor_ffi/src/vm_database.dart:76:11)
#3      _ExecutorWithQueryDelegate.runInsert.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:69:19)
#4      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
#5      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22:26)
#6      _ExecutorWithQueryDelegate.runInsert (package:moor/src/runtime/executor/helpers/engines.dart:67:12)
#7      _MoorServer._runQuery (package:moor/src/runtime/isolate/server.dart:91:25)
<asynchronous suspension>
#8      _MoorServer._handleRequest (package:moor/src/runtime/isolate/server.dart:68:14)
#9      IsolateCommunication.setRequestHandler.<anonymous closure> (package:moor/src/runtime/isolate/communication.dart:138:31)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#13     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
...
```
for this.
```
return into(compPropTable).insert(data).catchError((e) {
    print("error> " + e.toString());
});
```
```
moor: ^2.2.0
moor_ffi: ^0.3.1
```

**Comment by simolus3** [comment]
Do you have a full repro for this? If you post the definition of the tables involved (feel free to obfuscate them etc.) it would be much easier for me to see what's going on here.

I also noticed that you're using old `moor` and `moor_ffi` versions. Have you tried upgrading to `moor: ^3.1.0` and `moor_ffi: ^0.6.0`? You'll also need to use `moor_generator: ^3.1.0`. There have been many isolate enhancements in those updates, so it's likely that the problem has already been fixed.

**Comment by simolus3** [comment]
Let me know if you still have this problem (and more information to reproduce this). From my perspective, it appears to be working, so I'll close this issue. But let me know if this still happens for you, I'll re-open this then.
