### ISSUE TITLE
Fail batch on insertAllOnConflictUpdate

### ISSUE THREAD

**Issue by MuhammadDicky** [simolus3/moor#805]
I have facing error when try to insert or update on conflict inside batch, im not sure what is wrong.

**method**:
```
Future<void> addBatch(List<Insertable<D>> entityList) async {
    await batch((b) {
      b.insertAllOnConflictUpdate(table, entityList);
    });
  }
```

**implement**:
```
// Companion DataClass
final List<EpisodesCompanion> episodeDataList = [];

      for (Map<String, dynamic> episode
          in listDt) {
        final EpisodeProvider episodeProvider =
            _episodeListSL.add(EpisodeProvider.fromJson(episode));

        episodeDataList.add(episodeProvider.episode.toCompanion(true));
      }

      // Save episode data to database
      await _appDb.episodeDao.addBatch(episodeDataList);
```

**Log**:
```
I/flutter ( 9972): Moor: Executing BatchedStatements([INSERT INTO episodes (episode_id, type, explicit, title, duration, site_url, image_original_url, image_url, published_at, author_id, show_id, download_enabled, waveform_url, download_url, playback_url, have_detail, current_position, is_downloaded, is_finnish, is_current_play, create_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(episode_id) DO UPDATE SET episode_id = ?, type = ?, explicit = ?, title = ?, duration = ?, site_url = ?, image_original_url = ?, image_url = ?, published_at = ?, author_id = ?, show_id = ?, download_enabled = ?, waveform_url = ?, download_url = ?, playback_url = ?, have_detail = ?, current_position = ?, is_downloaded = ?, is_finnish = ?, is_current_play = ?], [ArgumentsForBatchedStatement(0, [40701389, RECORDED, 0, Kajian Online Kitabul Ilmi - Bab III Beberapa Kesalahan Yang Harus Dijauhi Oleh Penuntut Ilmu #9 (Ustadz Hilal), 3166220, https://www.spreaker.com/episode/40701389, https://d3wo5wojvuv7l.cloudfront.
E/SQLiteLog( 9972): (1) near "ON": syntax error
E/flutter ( 9972): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1 SQLITE_ERROR): , while compiling: INSERT INTO episodes (episode_id, type, explicit, title, duration, site_url, image_original_url, image_url, published_at, author_id, show_id, download_enabled, waveform_url, download_url, playback_url, have_detail, current_position, is_downloaded, is_finnish, is_current_play, create_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(episode_id) DO UPDATE SET episode_id = ?, type = ?, explicit = ?, title = ?, duration = ?, site_url = ?, image_original_url = ?, image_url = ?, published_at = ?, author_id = ?, show_id = ?, download_enabled = ?, waveform_url = ?, download_url = ?, playback_url = ?, have_detail = ?, current_position = ?, is_downloaded = ?, is_finnish = ?, is_current_play = ?) sql 'INSERT INTO episodes (episode_id, type, explicit, title, duration, site_url, image_original_url, image_url, published_at, author_id, show_id, download_enabled, waveform_url, download_url, playback_url, have_detail, current_position, is_downloaded, is_finnish, is_current_play, create_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(episode_id) DO UPDATE SET episode_id = ?, type = ?, explicit = ?, title = ?, duration = ?, site_url = ?, image_original_url = ?, image_url = ?, published_at = ?, author_id = ?, show_id = ?, download_enabled = ?, waveform_url = ?, download_url = ?, playback_url = ?, have_detail = ?, current_position = ?, is_downloaded = ?, is_finnish = ?, is_current_play = ?' args [40701389, RECORDED, 0, Kajian Online Kitabul Ilmi - Bab III Beberapa Kesalahan Yang Harus Dijauhi Oleh Penuntut Ilmu #9 (Ustadz Hilal), 3166220, https://www.spreaker.com/episode/40701389, https://d3wo5wojvuv7l.cloudfront.net/images.spreaker.com/original/a381de33f7cc270a94d702f3a8fea937.jpg, https://d3wo5wojvuv7l.cloudfront.net/t_square_limited_160/images.spreaker.com/original/a381de33f7cc270a94d702f3a8fea937.jpg, 2020-09-04 10:35:50, 9187819, 4304795, 1, https://d3770qakewhkht.cloudfront.net/episode_40701389.gz.json?v=X62jSR, https://api.spreaker.com/v2/episodes/40701389/download.mp3, https://api.spreaker.com/v2/episodes/40701389/play.mp3, 0, 0.0, 0, 0, 0, 2020-09-04 10:39:46, 40701389, RECORDED, 0, Kajian Online Kitabul Ilmi - Bab III Beberapa Kesalahan Yang Harus Dijauhi Oleh Penuntut Ilmu #9 (Ustadz Hilal), 3166220, https://www.spreaker.com/episode/40701389, https://d3wo5wojvuv7l.cloudfront.net/images.spreaker.com/original/a381de33f7cc270a94d702f3a8fea937.jpg, https://d3wo5wojvuv7l.cloudfront.net/t_square_limited_160/images.spreaker.com/original/a381de33f7cc270a94d702f3a8fea937.jpg, 2020-09-04 10:35:50, 9187819, 4304795, 1, https://d3770qakewhkht.cloudfront.net/episode_40701389.gz.json?v=X62jSR, https://api.spreaker.com/v2/episodes/40701389/download.mp3, https://api.spreaker.com/v2/episodes/40701389/play.mp3, 0, 0.0, 0, 0, 0]}
E/flutter ( 9972): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 9972): <asynchronous suspension>
E/flutter ( 9972): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter ( 9972): #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite_common/src/database_mixin.dart:208:15)
E/flutter ( 9972): #3      SqfliteDatabaseMixin.txnApplyBatch.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:429:17)
E/flutter ( 9972): #4      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:312:26)
E/flutter ( 9972): #5      SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite_common/src/database_mixin.dart:345:7)
E/flutter ( 9972): #6      SqfliteDatabaseMixin.txnApplyBatch (package:sqflite_common/src/database_mixin.dart:419:12)
E/flutter ( 9972): #7      SqfliteTransactionBatch.commit (package:sqflite_common/src/batch.dart:149:33)
E/flutter ( 9972): #8      _SqfliteExecutor.runBatched (package:moor_flutter/moor_flutter.dart:130:17)
E/flutter ( 9972): #9      _ExecutorWithQueryDelegate.runBatched.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:90:19)
E/flutter ( 9972): #10     _ExecutorWithQueryDelegate._synchronized (p
```

**Comment by MuhammadDicky** [comment]
Sorry, just fix by using `package:moor/ffi.dart`
