### ISSUE TITLE
Inner Join returning - ambiguous column name

### ISSUE THREAD

**Issue by jesseframework** [simolus3/moor#847]
This is not any issue this is me begging help.
can someone help me with inner join query.

This is returning null for me but i can figure out why
```
Stream<List<JourneyPlanData>> watchAllJourneyPlanByUserandAddress(
      String userName) {
    return customSelect(
      'SELECT'
      ' j.customer_name,'
      ' j.company_name,'
      ' a.address_line1 '
      ' FROM '
      ' journey_plan j '
      ' left outer join address a on j.customer_id = a.customer_id '
      ' WHERE '
      ' j.is_deleted = 0 '
      'and j.assign_to = "$userName" ',
      readsFrom: {
        db.journeyPlan
      }, // used for the stream: the stream will update when either table changes
    ).watch().map((rows) {
      return rows.map((row) => JourneyPlanData.fromData(row.data, db)).toList();
    });
  }
```

also if used this

``` 
Stream<List<JourneyWithAddress>> watchAllCarts() {    
    final jpStream = select(db.journeyPlan).watch();
    return jpStream.switchMap((jplans) {     
      final setUserJPlant = {for (var jplan in jplans) jplan.customerId: jplan};
      final userJplan = setUserJPlant.keys;     
      final entryQuery = select(db.address).join(
        [
          innerJoin(
            db.address,
            db.journeyPlan.customerId.equalsExp(db.address.customerId),
          )
        ],
      );
      return entryQuery.watch().map((rows) {       
        final jplaAddress = <String, List<Addres>>{};      
        for (var row in rows) {
          final allJplanAddress = row.readTable(db.address);
          final id = row.readTable(db.journeyPlan).customerId;

          jplaAddress.putIfAbsent(id, () => []).add(allJplanAddress);
        }

        return [
          for (var id in userJplan)
            JourneyWithAddress(jplaAddress[id], setUserJPlant[id] ?? []),
        ];
      });
    });
  }
```

Am getting
Exception has occurred.
```
MoorWrappedException (SqliteException(1): ambiguous column name: address.tenant_id, SQL logic error (code 1) at 
#0      Database.prepare (package:moor_ffi/src/impl/database.dart:155:7)
#1      _VmDelegate.runSelect (package:moor_ffi/src/vm_database.dart:96:22)
#2      _ExecutorWithQueryDelegate.runSelect.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:41:19)
#3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
#4      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22:26)
#5      _ExecutorWithQueryDelegate.runSelect (package:moor/src/runtime/executor/helpers/engines.dart:39:26)
#6      JoinedSelectStatement._getWithQuery.<anonymous closure> (package:moor/src/runtime/query_builder/statements/select/select_with_join.dart:193:24)
#7      QueryEngine.doWhenOpened.<anonymous closure> (package:moor/src/runtime/api/query_engine.dart:98:64)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     BasicLock.synchronized (package:synchronized/src/basic_lock.dart)
<asynchronous suspension>
#17     DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:238:25)
#18     QueryEngine.doWhenOpened (package:moor/src/runtime/api/query_engine.dart:98:21)
#19     JoinedSelectStatement._getWithQuery (package:moor/src/runtime/query_builder/statements/select/select_with_join.dart:191:40)
#20     JoinedSelectStatement.watch.<anonymous closure> (package:moor/src/runtime/query_builder/statements/select/select_with_join.dart:177:24)
#21     QueryStream.fetchAndEmitData (package:moor/src/runtime/executor/stream_queries.dart:248:38)
#22     QueryStream._onListen (package:moor/src/runtime/executor/stream_queries.dart:219:7)
#23     _runGuarded (dart:async/stream_controller.dart:847:24)
#24     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#25     _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
#26     _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
#27     _StartWithValueStream.listen (package:moor/src/utils/start_with_value_transformer.dart:40:33)
#28     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
#29     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
#30     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
#31     SwitchMapStreamTransformer._buildTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/transformers/switch_map.dart:55:55)
#32     _StartWithValueStream.listen.wrappedCallback (package:moor/src/utils/start_with_value_transformer.dart:37:15)
#33     _rootRunUnary (dart:async/zone.dart:1198:47)
#34     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#37     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#38     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#39     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#40     _rootRun (dart:async/zone.dart:1182:47)
#41     _CustomZone.run (dart:async/zone.dart:1093:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#44     _rootRun (dart:async/zone.dart:1190:13)
#45     _CustomZone.run (dart:async/zone.dart:1093:19)
#46     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#47     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

Moor detected a possible cause for this: This query contained the table address more than once. Is this a typo? 
If you need a join that includes the same table more than once, you need to alias() at least one table. See https://moor.simonbinder.eu/queries/joins#aliases for an example.)
```

but i dont where in the this method to add alias in this method. My table have same field name as you can see in the first attempt up top.If i used this method i would like to know how to specified the field name.

**Comment by simolus3** [comment]
Thanks for opening an issue, I'm happy to help. Regarding your first query: You have a potential [SQL Injection](https://en.wikipedia.org/wiki/SQL_injection) vulnerability there, since the string is inserted into the sql (think about what could happen [if `userName` contained a `"`](https://xkcd.com/327/)). Also, a double quoted string in SQL usually refers to an identifier which might cause other problems.
You can fix this by replacing the last lines with:
```
      'and j.assign_to = ? ',
      readsFrom: {
        db.journeyPlan
      },
      variables: [Variable.withString(userName)]
```

That alone might fix your problem. If not - I'm happy to take another look. If you're writing raw sql queries I also recommend to take a look at [compiled queries](https://moor.simonbinder.eu/docs/using-sql/custom_queries/). They're immune to SQL injections and can spot most errors at build time.

In your second example, your join looks a bit off: Your main select works on `address` but then you also join the `address` table again. Instead, this should work:

```
      final entryQuery = select(db.address).join(
        [
          innerJoin(
            db.journeyPlan,
            db.journeyPlan.customerId.equalsExp(db.address.customerId),
          )
        ],
      );
```

**Comment by jesseframework** [comment]
Thank you very much.
It now working

**Comment by jesseframework** [comment]
Hello,
I have one more question.
How do moor know which parameter to assign and how to assign parameter if i used this ? with multiple parameter.
  'and j.assign_to = ? ',
      readsFrom: {
        db.journeyPlan
      },
      variables: [Variable.withString(userName)]

**Comment by simolus3** [comment]
By default, parameters are bound to the `?` in the order in which they appear in SQL. So if you have `WHERE id = ? AND j.assign_to = ?`, the first variable would bind the first `?` and so on.

You can also make this explicit by using explicit indices: `WHERE id = ?1 AND j.assign_to = ?2`.
