### ISSUE TITLE
DateTime in moor files

### ISSUE THREAD

**Issue by glenfordwilliams** [simolus3/moor#879]
I have this table definition in a moor file

```
CREATE TABLE IF NOT EXISTS items (
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	unit_id INTEGER DEFAULT NULL,
	name VARCHAR DEFAULT NULL
)as Item;
```
I have a stream open listening for changes when a write is done, so immediately after writing  i get 
the error below.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'String' is not a subtype of type 'int' in type cast
#0      DateTimeType.mapFromDatabaseResponse
package:moor/…/types/sql_types.dart:110
#1      new Item.fromData
package:inventory/database/database.g.dart:905
#2      Items.map
package:inventory/database/database.g.dart:1144
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#5      new List.from (dart:core-patch/array_patch.dart:38:29)
#6      new List.of (dart:core-patch/array_patch.dart:68:17)
#7      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#8      SimpleSelectStatement._getWithQuery
package:moor/…/select/select.dart:42
<asynchronous suspension>
#9      SimpleSelectStatement.watch.<anonymous closure>
package:moor/…/select/select.dart:113
#10     QueryStream.fetchAndEmitData
package:moor/…/executor/stream_queries.dart:248
#11     QueryStream._onListen.<anonymous closure>
package:moor/…/executor/stream_queries.dart:225
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#17     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
#18     _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
#19     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
```
I had it  properly working before  completely moving to moor files in dart code. So how can i get the datetime serialization to work?

**Comment by simolus3** [comment]
Can you try to manually select the table and see what string values might be included in `created_at`? Moor should definitely make that an int column by default.

**Comment by simolus3** [comment]
Actually, did you use the approach from #871 in Dart? In that case you would have to use

```sql
import 'your_converter.dart'

CREATE TABLE IF NOT EXISTS items (
	created_at TEXT NOT NULL MAPPED BY `const FormattedDateTimes()`, 
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	unit_id INTEGER DEFAULT NULL,
	name VARCHAR DEFAULT NULL
)as Item;
```

Unfortunately there's no `clientDefault()` equivalent for moor files, so you'd have to manually use `copyWith` on an insert to insert the current date.

**Comment by glenfordwilliams** [comment]
`response` here is "2020-10-18 18:22:18"
```
/// Maps [DateTime] values from and to sql
class DateTimeType extends SqlType<DateTime> {
  /// Constant constructor used by the type system
  const DateTimeType();

  @override
  DateTime mapFromDatabaseResponse(dynamic response) {
    if (response == null) return null;

    final unixSeconds = response as int;

    return DateTime.fromMillisecondsSinceEpoch(unixSeconds * 1000);
  }```

**Comment by simolus3** [comment]
Did you see my comment? We commented at roughly the same time. If you used a type converter to store dates as string, you'll also need to apply that converter in your moor file.

**Comment by glenfordwilliams** [comment]
Sorry for the late reply, i ended up using a combination of a custom type converter and triggers to get things working

```
-- items definition
CREATE TABLE IF NOT EXISTS items (
	created_at TEXT MAPPED BY `const FormattedDateTimes()`,
	updated_at TEXT MAPPED BY `const FormattedDateTimes()`,
	deleted_at TEXT MAPPED BY `const FormattedDateTimes()`,

	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	unit_id INTEGER DEFAULT NULL,
	name TEXT DEFAULT NULL,
	description TEXT DEFAULT NULL
)as Item;


CREATE TRIGGER IF NOT EXISTS items_create_Trigger
AFTER INSERT ON items
BEGIN
   UPDATE items SET created_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS items_update_Trigger
AFTER INSERT ON items
BEGIN
   UPDATE items SET updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW') WHERE id = NEW.id;
END;
```

**Comment by simolus3** [comment]
Cool idea!
