### ISSUE TITLE
Strings can't be mapped to sql literals yet during open

### ISSUE THREAD

**Issue by GregorySech** [simolus3/moor#88]
I'm trying to use a migration to populate the database on creation. 
Following the guide I've overridden the migration getter

```
@override
  MigrationStrategy get migration {
    return MigrationStrategy(
      beforeOpen: (engine, details) async {
        if (details.wasCreated) {
          await into(categories).insert(CategoriesCompanion(
              title: Value('Downloaded'), modifiable: Value(false)));
          await into(savedSearches).insert(
              SavedSearchesCompanion(tags: Value(''), personal: Value(false)));
        }
      },
    );
  }
```
I keep getting the following error and I have no idea how to fix it as there is no reference to my project classes. 

```
I/flutter (28988): error UnimplementedError: Strings can't be mapped to sql literals yet during open, closing...
E/flutter (28988): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: UnimplementedError: Strings can't be mapped to sql literals yet
E/flutter (28988): #0      StringType.mapToSqlConstant (package:moor/src/types/sql_types.dart:51:5)
E/flutter (28988): #1      Constant.writeInto (package:moor/src/runtime/expressions/variables.dart:78:31)
E/flutter (28988): #2      GeneratedColumn.writeColumnDefinition (package:moor/src/runtime/structure/columns.dart:59:22)
E/flutter (28988): #3      Migrator.createTable (package:moor/src/runtime/migration.dart:91:14)
E/flutter (28988): <asynchronous suspension>
E/flutter (28988): #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
E/flutter (28988): #5      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter (28988): #6      Future.wait (dart:async/future.dart:393:26)
E/flutter (28988): #7      Migrator.createAllTables (package:moor/src/runtime/migration.dart:70:19)
E/flutter (28988): #8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
E/flutter (28988): #9      Migrator.createAllTables (package:moor/src/runtime/migration.dart:69:31)
E/flutter (28988): #10     _defaultOnCreate (package:moor/src/runtime/migration.dart:22:48)
E/flutter (28988): #11     GeneratedDatabase.handleDatabaseCreation (package:moor/src/runtime/database.dart:297:31)
E/flutter (28988): #12     FlutterQueryExecutor._openDatabase.<anonymous closure> (package:moor_flutter/moor_flutter.dart:131:27)
E/flutter (28988): #13     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.doOpen.<anonymous closure> (package:sqflite/src/database_mixin.dart:661:29)
E/flutter (28988): #14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter (28988): #15     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (28988): #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (28988): #17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (28988): #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (28988): #19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (28988): #20     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (28988): #21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (28988): #22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter (28988): #23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter (28988): #24     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.getVersion (package:sqflite/src/database_mixin.dart)
E/flutter (28988): #25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter (28988): #26     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (28988): #27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (28988): #28     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (28988): #29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (28988): #30     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (28988): #31     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (28988): #32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (28988): #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter (28988): #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter (28988): #35     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart)
E/flutter (28988): #36     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter (28988): #37     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (28988): #38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (28988): #39     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (28988): #40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (28988): #41     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (28988): #42     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (28988): #43     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (28988): #44     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter (28988): #45     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter (28988): #46     _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite/src/database_mixin.dart)
E/flutter (28988): #47     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter (28988): #48     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (28988): #49     _Cus
```
Adding the onCreate with createAllTables gets a similar error referencing it.

**Comment by simolus3** [comment]
Thanks for taking the time to file an issue. You still need the `onCreate` with the `createAllTables` statement, otherwise the tables won't be created. That's unrelated to the real problem here though.

I reckon you have a `Constant(string)` somewhere in your table (perhaps as a default value somewhere)? Moor doesn't write that (yet) because we're writing constants directly to sql (instead of preparing a statement and binding the value, as we do for variables). That means we have to be very careful with sql injections, and the approach so far was to forbid that...

That said, we'll have a new (internal) database backend api that should allow us to solve that problem without worrying about sql injections. I'll try to make moor support string literals in the next version, it shouldn't be to much work.

**Comment by GregorySech** [comment]
Thanks, I've removed all the defaults values and now it works.

**Comment by simolus3** [comment]
Right. Moor will be able to handle default strings in the next version, but I'm afraid removing string defaults is the only workaround until then.
