### ISSUE TITLE
The getter 'definingUnit' was called on null (moor_generator:moor_generator)

### ISSUE THREAD

**Issue by AlexanderDecode** [simolus3/moor#905]
When I run `flutter packages pub run build_runner build` the following error assocaited to the `moor_generator:moor_generator` occurs and results in a infinity loop where the action never completes:

```
> flutter packages pub run build_runner build
[INFO] Generating build script...
...
[SEVERE] moor_generator:moor_generator on lib/data/{MY_DAO_FILE}.dart:
NoSuchMethodError: The getter 'definingUnit' was called on null.
Receiver: null
Tried calling: definingUnit
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LinkedElementFactory.isLibraryUri (package:analyzer/src/summary2/linked_element_factory.dart:133:28)
#2      LibraryContext.isLibraryUri (package:analyzer/src/dart/analysis/library_context.dart:97:27)
#3      LibraryAnalyzer._isLibrarySource (package:analyzer/src/dart/analysis/library_analyzer.dart:522:25)
#4      LibraryAnalyzer._resolveDirectives (package:analyzer/src/dart/analysis/library_analyzer.dart:562:36)
#5      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:136:5)
#6      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:12)
#7      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1317:63)
#8      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#9      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1294:20)
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1247:14)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZoned (dart:async/zone.dart:1550:10)
#15     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#16     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1246:40)
#17     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1372:41)
#18     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:979:20)
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1936:5)
#21     analysisDriver (package:build_resolvers/src/analysis_driver.dart:62:13)
#22     AnalyzerResolvers._ensureInitialized.<anonymous closure> (package:build_resolvers/src/resolver.dart:306:26)
<asynchronous suspension>
#23     AnalyzerResolvers._ensureInitialized.<anonymous closure> (package:build_resolvers/src/resolver.dart)
#24     AnalyzerResolvers._ensureInitialized (package:build_resolvers/src/resolver.dart:309:6)
#25     AnalyzerResolvers.get (package:build_resolvers/src/resolver.dart:314:11)
#26     PerformanceTrackingResolvers.get.<anonymous closure> (package:build_runner_core/src/performance_tracking/performance_tracking_resolvers.dart:19:58)
#27     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#28     PerformanceTrackingResolvers.get (package:build_runner_core/src/performance_tracking/performance_tracking_resolvers.dart:19:16)
#29     BuildStepImpl.resolver (package:build/src/builder/build_step_impl.dart:74:54)
#30     _Builder.build (package:source_gen/src/builder.dart:72:32)
#31     MoorSharedPartBuilder.build (package:moor_generator/src/backends/build/moor_builder.dart:89:18)
<asynchronous suspension>
#32     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#33     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#34     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#35     Future.wait (dart:async/future.dart:406:26)
#36     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#37     _rootRun (dart:async/zone.dart:1190:13)
#38     _CustomZone.run (dart:async/zone.dart:1093:19)
#39     _runZoned (dart:async/zone.dart:1630:10)
#40     runZonedGuarded (dart:async/zone.dart:1618:12)
#41     runZoned (dart:async/zone.dart:1547:12)
#42     scopeLogAsync (package:build/src/builder/logging.dart:26:3)
#43     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#44     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:485:19)
#45     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#46     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:483:23)
<asynchronous suspension>
#47     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#48     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#49     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:440:22)
#50     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#51     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:436:17)
#52     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)
#53     MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#54     Future.wait (dart:async/future.dart:406:26)
#55     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)
#56     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
#57     _rootRunUnary (dart:async/zone.dart:1198:47)
#58     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#59     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#60     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#61     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#62     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#63     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#64     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#65     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#66     _rootRunUnary (dart:async/zone.dart:1198:47)
#67     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#68     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#69     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#70     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#71     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#72     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
#73     _rootRunUnary (dart:async/zone.dart:1198:47)
#74     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#75     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#76     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#77     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#78     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#79     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#80     _rootRun (dart:async/zone.dart:1190:13)
#81     _CustomZone.run (dart:async/zone.dart:1093:19)
#82     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#83     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#84     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#85     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#86     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#87     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
-- After that the code just get stuck in a loop and need to terminate the job:
[INFO] 33.4s elapsed, 2/15 actions completed.
...
[INFO]  1m 58s elapsed, 2/15 actions completed.
```
**Temporary Fix:**
This squence resolve the issue temporarily until it unexpectedly reverts back to not working as above when I have called `flutter packages pub run build_runner build` an seemingly random amount of times.
```
> flutter clean
> flutter pub get
> flutter packages pub run build_runner build --delete-conflicting-outputs
// Output: Going through each action one by one as expected until it gets completed with confirmation message:
[INFO] Succeeded after 14.4s with 12 outputs (56 actions)
```

**pubspec.yaml**
```
environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.2.0
  path_provider:
  path:
  meta: ^1.1.6
  cupertino_icons: ^1.0.0
  
dev_dependencies:
  moor_flutter: ^3.1.0
  flutter_test:
    sdk: flutter
  moor_generator: ^3.4.0
  build_runner:
  test: ^1.15.4
  
flutter:
  uses-material-design: true
```

**Comment by simolus3** [comment]
Thanks for the report. This looks like a bug in the `analyzer` package to me, but it's hard to say without seeing the code it fails for. Can you share code that reproduces this?

**Comment by AlexanderDecode** [comment]
Yes, found from another [thread](https://github.com/google/json_serializable.dart/issues/738#issuecomment-722316727) the solution and it was indeed a `analyzer` package issue. By reverting to version `0.40.5` solved this issue.

```
dependencies:
  analyzer: 0.40.5
```
