### ISSUE TITLE
Unhandled Exception: "\"NoSuchMethodError: The method 'beforeOpen' was called on null.

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#929]
Hi @simolus3, I'm receiving this error,

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: "\"NoSuchMethodError: The method 'beforeOpen' was called on null.\\nReceiver: null\\nTried calling: beforeOpen(Instance of '_IsolateQueryExecutor', Instance of 'OpeningDetails')\""
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _MoorClient._handleRequest (package:moor/src/runtime/isolate/client.dart:38:27)
#2      IsolateCommunication.setRequestHandler.<anonymous closure> (package:moor/src/runtime/isolate/communication.dart:163:31)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#7      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#10     _rootRun (dart:async/zone.dart:1182:47)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

I'm using isolates in main thread using this,

```
  Future<bool> initDBForFile() async {
    if(tempFilePath==null||tempBlupFilePath!=keyResolver.currentFilePath) {
      tempFilePath=keyResolver.currentFilePath;
      
      MoorIsolate isolate = await createMoorIsolateOnMainThread(keyResolver.currentFilePath);
      moor.DatabaseConnection connection = await isolate.connect();
      connection = await isolate.connect();
      saveDatabase = SaveDatabase.connect(connection);
    
    }
    return true;
  }
```

Below is the code provided in the  Moor Documentation.
```
Future<MoorIsolate> createMoorIsolateOnMainThread(String filePath) async {
  final receivePort = ReceivePort();

  await Isolate.spawn(
    _startBackground,
    _IsolateStartRequest(receivePort.sendPort, filePath),
  );

  // _startBackground will send the MoorIsolate to this ReceivePort
  return (await receivePort.first as MoorIsolate);
}

void _startBackground(_IsolateStartRequest request) {
  final executor = VmDatabase(File(request.targetPath),logStatements: false);
  final moorIsolate = MoorIsolate.inCurrent(
        () => DatabaseConnection.fromExecutor(executor),
  );
  request.sendMoorIsolate.send(moorIsolate);
}
class _IsolateStartRequest {
  final SendPort sendMoorIsolate;
  final String targetPath;

  _IsolateStartRequest(this.sendMoorIsolate, this.targetPath);
}
```

and finally

```
@override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: initDBForFile(),
        builder: (context, snapshot){
          if(snapshot.hasData&&snapshot.data){
            return mainWidget();
          }else{
            return SizedBox();
          }
        }
    );
  }
```

**Comment by simolus3** [comment]
This can happen if the background isolate is somehow opened before you open your `SaveDatabase`, but I've never seen that before. Can you enable the `isolateDebugLog` parameter on `MoorIsolate.connect` and post the logs?

**Comment by SahajRana** [comment]
I have two DB's. One opens in `Void main(){}` using the regular Isolate way and the other is the above mentioned one where the DB file can be changed based on requirements in the main thread.

**Comment by SahajRana** [comment]
Below are the logs for 2nd one DB in the Main thread.

```
flutter: [OUT]: request (id = 0): _NoArgsRequest.getTypeSystem
flutter: [IN]: response (id = 0): Instance of 'SqlTypeSystem'
flutter: saveDatabase>> Instance of 'SaveDatabase' >> 9
flutter: [OUT]: request (id = 1): EnsureOpen(9, null)
flutter: [IN]: error response (id = 1): "\"NoSuchMethodError: The method 'beforeOpen' was called on null.\\nReceiver: null\\nTried calling: beforeOpen(Instance of '_IsolateQueryExecutor', Instance of 'OpeningDetails')\"" at #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _MoorClient._handleRequest (package:moor/src/runtime/isolate/client.dart:38:27)
#2      IsolateCommunication.setRequestHandler.<anonymous closure> (package:moor/src/runtime/isolate/communication.dart:163:31)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#7      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#10     _rootRun (dart:async/zone.dart:1182:47)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by SahajRana** [comment]
@simolus3, I have resolved it with the help of your hint.

```
  Future<bool> initDBForFile() async {
    if(tempFilePath==null||tempBlupFilePath!=keyResolver.currentFilePath) {
      tempFilePath=keyResolver.currentFilePath;
      
      MoorIsolate isolate = await createMoorIsolateOnMainThread(keyResolver.currentFilePath);
      moor.DatabaseConnection connection = await isolate.connect();   <----
      connection = await isolate.connect();                                               <----
      saveDatabase = SaveDatabase.connect(connection);
    
    }
    return true;
  }
```
I had written the above statement two times due to some unknown reason. After removing one, it works!
