### ISSUE TITLE
Closing a database cause error in isolates.

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#931]
Hi @simolus3, I'm trying to close `await saveDatabase.close();` which is part of isolates.

**The problem is that I need to close SaveDatabase & open SaveDatabase again but with a different moorfile.**

So, if I close the DB. I receive this error.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: Bad state: Tried to send request (id = 219): EnsureOpen(9, null) over isolate channel, but the connection was closed!
#0      IsolateCommunication._send (package:moor/src/runtime/isolate/communication.dart:133:7)
#1      IsolateCommunication.request (package:moor/src/runtime/isolate/communication.dart:127:5)
#2      _IsolateQueryExecutor.ensureOpen (package:moor/src/runtime/isolate/client.dart:111:10)
#3      QueryEngine.doWhenOpened (package:moor/src/runtime/api/query_engine.dart:98:21)
#4      SimpleSelectStatement._getWithQuery (package:moor/src/runtime/query_builder/statements/select/select.dart:39:40)
#5      SimpleSelectStatement.get (package:moor/src/runtime/query_builder/statements/select/select.dart:35:12)
#6      InternalDatabase.getAllInternalPropTypeTables (package:ide/business_logic/data/moor_database.dart:87:114)
#7      InternalDBLogic.checkAndUpdateInternalDBForUserProfile (package:ide/business_logic/data/moor_db_internal_logic.dart:73:30)
#8      HomePageState.initWithInternalDB (package:ide/pages/home_page.dart:914:21)
#9      HomePageState.getChildWidget (package:ide/pages/home_page.dart:1061:5)
#10     HomePageState.mainWidget.<anonymous closure>.<anonymous closure> (package:ide/pages/home_page.dart:257:45)
```

and If I do not close it. It shows `multiple DB opened & race-condition error`.

I have tried all ways to deal with it, namely:

```
        await saveDatabase.close();
        saveDatabase = null;
        //await connection.executor.close();
        //await isolate.shutdownAll();
```
But I couldn't find a proper way to close a DB safely from isolates and then reopen again with a different moor-file.

**Comment by simolus3** [comment]
If you want to use a different database file, you'll need to close the `saveDatabase` _and_ shutdown the isolate. After that, you can spawn a new isolate pointing to a different file and connect to that. In your case, it sounds like you're trying to connect to re-use the same database after you closed it.

**Comment by SahajRana** [comment]
My approach is like this

```
      isolate = await createMoorIsolateOnMainThread("Myfile0.sqlite");
      moor.DatabaseConnection connection = await isolate.connect();
      saveDatabase = SaveDatabase.connect(connection);
      
      //Later while opening another file.

      saveDatabase.close();
      isolate.shutdownAll();

      isolate = await createMoorIsolateOnMainThread("Myfile1.sqlite");
      moor.DatabaseConnection connection = await isolate.connect();
      saveDatabase = SaveDatabase.connect(connection);
```
This cause above mentioned error.

Could you help me to understand what am I missing in this?

**Comment by simolus3** [comment]
That code looks correct to me, but I'd `await` both `saveDatabase.close()` and `isolate.shutdownAll()`.

**Comment by DennisMuchiri** [comment]
@simolus3 inserting in the main thread works.
