### ISSUE TITLE
Quoting in custom statements

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#940]
I have a problem, discovered during a migration for which I have a successful migration test.

The migration uses a statement like this:
```dart
await db.customStatement('DELETE FROM foo WHERE type = "bar"');
``` 
The migration test runs successful. This query fails on Android but works on iOS.

Changing the query quoting to the following works on both OS:
```dart
await db.customStatement("DELETE FROM foo WHERE type = 'bar'");
``` 

I am wondering what is causing this and if it can not be prevented, if moor can somehow warn the developer when the query runs so that i can be detected in test cases.

**Comment by North101** [comment]
I'm not sure about SQLite but SQL typically uses double quotes (") for columns. Single quotes ('), backticks (`) and a few other things can be used for strings.
So I think your code is actually checking whether the value of the column `type` is a column named `bar`. No idea why this works in the test or iOS

**Comment by kuhnroyal** [comment]
@North101 Yes that is exactly the problem, on Android the column `bar` does not exist, but why does it work on iOS.

**Comment by kuhnroyal** [comment]
Maybe the custom statements can be sent through the sqlparser to find these kinds of problems.

**Comment by simolus3** [comment]
There is a way to disable double-quoted strings at runtime, but it requires varargs that `dart:ffi` doesn't support yet. My understanding is that on x86 we can just call variadic functions like regular C functions, so this works:

```dart
import 'dart:ffi';

import 'package:sqlite3/sqlite3.dart';
import 'package:sqlite3/open.dart';

typedef _config_native = Int32 Function(Pointer<Void>, Int32, Int32);
typedef _config_dart = int Function(Pointer<Void>, int, int);

const _SQLITE_DBCONFIG_DQS_DML = 1013;
const _SQLITE_DBCONFIG_DQS_DDL = 1014;

/// Utility to disable double-quoted string literals.
extension DisableDQS on Database {
  /// Disables double-quoted string literals for this database.
  void disableDoubleQuotedStrings() {
    final library = open.openSqlite();
    final setConfig = library
        .lookupFunction<_config_native, _config_dart>('sqlite3_db_config');

    setConfig(handle.cast(), _SQLITE_DBCONFIG_DQS_DDL, 0);
    setConfig(handle.cast(), _SQLITE_DBCONFIG_DQS_DML, 0);
  }
}
```

> Maybe the custom statements can be sent through the sqlparser to find these kinds of problems.

I like this idea, but a problem is that it doesn't support all statements yet. `BEGIN`/`COMMIT`/`PRAGMA` are still missing for instance. We also need to know the table structure to find that problem (`"bar"` could be a valid identifier after all, parsing is not enough). We can get that on-the-fly by reading `CREATE TABLE` statements as they come in, but this is very fragile until we support alter statements too.

I'll keep this idea in mind, but the parser isn't complete enough to support that yet.

**Comment by kuhnroyal** [comment]
Thanks!
When do I need to call this? And do you have an idea why this works by default on iOS?

**Comment by simolus3** [comment]
>When do I need to call this?

At the moment it's a bit tough, but if you're using `moor_generator` from `develop` you could use the new `SchemaVerifier.schemaAt` method to get a raw database and a connection. You can continue to use the connection for schema tests, but call `database.disableDoubleQuotedStrings` before that.

> And do you have an idea why this works by default on iOS?

If you're using `sqlite_flutter_libs` for Android, we explicitly [disable them](https://github.com/simolus3/sqlite-native-libraries/blob/master/sqlite3-native-library/cpp/CMakeLists.txt#L13) which is what sqlite's documentation recommends. iOS might not do that.

**Comment by kuhnroyal** [comment]
Ah ok, so `sqlite3_flutter_libs` uses `sqlite-native-libraries` on Android and the `sqlite3` pod on iOS while ensuring they are the same version. But they still might be compiled with different flags.

**Comment by simolus3** [comment]
Wait, we actually use the `perf-threadsafe` subspec, which [also disables DQS](https://github.com/clemensg/sqlite3pod/blob/b31d3032f58b8c5f479269d560d55a811b2cd194/sqlite3.podspec#L77-L80). Its pretty suspicious that this works on iOS. Maybe this is related to #889, but so far I've never been able to reproduce that.

**Comment by kuhnroyal** [comment]
I have not printed the sqlite version on iOS but I am using all the newer features so I always expected it to just work.
Also not using any overrides/dynamic library loading so now I am not so sure anymore.

**Comment by kuhnroyal** [comment]
Seem to be the correct version in the Simulator but my wrong migration (with double quotes) works there, so DQS can not be disabled.
```
flutter: Version(libVersion: 3.32.3, sourceId: 2020-06-18 14:16:19 02c344aceaea0d177dd42e62c8541e3cab4a26c757ba33b3a31a43ccc7d4aapl, number: 3032003)
```

**Comment by kuhnroyal** [comment]
Ok, running on an older Simulator with iOS 12.4 I get a really old version:
```
flutter: Version(libVersion: 3.24.0, sourceId: 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl, number: 3024000)
```
So it seems that the pod is not being used.

**Comment by kuhnroyal** [comment]
So after reading a bit I found out that iOS 14.x ships with sqlite `3.32.3` and 12.x with `3.24.0`.
The integration test https://github.com/simolus3/sqlite3.dart/runs/1287717728?check_suite_focus=true will currently always print the `3.32.3` version on iOS 14 and doesn't tell you if it is actually using the pod, as it is the same version as the system provided. Need to run the test on an older version.

**Comment by kuhnroyal** [comment]
@simolus3 I now found the time to apply this to my test case but it still succeeds with double quoted strings. Any idea?

```dart
  setUp(() async {
    verifier = SchemaVerifier(GeneratedHelper());
    schema = await verifier.schemaAt(4);
    from = schema.rawDatabase;
    from.disableDoubleQuotedStrings();
    to = AppDatabase.connect(schema.connection);
  });
```

**Comment by simolus3** [comment]
Huh, when I tried that out I got the error I expected. Does your double-quoted string refer to a valid column name by any chance?

**Comment by kuhnroyal** [comment]
Nope just tried this and it doesn't throw: 
```dart
    verifier = SchemaVerifier(GeneratedHelper());
    schema = await verifier.schemaAt(4);
    from = schema.rawDatabase;
    from.disableDoubleQuotedStrings();
    from.execute('SELECT * FROM foo WHERE type = "bar"');
    to = AppDatabase.connect(schema.connection);
```
And `bar` is not a valid column name.

**Comment by simolus3** [comment]
I tried to reproduce this in `extras/migration_example`:

```diff
diff --git a/extras/migrations_example/test/migration_test.dart b/extras/migrations_example/test/migration_test.dart
index d0bbca9e..4c9961ae 100644
--- a/extras/migrations_example/test/migration_test.dart
+++ b/extras/migrations_example/test/migration_test.dart
@@ -1,6 +1,10 @@
+import 'dart:ffi';
+
 import 'package:migrations_example/database.dart';
 import 'package:test/test.dart';
 import 'package:moor_generator/api/migrations.dart';
+import 'package:sqlite3/sqlite3.dart' as sqlite3;
+import 'package:sqlite3/open.dart';
 
 // Import the generated schema helper to instantiate databases at old versions.
 import 'generated/schema.dart';
@@ -8,8 +12,13 @@ import 'generated/schema.dart';
 void main() {
   SchemaVerifier verifier;
 
-  setUpAll(() {
+  setUpAll(() async {
     verifier = SchemaVerifier(GeneratedHelper());
+
+    final schema = await verifier.schemaAt(1);
+    final from = schema.rawDatabase;
+    from.disableDoubleQuotedStrings();
+    from.select('SELECT "foo";');
   });
 
   test('upgrade from v1 to v2', () async {
@@ -38,3 +47,22 @@ void main() {
     await db.close();
   });
 }
+
+typedef _config_native = Int32 Function(Pointer<Void>, Int32, Int32);
+typedef _config_dart = int Function(Pointer<Void>, int, int);
+
+const _SQLITE_DBCONFIG_DQS_DML = 1013;
+const _SQLITE_DBCONFIG_DQS_DDL = 1014;
+
+/// Utility to disable double-quoted string literals.
+extension DisableDQS on sqlite3.Database {
+  /// Disables double-quoted string literals for this database.
+  void disableDoubleQuotedStrings() {
+    final library = open.openSqlite();
+    final setConfig = library
+        .lookupFunction<_config_native, _config_dart>('sqlite3_db_config');
+
+    setConfig(handle.cast(), _SQLITE_DBCONFIG_DQS_DDL, 0);
+    setConfig(handle.cast(), _SQLITE_DBCONFIG_DQS_DML, 0);
+  }
+}
```

Selecting `"foo"` throws with the `disableDoubleQuotedStrings()` line above, the test pass otherwise. I fixed a problem that might be related in 1edcc634b1c1fc09bf444ca10854b2509bf6be7f though.

**Comment by kuhnroyal** [comment]
Can't test it cause I cant go past 6c913a481145019a8c37c3d6f2d4480ac884f83e - too many changed dependencies.

**Comment by kuhnroyal** [comment]
I have now tested this after updating to 4.2.1 - when using the extension, all false double quoting leads to unit test failures, exactly as expected.
Still wondering if the extension should be part of some test helper as this might be a more common problem.

**Comment by simolus3** [comment]
I think we could expose the `sqlite3_db_config` function in the `sqlite3` package once `dart:ffi` supports variadic functions.

The extension should work, but it feels a bit fragile to call variadic functions like that. I don't fully understand the lower-level ffi trampolines and how they might interfere with things here, but it looks like we might run into issues on some platforms: [dart-lang/sdk#38578](https://dartbug.com/38578). I'm reluctant to add that to a public api until I know for sure that it's not going to crash in some platform-specific setups.

**Comment by kuhnroyal** [comment]
Hello @simolus3, starting with Flutter/Dart 3.7.0/2.19.0 I am seeing weird `TestDeviceException`s in some of my migration tests and I have narrowed it down to the `disableDoubleQuotedStrings()` call from above.

This only occurs when there are at least 4 test functions in file where this is called before each test in the test `setUp`.
I wonder if anything changed on the FFI side.

**Comment by simolus3** [comment]
@kuhnroyal Is there any information available in the `TestDeviceException` or does the app just crash? I don't think anything should have changed on the FFI side, or at least nothing comes to mind.

**Comment by kuhnroyal** [comment]
Not much info to be had:
```
00:02 +3: Migrations<GeneratedDatabase> 36_foo should migrate foo table                                                                                                       unhandled error during finalization of test:
/Users/USER/my-app/test/unit/db/migrations/36_foo_test.dart
TestDeviceException(Shell subprocess crashed with unexpected exit code -10.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:232:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:214:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:507:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:563:11)
<asynchronous suspension>

00:02 +3: Migrations<GeneratedDatabase> 36_foo should migrate foo table - did not complete [E]                                                                                
00:02 +3: Some tests failed. 
```

If I remove the `disableDoubleQuotedStrings()` call everything succeeds :/

**Comment by kuhnroyal** [comment]
Hmm sometimes I get this preceding the above error:
```
time/vm/raw_object.cc: 356: error: Invalid cid: 0, obj: 0x11c6812d8, tags: 108. Corrupt heap?
Shell: version=2.19.1 (stable) (Tue Jan 31 12:25:35 2023 +0000) on "macos_arm64"
Shell: pid=51701, thread=14083, isolate_group=main(0x12903be00), isolate=(nil)(0x0)
Shell: os=macos, arch=arm64, comp=no, sim=no
Shell: isolate_instructions=10066e400, vm_instructions=10066e400
Shell:   pc 0x0000000100ef8c0c fp 0x00000001704b6b30 dart::Profiler::DumpStackTrace(void*)+0x90
Shell:   pc 0x0000000100d95f8c fp 0x00000001704b6b50 dart::Assert::Fail(char const*, ...) const+0x28
Shell:   pc 0x0000000100f04b70 fp 0x00000001704b6ba0 dart::UntaggedField::VisitFieldPointers(dart::FieldPtr, dart::ObjectPointerVisitor*)+0x0
Shell:   pc 0x0000000100fc4078 fp 0x00000001704b6c10 dart::ScavengerVisitorBase<true>::ProcessToSpace()+0xc4
Shell:   pc 0x0000000100fc34a4 fp 0x00000001704b6d60 dart::ScavengerVisitorBase<true>::ProcessSurvivors()+0xf8
Shell:   pc 0x0000000100fc1e88 fp 0x00000001704b6e10 dart::ParallelScavengerTask::RunEnteredIsolateGroup()+0x98
Shell:   pc 0x0000000100fc31e0 fp 0x00000001704b6e50 dart::ParallelScavengerTask::Run()+0x74
Shell:   pc 0x0000000100f8214c fp 0x00000001704b6f10 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x154
Shell:   pc 0x0000000100f82404 fp 0x00000001704b6f50 dart::ThreadPool::Worker::Main(unsigned long)+0x98
Shell:   pc 0x0000000100ef4e4c fp 0x00000001704b6fc0 dart::ThreadStart(void*)+0xb4
Shell:   pc 0x00000001aeb6e06c fp 0x00000001704b6fe0 _pthread_start+0x94
Shell: -- End of DumpStackTrace
unhandled error during finalization of test
``

**Comment by kuhnroyal** [comment]
Ok, I now converted this to a plain Dart test by copying everything to a new project. It also happens with `dart test` but I get a full stack:

EDIT:
This is a different stack, fails to disable DQS.

```
00:03 +0: test/migrations/36_migrate_paths_test.dart: Migrations<GeneratedDatabase> 36_migrate_paths should create schema when migrating from 35                                                       
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=2, si_addr=0x1
version=2.19.1 (stable) (Tue Jan 31 12:25:35 2023 +0000) on "macos_arm64"
pid=61274, thread=15619, isolate_group=main(0x10e808600), isolate=main(0x10e80f200)
os=macos, arch=arm64, comp=no, sim=no
isolate_instructions=100670d80, vm_instructions=100670d80
  pc 0x0000000128c8f988 fp 0x0000000170261250 sqlite3_db_config+0x14c
  pc 0x0000000103106e28 fp 0x0000000170261280 Unknown symbol
  pc 0x0000000129842118 fp 0x00000001702612c0 Unknown symbol
  pc 0x0000000129841f0c fp 0x0000000170261320 Unknown symbol
  pc 0x0000000128ac2e60 fp 0x00000001702613c8 Unknown symbol
  pc 0x000000010c0e8540 fp 0x0000000170261418 Unknown symbol
  pc 0x000000010c0de500 fp 0x0000000170261498 Unknown symbol
  pc 0x000000010c0de30c fp 0x0000000170261500 Unknown symbol
  pc 0x000000010c0de124 fp 0x0000000170261598 Unknown symbol
  pc 0x000000010c0e8164 fp 0x00000001702615e8 Unknown symbol
  pc 0x000000010c0e7d6c fp 0x0000000170261648 Unknown symbol
  pc 0x000000010c0e6cb0 fp 0x00000001702616c8 Unknown symbol
  pc 0x000000010c0e5508 fp 0x0000000170261710 Unknown symbol
  pc 0x0000000128aac418 fp 0x0000000170261758 Unknown symbol
  pc 0x0000000103107e60 fp 0x0000000170261788 Unknown symbol
  pc 0x000000010c0e8540 fp 0x00000001702617d8 Unknown symbol
  pc 0x000000010c0de500 fp 0x0000000170261858 Unknown symbol
  pc 0x000000010c0de30c fp 0x00000001702618c0 Unknown symbol
  pc 0x000000010c0de124 fp 0x0000000170261958 Unknown symbol
  pc 0x000000010c0e8164 fp 0x00000001702619a8 Unknown symbol
  pc 0x000000010c0e7d6c fp 0x0000000170261a08 Unknown symbol
  pc 0x000000010c0e6cb0 fp 0x0000000170261a88 Unknown symbol
  pc 0x000000010c0e5508 fp 0x0000000170261ad0 Unknown symbol
  pc 0x0000000128aac418 fp 0x0000000170261b18 Unknown symbol
  pc 0x0000000103107e60 fp 0x0000000170261b48 Unknown symbol
  pc 0x000000010c0e8540 fp 0x0000000170261b98 Unknown symbol
  pc 0x000000010c0de500 fp 0x0000000170261c18 Unknown symbol
  pc 0x000000010c0de30c fp 0x0000000170261c80 Unknown symbol
  pc 0x000000010c0de124 fp 0x0000000170261d18 Unknown symbol
  pc 0x000000010c0e8164 fp 0x0000000170261d68 Unknown symbol
  pc 0x000000010c0e7d6c fp 0x0000000170261dc8 Unknown symbol
  pc 0x000000010c0e6cb0 fp 0x0000000170261e48 Unknown symbol
  pc 0x000000010c0e5508 fp 0x0000000170261e90 Unknown symbol
  pc 0x0000000128aac418 fp 0x0000000170261ed8 Unknown symbol
  pc 0x0000000103107e60 fp 0x0000000170261f08 Unknown symbol
  pc 0x000000010c0e8540 fp 0x0000000170261f58 Unknown symbol
  pc 0x000000010c0de500 fp 0x0000000170261fd8 Unknown symbol
  pc 0x000000010c0de30c fp 0x0000000170262040 Unknown symbol
  pc 0x000000010c0de124 fp 0x00000001702620d8 Unknown symbol
  pc 0x0000000128aa2b40 fp 0x0000000170262128 Unknown symbol
  pc 0x000000010c0cbac0 fp 0x00000001702621a0 Unknown symbol
  pc 0x000000010c0cb734 fp 0x0000000170262200 Unknown symbol
  pc 0x000000010c0cae3c fp 0x0000000170262290 Unknown symbol
  pc 0x000000010c0e5058 fp 0x0000000170262300 Unknown symbol
  pc 0x000000010c0e4f04 fp 0x0000000170262340 Unknown symbol
  pc 0x000000010c0e4be4 fp 0x0000000170262388 Unknown symbol
  pc 0x000000010c0e4774 fp 0x00000001702623c8 Unknown symbol
  pc 0x000000010c0e466c fp 0x00000001702623f0 Unknown symbol
  pc 0x000000010c0dbb38 fp 0x0000000170262430 Unknown symbol
  pc 0x0000000128abb8c4 fp 0x00000001702624b0 Unknown symbol
  pc 0x0000000128ab9ad8 fp 0x00000001702624e8 Unknown symbol
  pc 0x0000000128ab97a4 fp 0x0000000170262518 Unknown symbol
  pc 0x000000010c0a8720 fp 0x0000000170262580 Unknown symbol
  pc 0x000000010c0a7bac fp 0x00000001702625d8 Unknown symbol
  pc 0x0000000103103518 fp 0x00000001702626b0 Unknown symbol
  pc 0x00000001007945d0 fp 0x0000000170262750 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x140
  pc 0x000000010079443c fp 0x00000001702627b0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x128
  pc 0x0000000100796960 fp 0x00000001702627f0 dart::DartLibraryCalls::HandleMessage(long long, dart::Instance const&)+0x12c
  pc 0x00000001007ba8ec fp 0x0000000170262da0 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>)+0x2e8
  pc 0x00000001007e336c fp 0x0000000170262e10 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x154
  pc 0x00000001007e3aa8 fp 0x0000000170262e70 dart::MessageHandler::TaskCallback()+0x204
  pc 0x0000000100910b84 fp 0x0000000170262f30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14c
  pc 0x0000000100910f70 fp 0x0000000170262f60 dart::ThreadPool::Worker::Main(unsigned long)+0x84
  pc 0x00000001008836c8 fp 0x0000000170262fc0 dart::OSThread::GetMaxStackSize()+0xac
  pc 0x00000001aeb6e06c fp 0x0000000170262fe0 _pthread_start+0x94
-- End of DumpStackTrace
  pc 0x0000000000000000 fp 0x0000000170261280 sp 0x0000000000000000 Cannot find code object
  pc 0x0000000129842118 fp 0x00000001702612c0 sp 0x0000000170261290 [Optimized] FfiTrampoline_DisableDQS.disableDoubleQuotedStrings
  pc 0x0000000129841f0c fp 0x0000000170261320 sp 0x00000001702612d0 [Unoptimized] DisableDQS|disableDoubleQuotedStrings
  pc 0x0000000128ac2e60 fp 0x00000001702613c8 sp 0x0000000170261330 [Unoptimized] DatabaseMigrationTester.create
  pc 0x000000010c0e8540 fp 0x0000000170261418 sp 0x00000001702613d8 [Unoptimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x000000010c0de500 fp 0x0000000170261498 sp 0x0000000170261428 [Unoptimized] _rootRunUnary@4048458
  pc 0x000000010c0de30c fp 0x0000000170261500 sp 0x00000001702614a8 [Unoptimized] _rootRunUnary@4048458
  pc 0x000000010c0de124 fp 0x0000000170261598 sp 0x0000000170261510 [Unoptimized] _CustomZone@4048458.runUnary
  pc 0x000000010c0e8164 fp 0x00000001702615e8 sp 0x00000001702615a8 [Unoptimized] _FutureListener@4048458.handleValue
  pc 0x000000010c0e7d6c fp 0x0000000170261648 sp 0x00000001702615f8 [Unoptimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000010c0e6cb0 fp 0x00000001702616c8 sp 0x0000000170261658 [Unoptimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000010c0e5508 fp 0x0000000170261710 sp 0x00000001702616d8 [Unoptimized] _Future@4048458._completeWithValue@4048458
  pc 0x0000000128aac418 fp 0x0000000170261758 sp 0x0000000170261720 [Unoptimized] _SuspendState@4048458._returnAsyncNotFuture@4048458
  pc 0x0000000103107e60 fp 0x0000000170261788 sp 0x0000000170261768 [Stub] ReturnAsyncNotFuture
  pc 0x000000010c0e8540 fp 0x00000001702617d8 sp 0x0000000170261798 [Unoptimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x000000010c0de500 fp 0x0000000170261858 sp 0x00000001702617e8 [Unoptimized] _rootRunUnary@4048458
  pc 0x000000010c0de30c fp 0x00000001702618c0 sp 0x0000000170261868 [Unoptimized] _rootRunUnary@4048458
  pc 0x000000010c0de124 fp 0x0000000170261958 sp 0x00000001702618d0 [Unoptimized] _CustomZone@4048458.runUnary
  pc 0x000000010c0e8164 fp 0x00000001702619a8 sp 0x0000000170261968 [Unoptimized] _FutureListener@4048458.handleValue
  pc 0x000000010c0e7d6c fp 0x0000000170261a08 sp 0x00000001702619b8 [Unoptimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000010c0e6cb0 fp 0x0000000170261a88 sp 0x0000000170261a18 [Unoptimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000010c0e5508 fp 0x0000000170261ad0 sp 0x0000000170261a98 [Unoptimized] _Future@4048458._completeWithValue@4048458
  pc 0x0000000128aac418 fp 0x0000000170261b18 sp 0x0000000170261ae0 [Unoptimized] _SuspendState@4048458._returnAsyncNotFuture@4048458
  pc 0x0000000103107e60 fp 0x0000000170261b48 sp 0x0000000170261b28 [Stub] ReturnAsyncNotFuture
  pc 0x000000010c0e8540 fp 0x0000000170261b98 sp 0x0000000170261b58 [Unoptimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x000000010c0de500 fp 0x0000000170261c18 sp 0x0000000170261ba8 [Unoptimized] _rootRunUnary@4048458
  pc 0x000000010c0de30c fp 0x0000000170261c80 sp 0x0000000170261c28 [Unoptimized] _rootRunUnary@4048458
  pc 0x000000010c0de124 fp 0x0000000170261d18 sp 0x0000000170261c90 [Unoptimized] _CustomZone@4048458.runUnary
  pc 0x000000010c0e8164 fp 0x0000000170261d68 sp 0x0000000170261d28 [Unoptimized] _FutureListener@4048458.handleValue
  pc 0x000000010c0e7d6c fp 0x0000000170261dc8 sp 0x0000000170261d78 [Unoptimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000010c0e6cb0 fp 0x0000000170261e48 sp 0x0000000170261dd8 [Unoptimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000010c0e5508 fp 0x0000000170261e90 sp 0x0000000170261e58 [Unoptimized] _Future@4048458._completeWithValue@4048458
  pc 0x0000000128aac418 fp 0x0000000170261ed8 sp 0x0000000170261ea0 [Unoptimized] _SuspendState@4048458._returnAsyncNotFuture@4048458
  pc 0x0000000103107e60 fp 0x0000000170261f08 sp 0x0000000170261ee8 [Stub] ReturnAsyncNotFuture
  pc 0x000000010c0e8540 fp 0x0000000170261f58 sp 0x0000000170261f18 [Unoptimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
  pc 0x000000010c0de500 fp 0x0000000170261fd8 sp 0x0000000170261f68 [Unoptimized] _rootRunUnary@4048458
  pc 0x000000010c0de30c fp 0x0000000170262040 sp 0x0000000170261fe8 [Unoptimized] _rootRunUnary@4048458
  pc 0x000000010c0de124 fp 0x00000001702620d8 sp 0x0000000170262050 [Unoptimized] _CustomZone@4048458.runUnary
  pc 0x0000000128aa2b40 fp 0x0000000170262128 sp 0x00000001702620e8 [Unoptimized] _SuspendState@4048458._awaitNotFuture@4048458.run
  pc 0x000000010c0cbac0 fp 0x00000001702621a0 sp 0x0000000170262138 [Unoptimized] _rootRun@4048458
  pc 0x000000010c0cb734 fp 0x0000000170262200 sp 0x00000001702621b0 [Unoptimized] _rootRun@4048458
  pc 0x000000010c0cae3c fp 0x0000000170262290 sp 0x0000000170262210 [Unoptimized] _CustomZone@4048458.run
  pc 0x000000010c0e5058 fp 0x0000000170262300 sp 0x00000001702622a0 [Unoptimized] _CustomZone@4048458.runGuarded
  pc 0x000000010c0e4f04 fp 0x0000000170262340 sp 0x0000000170262310 [Unoptimized] _CustomZone@4048458.bindCallbackGuarded.<anonymous closure>
  pc 0x000000010c0e4be4 fp 0x0000000170262388 sp 0x0000000170262350 [Unoptimized] _microtaskLoop@4048458
  pc 0x000000010c0e4774 fp 0x00000001702623c8 sp 0x0000000170262398 [Unoptimized] _startMicrotaskLoop@4048458
  pc 0x000000010c0e466c fp 0x00000001702623f0 sp 0x00000001702623d8 [Unoptimized] _startMicrotaskLoop@4048458
  pc 0x000000010c0dbb38 fp 0x0000000170262430 sp 0x0000000170262400 [Unoptimized] _runPendingImmediateCallback@1026248
  pc 0x0000000128abb8c4 fp 0x00000001702624b0 sp 0x0000000170262440 [Unoptimized] _Timer@1026248._runTimers@1026248
  pc 0x0000000128ab9ad8 fp 0x00000001702624e8 sp 0x00000001702624c0 [Unoptimized] _Timer@1026248._handleMessage@1026248
  pc 0x0000000128ab97a4 fp 0x0000000170262518 sp 0x00000001702624f8 [Unoptimized] _Timer@1026248._handleMessage@1026248
  pc 0x000000010c0a8720 fp 0x0000000170262580 sp 0x0000000170262528 [Unoptimized] _Closure@0150898.dyn:call
  pc 0x000000010c0a7bac fp 0x00000001702625d8 sp 0x0000000170262590 [Unoptimized] _RawReceivePort@1026248._handleMessage@1026248
  pc 0x0000000103103518 fp 0x00000001702626b0 sp 0x00000001702625e8 [Stub] InvokeDartCode
```

**Comment by kuhnroyal** [comment]
> My understanding is that on x86 we can just call variadic functions like regular C functions, so this works.

Maybe that is the problem, this is Arm64 :)

**Comment by simolus3** [comment]
Looking at this some more, it seems like I've misused `sqlite3_db_config` all this time. It doesn't appear to be documented, but sqlite3 actually uses [two vararg parameters](https://github.com/sqlite/sqlite/blob/51b0373998e820ba81bab459e9134c4a9cec6225/src/main.c#L962-L975), with the second being a pointer to which, if non-null, the result will be written to. I don't know enough about this to be sure, but I'd guess that we were just lucky on x86 and it passes `0` for additional varargs that aren't set. On arm, sqlite probably writes into an undefined address which causes the crash.

We can fix this by passing a `nullptr` as a second argument, but Dart can't currently do that on arm - we'd have to wait for Dart 3 to get variadic FFI.

However, we can wrap the config call in a C library:

```C
#include <sqlite3.h>

int disable_dqs(sqlite3 *db) {
  int rc = sqlite3_db_config(db, SQLITE_DBCONFIG_DQS_DML, 0, 0);
  if (!rc) {
    rc = sqlite3_db_config(db, SQLITE_DBCONFIG_DQS_DDL, 0, 0);
  }
}
```

Then you can compile it with `clang -dynamiclib -lsqlite3 -o libhelper.dylib test.c`, load the library in the test and call it with `handle.cast()` and no further arguments.

**Comment by kuhnroyal** [comment]
Interesting, since I only use it for tests, I will just wait for Dart 3.

But this morning my team discovered, that it also fails on x86 with Dart 2.19.
The errors are not consistent in Flutter tests, most of the time the tests are successful.
In plain Dart, the error always surfaces.

So I am not sure why this worked 2 years ago and it doesn't now :)
Maybe something has changed in sqlite, maybe in FFI, maybe it never worked in plain Dart, no idea.

**Comment by kuhnroyal** [comment]
Hello @simolus3 just wanted to let you know that in sqlite 3.41.0 changed the behavior here. I am not exactly clear on wether this is now enabled or disabled in the sqlite_flutter_libs.
But after updating my local sqlite this started failing on MacOS/CI even with the workaround from above.

> As of SQLite 3.41.0 (2023-02-21) SQLITE_DBCONFIG_DQS_DDL and SQLTIE_DBCONFIG_DQS_DML are disabled by default in the [CLI](https://www.sqlite.org/cli.html). Use the ".dbconfig" dot-command to reenable the legacy behavior if desired.

**Comment by simolus3** [comment]
I've tried to reproduce this in a Dart VM (so without `sqlite3_flutter_libs`) as well as in a Flutter project with `sqlite3_flutter_libs` on macOS.

I'm disabling DQS by using `setup: (rawDb) => rawDb.config.doubleQuotedStringLiterals = false`. Both with the system's sqlite3 in a pure Dart setup (to be fair, 3.39.5 on macOS but 3.43 on my Linux PC) and with the Flutter app, I get exceptions for double quoted strings.

**Comment by kuhnroyal** [comment]
Yea, it seems I still had tests that were not configured with `disableDoubleQuotedStrings()` and those suddenly started failing since the default (at least in the MacOS ARM binary via brew) has changed. So for desktop use, the defaults may have changed.
 
In any case, I removed the few last occurrences in our code and now use the default settings.

Thanks and sorry for the noise!
