### ISSUE TITLE
NoSuchMethodError: Class '_Comparison' has no instance method '&'.

### ISSUE THREAD

**Issue by ggqshr** [simolus3/moor#961]
Hi,when i use `batch.update`, and set where parameter just like that
```dart
Future<void> updateMany(List<DeviceData> datas)async{
    return await (batch((b){
      for (var data in datas){
        b.update(device, data,where: (t)=>t.taskId.equals(data.taskId) & t.id.equals(data.id));
      }
    }));
  }
```
When this method executes, I get this exception:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: Class '_Comparison' has no instance method '&'.
E/flutter ( 6771): Receiver: Instance of '_Comparison'
E/flutter ( 6771): Tried calling: &(Instance of '_Comparison')
E/flutter ( 6771): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 6771): #1      DeviceDB.updateMany.<anonymous closure>.<anonymous closure> (package:ifcy/common/dao/device_dao.dart:74:72)
E/flutter ( 6771): #2      SingleTableQueryMixin.where (package:moor/src/runtime/query_builder/statements/query.dart:179:29)
E/flutter ( 6771): #3      Batch.update (package:moor/src/runtime/api/batch.dart:88:29)
E/flutter ( 6771): #4      DeviceDB.updateMany.<anonymous closure> (package:ifcy/common/dao/device_dao.dart:74:11)
E/flutter ( 6771): #5      QueryEngine.batch (package:moor/src/runtime/api/query_engine.dart:390:30)
E/flutter ( 6771): #6      DeviceDB.updateMany (package:ifcy/common/dao/device_dao.dart:72:19)
E/flutter ( 6771): #7      DeviceCheckDataProvider.updateLocalBatch (package:ifcy/device_staff/repositories/device_check_repositories.dart:36:15)
E/flutter ( 6771): #8      DeviceCheckRepositories.updateLocal (package:ifcy/device_staff/repositories/device_check_repositories.dart:84:18)
E/flutter ( 6771): <asynchronous suspension>
E/flutter ( 6771): #9      DeviceStaffDeviceCheckBloc._mapLoadDeviceToState (package:ifcy/device_staff/blocs/device_staff_device_check_bloc/device_staff_device_check_bloc.dart:54:23)
E/flutter ( 6771): <asynchronous suspension>
E/flutter ( 6771): #10     DeviceStaffDeviceCheckBloc.mapEventToState (package:ifcy/device_staff/blocs/device_staff_device_check_bloc/device_staff_device_check_bloc.dart:40:14)
E/flutter ( 6771): <asynchronous suspension>
E/flutter ( 6771): #11     Bloc._bindEventsToStates.<anonymous closure> (package:bloc/src/bloc.dart:252:20)
E/flutter ( 6771): #12     Stream.asyncExpand.onListen.<anonymous closure> (dart:async/stream.dart:576:30)
E/flutter ( 6771): #13     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 6771): #14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 6771): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 6771): #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
E/flutter ( 6771): #17     _DelayedData.perform (dart:async/stream_impl.dart:593:14)
E/flutter ( 6771): #18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
E/flutter ( 6771): #19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
E/flutter ( 6771): #20     _rootRun (dart:async/zone.dart:1122:38)
E/flutter ( 6771): #21     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 6771): #22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 6771): #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 6771): #24     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 6771): #25     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 6771): #26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 6771): #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 6771): #28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 6771): #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 6771): 

```
But using update directly is fine,like this:
```dart
Future<int> updateLocal(DeviceData data) async {
    return await (update(device)
          ..where(
              (t) => t.taskId.equals(data.taskId) & t.id.equals(data.id) ))
        .write(DeviceCompanion(
      comment: Value(data.comment),
      checkStatus: Value(data.checkStatus),
      checkResult: Value(data.checkResult),
      images: Value(data.images),
    ));
  }
```

I do not know why, am I using it wrong?

**Comment by simolus3** [comment]
The problem is that `&` is an extension method. I think this might be related to `t` being inferred as `dynamic`.

Does it work if you do this?

```dart
b.update(device, data,where: (Device t)=>t.taskId.equals(data.taskId) & t.id.equals(data.id));
```

**Comment by ggqshr** [comment]
> The problem is that `&` is an extension method. I think this might be related to `t` being inferred as `dynamic`.
> 
> Does it work if you do this?
> 
> ```dart
> b.update(device, data,where: (Device t)=>t.taskId.equals(data.taskId) & t.id.equals(data.id));
> ```

Thanks a lot, that's work for me, and thanks again for this awesome library!
